### ISSUE TITLE
When does the "irrelevant" event trigger?

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#102]
Hi,

I was just wondering, what are the requirements for the "irrelevant" event to trigger?

I was trying something like this:

```javascript
var key = 'id1';
var cursor = stateTree.select('admin', 'notificationsMap', key);
cursor.on('irrelevant', function () {
  console.log('no more data here');
});
var parent = cursor.up();
var parentMap = parent.get();
delete parentMap[key];
parent.edit(parentMap);
```
The event does not trigger. Will this be fixed with the new `remove` method maybe?

**Comment by christianalfoni** [comment]
Btw, is this handled in the React Mixin? Is that state related to the cursor removed from the state object when it becomes irrelevant?

**Comment by Yomguithereal** [comment]
I guess that, after your last PR, the only remaining point here is what does the react mixin concerning the `relevant` and `irrelevant` cursors? Well for the time being the answer might be disappointing: nothing (well related state will refer to undefined and `this.cursor.get` will return, expectedly, the same).

Do you think something more could be done in this regard?

**Comment by christianalfoni** [comment]
Hm, the only thing I can think of is that when the cursor becomes irrelevant it should remove the value from the state of component too. It has to keep things in sync.

So basically, the tree and cursor mixin also has to listen for `irrelevant` and `relevant`. `irellevant` deleting the cursor key on the `this.state.cursors` object, and `relevant` putting it back. Could create a pull for this, just have to get my head above water first :-)

**Comment by Yomguithereal** [comment]
Is there really a difference between unsetting the `cursor` key of the state rather than solving their values to `undefined`?

**Comment by christianalfoni** [comment]
Yup, I think so.

Lets say you have a map of items where the key is ID. Then you want to pass all those items to the server. You grab them off a cursor... but... one of them is undefined, it should never have gone to the server :-)

Did I understand this correctly?

**Comment by Yomguithereal** [comment]
Following up in Yomguithereal/baobab-react#29.
