### ISSUE TITLE
suggestion to add link for a good post about baobab

### ISSUE THREAD

**Issue by asfktz** [Yomguithereal/baobab#105]
this blog post really help me understand how to use baobab,
maybe it will be valuable for others to mention it in the readme?

http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html

**Comment by Yomguithereal** [comment]
@christianalfoni, is that ok for you if I link towards your article in the documentation?

**Comment by christianalfoni** [comment]
Of course, it would be an honor ;-)

Btw, I am writing up a new article now which will also get a pull request. I have figured out something really awesome. It is a way to use contexts of React JS with Baobab to build isomorphic apps.

Using it on a project I am working on https://github.com/christianalfoni/EmptyBox.

I hope to get the article out today, really excited about it :-)

**Comment by jessep** [comment]
:+1: I just came here to post this same suggestion.

**Comment by Yomguithereal** [comment]
v1 just landed @christianalfoni. Should we rewrite the blog post a little to account for the changes?

**Comment by christianalfoni** [comment]
Writing a new article :-) Will insert link to new article in old one when it is done.
