### ISSUE TITLE
Avoid loading json file

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#106]
Hi there,

When using webpack you have to download a specific json loader to load up baobab. Would it be okay to avoid loading a json file? Webpack is having great momentum these days and its too bad that this module requires an additional loader to work :-)

**Comment by milanlandaverde** [comment]
+1

**Comment by Yomguithereal** [comment]
Other question: does webpack shims `process`? If not, I should change some tiny things to make it work.

**Comment by christianalfoni** [comment]
Yup it shims/polyfills it :-)
