### ISSUE TITLE
Simplify React JS mixin cursors

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#110]
Hi there,

I have been thinking about the mixins and how you define cursors. I think it would be a lot more powerful and easier to understand if you narrowed down how mixin cursors work to just this:

```js
var MyComponent = React.createClass({
  mixins: [tree.mixin],
  cursors: {
    todos: ['todos', 'items'],
    isLoading: ['todos', 'isLoading']
  },
  render: function () {
    return (
     <div>{this.state.todos.length} and {this.state.isLoading}</div>
    );
  }
});
```

Just remove cursor and cursors property using arrays. What we gain by this is:

1. There is only one way to do it, and it is the best way to do it (most flexible)
2. You can name the property on the state, which can differ from the name on the cursor
3. You can put the cursor data directly on the state, not under a `this.state.cursors.todos`
4. By only having a store mixin you always have access to all data (best practice)

It is really annoying that you can not use this state directly as it is just too much to write inline with your JSX. `this.state.cursors.todos` and `this.state.todos`.

I am not sure how a transition to this one single format could work, but a suggestion is:

- Breaking API change
- Deprecate the cursor and cursors array format, but keep it for a couple of more versions
- Deprecate cursor mixins

I think it would really clean up the library and make it easier to use and understand :-)

**Comment by Yomguithereal** [comment]
The only thing that scares me with this approach is a potential incompatibility with some components already using specific keys on their states that would conflict by the names of the keys in your store.

**Comment by christianalfoni** [comment]
Hi :-)

I see your point, but the key you use to define a cursor is the key that
will be used on the state object. You define your "getInitialState" and
cursor keys in the same file, so you have to work pretty hard to get a
conflict. And if you do, it is as easy as changing either the
"getInitialState" key or cursor key. Could even state an error from Baobab
in case of conflicting keys.

**Comment by christianalfoni** [comment]
This would also allow for letting the user use a function instead of a map:

```js
var MyComponent = React.createClass({
  mixins: [tree.mixin],
  cursors: function () {
    return {
      todos: this.props.todosCursor,
      isLoading: ['todos', 'isLoading']
    };
  },
  render: function () {
    return (
     <div>{this.state.todos.length} and {this.state.isLoading}</div>
    );
  }
});
```
Allowing you to use instance properties etc.

**Comment by mkuklis** [comment]
@christianalfoni  I love this.

**Comment by Yomguithereal** [comment]
I like where this is going. This feature, as well as the removal of `state.key` will probably make it to the v1.

**Comment by RJ** [comment]
:+1: for removing the ".cursors" bit and putting the data directly in state

also, I would find it very useful to be able to use instance properties in cursor paths like this:
````javascript
    var Channel = React.createClass({
      mixins: [tree.mixin],
      cursor: ['channels', this.props.id] // this.props not valid here
      },
      render: function () {
          ... <h1>{this.state.cursor.name}</h1>
      }
    });
````

This seems like a nice option to have, and would solve the problems i'm having with dynamic cursor paths:

````javascript
    var Channel = React.createClass({
      mixins: [tree.mixin],
      cursor: function(){ return ['channels', this.props.id]; },
      },
      render: function () {
          ... <h1>{this.state.cursor.name}</h1>
      }
    });
````

**Comment by Yomguithereal** [comment]
This will make it into the `1.0.0` version, normally. Even if I have some difficulties to sketch how the mixin would work under the hood to perform this.

**Comment by christianalfoni** [comment]
@Yomguithereal We built a mixin like this at our company that has this behavior. Would be happy to contribute with a 1.0 mixin :-)

**Comment by RJ** [comment]
@christianalfoni I'd like to see that, is it already published somewhere?

Discovered Baobab from your blog post btw, so thanks for that :)

**Comment by christianalfoni** [comment]
@RJ You are very welcome :-)

Let me just paste the code here with comments. I did some changes to this after pasting it so might be a bug here, but you will figure that out if you want to test, I am sure :-)

This mixin allows you to do:

```js
var Comp = React.createClass({
  cursors: function () {
    return {
      list: ['admin', 'todos'] // cursor key decides state key
    }
  },
  render: function () {
    // this.state.list
  }
};
```
Have to merge this with existing cursor to also allow using a map as cursors. 

```js
// The mixin needs a reference to your Baobab instance
var stateTree = require('./stateTree.js');

/*
 * Grabbed code from React lib as it will not change and we reduce
 * a dependency with one. Also testing becomes easier
 */
var shallowEqual = function shallowEqual(objA, objB) {
  if (objA === objB) {
    return true;
  }
  var key;
  // Test for A's keys different from B.
  for (key in objA) {
    if (objA.hasOwnProperty(key) &&
        (!objB.hasOwnProperty(key) || objA[key] !== objB[key])) {
      return false;
    }
  }
  // Test for B's keys missing from A.
  for (key in objB) {
    if (objB.hasOwnProperty(key) && !objA.hasOwnProperty(key)) {
      return false;
    }
  }
  return true;
};

var ReactComponentWithPureRenderMixin = {
  shouldComponentUpdate: function(nextProps, nextState) {
    return !shallowEqual(this.props, nextProps) ||
           !shallowEqual(this.state, nextState);
  }
};

module.exports = {
  mixins: [ReactComponentWithPureRenderMixin],
  cursorSubscriptions: null,
  ignoreCursorUpdate: false,
  onCursorUpdate: function () {

    // There can be multiple updates on the same tick,
    // ignore those, as we only need one update
    if (this.ignoreCursorUpdate)  {
      return;
    }

    this.ignoreCursorUpdate = true;
    setTimeout(function () {
      this.ignoreCursorUpdate = false;
      this.setCurrentCursorsValues();
    }.bind(this), 0);

  },

  // Remove data from component when cursor is removed
  onIrellevant: function (event) {

    // Wait for next event tick
    setTimeout(function () {
      var key = event.target.path.slice(0).pop();
      delete this.state[key];
      this.setState(this.state);
    }.bind(this), 0);
  },
  getCurrentCursorsValues: function () {

    var cursors = this.cursorSubscriptions;
    return Object.keys(cursors).reduce(function (cursorsValues, cursorKey) {
      cursorsValues[cursorKey] = cursors[cursorKey].get();
      return cursorsValues;
    }, {});

  },
  setCurrentCursorsValues: function () {

    // If there is a cursor update while unmounting,
    // let us just return
    if (!this.isMounted()) {
      return;
    }

    var cursorsValues = this.getCurrentCursorsValues();

    // attach to state
    this.setState(cursorsValues);

  },
  componentWillMount: function () {
    
    // Might not have any cursors
    if (!this.cursors) {
      return;
    }

    // Make sure cursors is a function
    if (typeof this.cursors !== 'function') {
      throw new Error('You have to use a function and return cursors in an object on ' + this.constructor.displayName);
    }

    var cursors = this.cursors();

    // Add actual cursors to map and listen to changes
    this.cursorSubscriptions = Object.keys(cursors).reduce(function (subscriptions, key) {
      var cursor = stateTree.select(cursors[key]);
      cursor.on('update', this.onCursorUpdate);

      // Have to wait for next event loop, as the data might still be comitting
      setTimeout(function () { 
        cursor.on('irrelevant', this.onIrellevant); 
      }.bind(this), 0);

      subscriptions[key] = cursor;
      return subscriptions;
    }.bind(this), {});

    this.setCurrentCursorsValues();

  },
  componentWillUnmount: function () {
    if (this.cursorSubscriptions) {
      Object.keys(this.cursorSubscriptions).forEach(function (key) {
        this.cursorSubscriptions[key].off('update', this.onCursorUpdate);
        this.cursorSubscriptions[key].off('irrelevant', this.onIrellevant);
      }, this);
    }
  }
}
```
Okay, let me know if you try it and get into trouble, would maybe we can work on it here and make it ready as a suggestion for 1.0 :-)

**Comment by Yomguithereal** [comment]
@christianalfoni, I think you can use the library [combinations](https://github.com/Yomguithereal/baobab/blob/master/src/combination.js) to simplify your mixin's update listeners. Example [here](https://github.com/Yomguithereal/baobab/blob/master/src/mixins.js#L91).

I don't think those are accessible outside of the library but you can still use the cursors' `or` method to build it.

**Comment by nickdima** [comment]
1. Would be possible for the mixin to not depend on the Baobab instance and instead pass the instance (and maybe also the cursors) somehow from inside the component?
2. Are you looking at coming up with an alternative to the mixin for react 0.13 so that it can be used with ES6 classes? Higher-order Components could be an alternative maybe https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775
I just started playing out with Baobab but I'll gladly help if come up with something.

**Comment by nickdima** [comment]
Another great example would be `FluxComponent` from [flummox](https://github.com/acdlite/flummox)
https://github.com/acdlite/flummox/blob/master/docs/why-flux-component-is-better-than-flux-mixin.md

**Comment by Yomguithereal** [comment]
Those are interesting concepts @nickdima, I'll check that more thoroughly soon.

What should be done to enhance ES6 classes compatibility?

**Comment by nickdima** [comment]
As ES6 classes don't have any standard way of doing mixins, React decided they won't implement their own proprietary system. More details here, look for the Mixins section: http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by christianalfoni** [comment]
Hi guys! 

Got the flue last weekend so been on the couch all week, but back now :-)

Here are my thoughts on this.

I think it would be nice to create three different interactions with Baobab and React:

1. Mixin from the tree instance
```js
var tree = require('./tree.js');
var Comp = React.createClass({
  mixins: [tree.mixin],
  cursors: function () {
    return {
      items: ['items']
    };
  },
  // or
  cursors: {
    items: ['items']
  },
  render: function () { ... }
});
```
2. ContextMixin where the tree is passed in the context
Unsure how to handle the key of the context. It probably needs to have a specific key, like *baobab*. 

var Baobab = require('baobab');
```js
var Comp = React.createClass({
  mixins: [Baobab.ContextMixin],
  contextTypes: {
    baobab: React.PropTypes.Object
  },
  cursors: function () {
    return {
      items: ['items']
    };
  },
  // or
  cursors: {
    items: ['items']
  },
  render: function () { ... }
});
```
3. Extend class 
```js
var tree = require('./tree.js');
class MyComponent extends React.Component {
  constructor () {
    tree.applyCursors(this, {
      items: ['items']
    });
  }
}
```

Just some suggestion to try to narrow down a spec for the different scenarios Baobab could handle :-)

**Comment by Yomguithereal** [comment]
Moving this discussion to this [repository](https://github.com/Yomguithereal/baobab-react).

**Comment by christianalfoni** [comment]
Been so busy lately @Yomguithereal , just checked out the repo. It looks freakin awesome! I think you did a great choice here moving it to its own repo!
