### ISSUE TITLE
Support transactions

### ISSUE THREAD

**Issue by slorber** [Yomguithereal/baobab#112]
Hi,

As mentionned on twitter I'm looking at baobab and see if I could use it as data structure in my framework https://github.com/stample/atom-react

I haven't seen anything related to transaction management.

My idea of this is that you can actually call "set" on 2 different cursors, and this only produces a single re-rendering because you don't want to render intermediate states that could be inconsistent.

Also, you would want to render before transaction commit as if the React rendering for a given state is buggy, you 'd rather not commit the transaction and rollback to the last state that was rendered successfully. Otherwise this may "lock" the UI as all former states created from the buggy state may probably be buggy too.

See how I implemented this:
https://github.com/stample/atom-react/blob/master/src/atom/atom.js

And an example usage here:
https://github.com/stample/atom-react/blob/master/examples/todomvc/js/components/TodoItem.react.js#L79

```javascript
_onSave: function(text) {
    this.transact(function() {
      this.publish(TodoEvents.updateText(this.todo().id,text));
      this.props.todoCursor.follow("isEditing").unset();
      this.props.todoCursor.follow("editionText").unset();
    }.bind(this));
  },
```

**Comment by slorber** [comment]
Also it would be nice if the cursors could have configurable semantics like "read-your-writes" or "memoization" (inside transactions or not)

**Comment by Yomguithereal** [comment]
Hello @slorber,
First of all, transactions already exist in Baobab. If you call set twice on the same element, the tree will merge the updates and only apply the last one in the stack.

Secondly, by default the tree commits its changes asynchronously, meaning that you won't have any "transitionnal" renders.

If you need to commit the changes synchronously once because you need it, you remain free to use the `tree.commit` method.

**Comment by Yomguithereal** [comment]
> Also it would be nice if the cursors could have configurable semantics like "read-your-writes" or "memoization" (inside transactions or not)

I don't understand this part, could you develop a bit more please?

**Comment by slorber** [comment]
I mean that you can read what you writes immediately.
If a cursor is backed by 0, you can do cursor.inc() + cursor.inc() and it gives you 2, not 1

cursor.set(1) + cursor.get() returns 1 (even if this is done synchronously) and does not wait for the transaction to complete.

I guess this can be achieved by the commit method anyway, but you may want to read your writes without triggering a rendering.

**Comment by Yomguithereal** [comment]
For those kind of cases you have the `cursor.chain` method that will apply successive functions by composition. [Docs](https://github.com/Yomguithereal/baobab#chaining-mutations).

**Comment by slorber** [comment]
thanks that seems nice

**Comment by Yomguithereal** [comment]
No problem @slorber, don't hesitate to tell me if there are any cases that `chain` wouldn't cut.

**Comment by Yomguithereal** [comment]
Also, I you don't want the tree to commit transactions on its own, you can set its `autoCommit` setting to `false` if ever needed.
