### ISSUE TITLE
Invisible characters causing "Uncaught SyntaxError: Unexpected token null"

### ISSUE THREAD

**Issue by jbroadway** [Yomguithereal/baobab#113]
I'm using browserify to compile my scripts and I run into the error `Uncaught SyntaxError: Unexpected token null` on a few lines in Baobab due to invisible non-ascii characters that once compiled appear like this:

    this.validate = this.options.validate ||Â null;

Searching and replacing them with nothing fixes it (using BBEdit's "Zap Gremlins" feature, also available in the free TextWrangler), but after an `npm update` they're back.

**Comment by Yomguithereal** [comment]
Thanks for the information @jbroadway. I have a nasty tendency to type weirdly on my keyboard and inserting those nasty gremlins in the code against my will.

**Comment by marbemac** [comment]
@Yomguithereal Also just ran into this. With the exposure from hacker news, and the new people checking out the project, would it make sense to cut a quick new npm release? This completely (and fairly invisibly) breaks baobab, and might leave a bad first impression on all these new developers.

**Comment by Yomguithereal** [comment]
Thanks @marbemac, just released a `0.4.0` version.

**Comment by marbemac** [comment]
@Yomguithereal I think this is an issue has resurfaced on the master branch? I'm getting unexpected token errors again.

**Comment by Yomguithereal** [comment]
Thanks again @marbemac, I added a safeguard to be sure those cursed characters won't happen again.
