### ISSUE TITLE
1 second delay

### ISSUE THREAD

**Issue by tomasbonco** [Yomguithereal/baobab#114]
Hello,

I'm trying to use Baobab without React as an internal DB. I'm saving data using ```.set()``` and reading them using ```.get()``` . It takes 1 sec to update my data (so it takes one second for .get() return data I set). Why is that?

**Comment by christianalfoni** [comment]
Hi @tomasbonco,

It does not really take a second, it waits for the next tick. This lets you run multiple mutations to the state tree synchronously, but only trigger one single 'update' event for each change. 

If you want a more predictable update of the tree you have two choices.

```js
var tree = new Baobab({
  foo: 'bar'
}, {
  autoCommit: false
});

 // You have to run tree.commit() whenever you want the update to actually
// go through. This gives best performance and control
tree.set('foo', 'something else');
tree.commit();
```

```js
var tree = new Baobab({
  foo: 'bar'
}, {
  asyncrhonous: false
});

// Each mutation to the tree will run a 'commit', potentially slower
// if you want to do lots of mutations before actually committing them
tree.set('foo', 'something else');
```

Hope this answered your question :-)

**Comment by tomasbonco** [comment]
Hello, thanks for answer.

I'm using it with animations so value updates at least 60 per second (next tick?). I also have connected Baobab to Angular so my HTML is updating. It takes almost exactly 1 second (+/- 10ms). Setting ```asynchronous``` to ```false```, is not helping.

During my testing I also found out that events are send immediately.

**Comment by christianalfoni** [comment]
Hi again,

This does not seem to be related to Baobab. Do you have some code, or maybe a fidlde, that shows the problem? If you use `tree.commit()` or `asynchronous: false` your update listener will synchronously trigger.

You can also see examples of this behavior on the WIKI: https://github.com/Yomguithereal/baobab/wiki/Options

**Comment by tomasbonco** [comment]
Because such fiddle is time consuming to create, I'll try to do it tommorow.

**Comment by christianalfoni** [comment]
Thats great. In the meantime I will try to answer this from a different angle :-)

When you say "It takes 1 sec to update my data", do you mean that you are attaching a huge data-structure to the tree? So the `set()` operation itself takes 1 second? Then the answer is that JavaScript is single threaded, meaning that nothing else can happen when Baobab is working on your data-structure. What you could to optimize this is updating the tree in batches.

So lets say you have 10.000 records you want to add to baobab. Do something like this:

```javascript
var tree = new Baobab({
  records: []
});

var recordsCursor = tree.select('records');

// Or batching insert function
var insertRecords = function (records) {

  // Cut next 1000 from records 
  var nextThousand = records.splice(0, 1000);

  // Add those thousand to the state tree using the apply
  // function
  recordsCursor.apply(function (records) {
    return records.concat(nextThousand);
  });

  // Commit the changes to the tree, preparing
  // for the next batch to be inserted
  tree.commit();

  // If no more records, return
  if (!records.length) {
    return;
  }

  // On the next tick (allowing angular and animation to do its thing)
  // insert a new batch where we have the rest of the records
  setTimeout(function () {
    insertRecords(records);
  }, 0);
};

// Pass the 10.000 records to the insert function
insertRecords(recordsCursor.get());

```

**Comment by tomasbonco** [comment]
:D Thanks for a try, but I'm updating just a simple integer. I couldn't reproduce my problem in smaller case, so I believe it's not a problem of Baobab, but my Baobab-to-Angular connection.

I'll reply tommorow, if I resolved my issue, but if the problem is not with Baobab, I'm sorry for wasting your time :(

**Comment by christianalfoni** [comment]
Hm hm, okay. One last try here, though it should have been solved with `asynchronous: false`.

Check out chaining on this page: https://github.com/Yomguithereal/baobab/wiki/Complex-updates

Anyways, good luck!

**Comment by tomasbonco** [comment]
Ok, all it needed was $scope.$apply() attached to Baobab's onupdate event. Anyway thank you for your time and of course Baobab.

**Comment by Yomguithereal** [comment]
Is it working sufficiently fast now after your $scope.$apply() fix?

**Comment by lucasmreis** [comment]
Hello, 

I'm also using Angular, and came across a similar issue. Maybe it has something to do with angular's dirty checking:

    // inside AppState factory:
    var appState = new Baobab({
      foos: [],
      bars: []
    });
    return appState;

    // inside controller:
    var localState = {};

    var foosCursor = AppState.select('foos');

    foosCursor.on('update', 
        function() { localState.foos = foosCursor.get(); });

    // inside view:
    <p ng-controller="someController as c">
      Foos:
      <ul>
        <li ng-repeat="foo in c.localState.foos">{{ foo }}</li>
      </ul>
    </p>

The view is only rendered after changing the Baobab object if I set `asynchronous: false`. If I want to use `asynchronous: true`, I have to call `$apply` after `localState.foos = foosCursor.get();`:

    // works with asynchronous: true
    foosCursor.on('update', 
        function() { localState.foos = foosCursor.get(); $scope.$apply(); });

What do you guys think is happening here?

Thank you one more time for the time devoted to this library,
Lucas Reis

**Comment by Yomguithereal** [comment]
I don't know angular very well but maybe an angular/baobab bridge should handle the tree transactions itself rather than let the tree perform them as it is used to by default.

By setting the `autoCommit` option to false and using `tree.commit` when needed, maybe the bridge could have more control about what is effectively taking place under angular's scopes hood?

**Comment by christianalfoni** [comment]
hi guys,

The reason this happens is indeed because of Angular digest loop. Angular will trigger this digest loop itself with use of certain directives or services. For example if you use `ng-click` a digest loop is run after the click method is executed. Also use `$http` or `$timeout` has the same effect.

The thing is that the digest loop runs synchronously after these "callbacks" has been executed. This means that when you bring Baobab into the picture and its asynchronous behavior you have to manually trigger digest loops.

There is not "best practice" of Baobab and Angular yet, as this needs to be explored. But one way of doing it is:

```javascript
angular.module('app', [])
  .factory('tree', function ($rootScope) {
    var tree = new Baobab({
      todos: []
    });
    tree.on('update', function () {
      $rootScope.$apply();
    });
    return tree; 
  })
```

So whenever the tree has any update it will trigger the digest loop.

**Comment by tomasbonco** [comment]
@Yomguithereal Yes, after $scope.$apply() it works sufficiently fast.

**Comment by christianalfoni** [comment]
Okay, created https://github.com/christianalfoni/baobab-angular now. Please let me know if this can work and if you have any ideas to make it better :-)

**Comment by lucasmreis** [comment]
Christian, amazing work and amazing speed, hehe! :runner: 

I'll take a look and build an example app with it. Thank you one more time!

**Comment by christianalfoni** [comment]
Hehe, I had most of the code in flux-angular, just had to change a dependency and remove some code ;-) 

Thanks for taking the time to try it out! Are no tests at the moment and I did very shallow testing, so probably is a bug or two there. Let me know!

**Comment by Yomguithereal** [comment]
Switching this issue to #121.
