### ISSUE TITLE
Suggestion: specify cursors at instance creation instead of component definition

### ISSUE THREAD

**Issue by qfz** [Yomguithereal/baobab#116]
I just discovered baobab, thank you for this great library!

I have a suggestion about where the cursors are specified for react components.

Right now, baobab requires the cursors to be specified when we define a react component with createClass(). I found this approach limiting, it's the only reason stopping me from using baobab.

If I had a component and I want to create many instances of, each of them is bound to different parts of the tree, just so that I can reuse them across the application. Currently I don't see any way to do that with baobab.

Would it be better to pass cursors in via props for each instance, like this:
```javascript
<MyComponent cursors={{colors: ['colors']}} />
```

rather than defining a static cursors object in createClass()?

**Comment by christianalfoni** [comment]
It is also possible to allow for the cursors prop to be a function:

```javascript
var Comp = React.createClass({
  mixins: [tree.mixin],
  cursors: function () {
    return {
      data: [this.props.cursor]
    };
  }
  ...
});
```

We created our own mixin on a project doing this. Works very well. It also feels much like the "getInitialState" method, so I would think that would be the way to go. What do you think?

**Comment by qfz** [comment]
That's cool, I didn't know a function would work. Thought about it for a second, but didn't try.

By the way, love your blog post on baobab. I didn't know PureRenderMixin exists, so wrote my own version of it. Found out about it through your post, overjoyed.

**Comment by christianalfoni** [comment]
Glad it helped :-)

**Comment by qfz** [comment]
Hey Christian, can you please elaborate a bit more on how you use a function to return cursor? I tried it but got an error baobab.mixin.cursor: invalid data (object or array). Strange thing is it refers to cursor, not cursors. I didn't define 'cursor' at all.

**Comment by christianalfoni** [comment]
Ah, sorry, it was meant as a feature suggestion :-)

The way we did it on our project was to build a mixin from scratch, not using the tree.mixin or cursor.mixin included with Baobab.

**Comment by qfz** [comment]
Oh, sorry I just deleted my previous question too fast. 

It will be a really good feature to have, looking forward to it.

**Comment by mkuklis** [comment]
I ran into a similar issue and I agree with @qfz it would be great to add a more dynamic support. Right now I do something similar to this:

````js
var Baobab = require('baobab');
var state = new Baobab({ /* my state */});
var getInitialState = state.mixin.mixins[0].getInitialState;
````
and then inside the react component:

````js
var Component = React.createClass({
  mixins: [ state.mixin ],
  getInitialState: function () {
    // ...
    this.cursor =  // Define your dynamic cursor
    return getInitialState.call(this);
  },
  ...
````

This is a workaround. I think it should be easy to refactor Baobab mixin and perhaps extract what currently happens in `getInitialState` to a util function so it can be executed later.

**Comment by Yomguithereal** [comment]
Merging this into #110.
