### ISSUE TITLE
Consider using immutable-store for immutable functionality

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#118]
Hi there,

I built this [immutable-store](https://github.com/christianalfoni/immutable-store). Maybe it could be used for immutability in Baobab? I am not too familiar with how Baobab works with its tree object "in the background", but ass immutable-store pretty much has the same API as native objects/arrays, it might be a good match?

Anyways, just a thought :-)

**Comment by Yomguithereal** [comment]
I don't think it should be necessary to rely on an external immutable store. If any immutable like option is needed freezing things internally should do the trick.

**Comment by christianalfoni** [comment]
Yeah, hm, it depends on how it is implemented though? Will it be like this?

```js
var tree = new Baobab({
  foo: {}
});
// Both tree and foo is now frozen

tree.select('foo').get(); // I get the already frozen object

// Baobab creates new foo object, attaches 'something' property with 'cool' value and freeze new foo.
// Then new tree object is created where the new frozen foo is attached and then tree is frozen
tree.select('foo').set('something', 'cool');

```

Or will you freeze when using `get()` ? If so it is not enough to just freeze the returned object, as freezing only affects the object itself, not the objects/arrays that are nested. So you would still have to traverse and pretty much to what cloning does, loosing some benefits. This is also a consideration in the first strategy.

So yeah, sorry if you already got this figured out, just wanted to share some thoughts :-)

**Comment by andrewluetgers** [comment]
I have been trying to compare Baobab and Omniscient, one of the differences seems to be immutability. I have read in other places that a user should only be using the tree api for changes so why not codify that with immutable objects? Also a big win of immutable objects is supposed to be the easy equality check. I know there are optimizations in Baobab but it is unclear what the differences are between the two. I would love to see detailed discussion of these issues esp. in regards to how Baobab performs its update checks vs how it would work with an immutable store. THANKS!

**Comment by andrewluetgers** [comment]
In regards to freezing being a solution this video has bee the best explanation I have seen of why other approaches (than immutable objects) just don't get you there. https://www.youtube.com/watch?v=I7IdS-PbEgI At about 18 mins in he covers object.observe, and in it there are limitations to the api where you would have to continually traverse and add observers to new objects to make it work. A bit of a mess. That is the same problem with freezing. And of course are we then copying the frozen object to make a new state? What is the cost of that vs structural sharing?

**Comment by christianalfoni** [comment]
Just a comment on immutable.js. Though it is very fast at setting data, we have to remember that we should avoid exposing the immutable-js specific objects. The API is really verbose compared to just using vanilla javascript. As I understand it using immutable.js would require the `.toJS()` method on every Baobab `.get()`, but that is insanely slow.

http://jsperf.com/immutablejs-v-immutable-store-getters

Slow writes is not really an issue I think, as you rarely do that compared getting data, at least with a FLUX type of architecture.

**Comment by Yomguithereal** [comment]
I guess we can close this now, since there is an immutable option.
