### ISSUE TITLE
Angular Best Practices

### ISSUE THREAD

**Issue by lucasmreis** [Yomguithereal/baobab#121]
I experimented with an angular architecture in [this blog post](http://lucasmreis.github.io/blog/a-more-functional-approach-to-angular-with-baobab/). Next step is trying [baobab-angular](https://github.com/christianalfoni/baobab-angular) on it.

This architecture is based on the [previous post](http://lucasmreis.github.io/blog/a-more-functional-approach-to-angular/) and on @christianalfoni [comment on this thread](https://github.com/Yomguithereal/baobab/issues/114#issuecomment-77765732).

Do you think this is a nice approach to using Baobab in an Angular 1.x app? I could help on the wiki if this is the case.

**Comment by christianalfoni** [comment]
The WIKI is open to all, would suggest you create an "baobab and angular" in the same format as the current pages, then we can comment on that? :-)

- Edit sidebar, add new header and links to your pages (Just name them somthing)
- Click the link and the wiki will automatically bring you into the editor for that new page

**Comment by lucasmreis** [comment]
Done. Christian, as soon as we decide on the format of `baobab-angular` I reference it on the wiki. Let the commenting begin! :smiley:

**Comment by Yomguithereal** [comment]
Thanks @lucasmreis, I will check that when I find time to read the wiki.

**Comment by lucasmreis** [comment]
:+1:

**Comment by Yomguithereal** [comment]
Any news on angular integration lately?

**Comment by christianalfoni** [comment]
I think we concluded that baobab-angular did not really help that much as you can quite easily just hook the Baobab tree up to the $rootScope in angular. Correct me if I remember incorrectly here @lucasmreis :-)

**Comment by lucasmreis** [comment]
That's right, @christianalfoni! And, on top of that, Angular 2 is coming as a complete rewrite. Everything is going to change a lot very soon :)

**Comment by Yomguithereal** [comment]
Do you want me to let this issue open to serve as discussion thread or should I close it and you'll open another one when we need to deal with angular 2?

**Comment by lucasmreis** [comment]
I would close it and wait for Angular 2 adoption rate to start growing. We don't even know how influent it will be :) What do you think, @christianalfoni ?

**Comment by christianalfoni** [comment]
Yup, agree!
