### ISSUE TITLE
Type checked getters and setters

### ISSUE THREAD

**Issue by DouglasLivingstone** [Yomguithereal/baobab#125]
Following on from [this post](https://news.ycombinator.com/item?id=9184912), I'm looking for a way to use cursors with TypeScript type checking. I'm not sure it fits within the scope of this project, but this is what I have in mind.

Here's a class with two properties of different types:

    interface Foo {
        name: string;
        count: number;
    }
    
    var foo: Foo;
    foo.name.length; // OK
    foo.count.length; // Compile error

Accessing the .length property on a number is invalid, so the idea is to get an early error message at compile time, rather than only at runtime, by providing type hints.

One way of making cursors work with TypeScript is using type inference with functions to read properties instead of string keys, but doing it like this means properties are read-only. A simple workaround is to pass a writer as well as a reader in, but I'm interested in ways to avoid that without horrible hacks (for example by generating the code for the setter from the getter, and using the getter only for type information).

    interface Cursor<T> {
        property<U>(getter: { (object: T): U }): Cursor<U>;
        value(): T;
    }
    
    var cursor: Cursor<Foo>;
    cursor.property(f => f.name).value().length; // OK
    cursor.property(f => f.count).value().length; // Compile error

**Comment by Yomguithereal** [comment]
Hello @DouglasLivingstone, thanks for the follow up. Let me document myself more about how TypeScript type checking works so I can see whether something might be improved for the library without too much pain.

**Comment by Yomguithereal** [comment]
On a slightly related matter, may I ask you if you know cursors library working with a type checking solution?

**Comment by DouglasLivingstone** [comment]
No, I've not seen a dedicated library for it. Informally in my own code I have structures which look like this:

    var field = form.field(model => model.value, (model, newValue) => model.value = newValue, ...);

which is used a bit like a cursor, but no, not really.

**Comment by Yomguithereal** [comment]
Hello @DouglasLivingstone. I am afraid I haven't found a fresh solution to your problem here. Any luck on your side?

**Comment by DouglasLivingstone** [comment]
No, I've not come up with anything elegant yet. If [either](https://github.com/Microsoft/TypeScript/issues/394) of [these](https://github.com/Microsoft/TypeScript/issues/1003) tickets produce new options I'll take a look at it again.
