### ISSUE TITLE
Sending cursors to React child elements

### ISSUE THREAD

**Issue by localhosted** [Yomguithereal/baobab#131]
Considering this tree:

    var tree = new Baobab({
        words: [
            [
                {
                    char: "h",
                    type: "c"
                },
                {
                    char: "e",
                    type: "t"
                },
                {
                    char: "l",
                    type: "g"
                }
            ],
            [
                {
                    char: "l",
                    type: "h"
                },
                {
                    char: "o",
                    type: "l"
                },
                {
                    char: "!",
                    type: "ç"
                }
            ]
        ]
    });

And the React elements:

    var Word = React.createClass({
        render: function() {
            return (
                <span  className="w">
            {this.props.chars.map(function(result) {
                return <span> {result[0].char}{result[1].char}{result[2].char} </span> ;
            })}
                </span>
            );
        }
    });
    
    
    var JText = React.createClass({
        mixins: [tree.mixin],
        cursors: {
            words: ['words']
        },
        render: function() {
            var words_ = this.state.cursors.words;
            return (
                <div  className="text">
                    <p>
                        {words_.map(function(result) {
                            return <Word key={Math.random()} chars={result}/>;
                        })}
                    </p>
                </div>
            );
        }
    });

That would be sufficient if I hadn't any need to track the state of each object in the list, how is the best way to have child elements receive cursors to the lements of the list?

**Comment by Yomguithereal** [comment]
Good evening @localhosted,
I am not sure to completely understand your use case here. Could explain why you need the Word components to be bound to a cursor (isn't the JText bound to your list enough? are you setting a random key on your Word component on purpose?) Anyway, we are discussing [here](https://github.com/Yomguithereal/baobab/issues/110#issuecomment-77749582) a way to set a cursor on a component based on its props and this should be quite similar to what you are trying to achieve.

**Comment by localhosted** [comment]
I read this [article](https://dialelo.github.io/application-architecture-with-react-rethinking-flux.html), so I was trying to go with this channel, top-down data idea. Instead of using his sample atom lib, I chose to see if Baobab would work. The idea that each word needs a cursor is so that I change the UI state trough the application data, instead of with an individual elements state.

I ended up just going `right()` until `null`:

    var JText = React.createClass({
        mixins: [tree.mixin],
        cursors: {
            words: ['words'],
            title: ['information', 'title']
        },
        render: function() {        
            var word = this.cursors.words.down();
            var words = [];
            while (word != null) {            
                words.push(<Word key={Math.random()} cursor={word}/>);
                word = word.right();
            }
            return (
                <div  className="text">
                    <p>
                        {words}
                    </p>
                </div>
            );
        }
    });

The random key was just because React was complaining that I had no key in my elements.

**Comment by Yomguithereal** [comment]
Ok, I see what you mean. However I wonder if the word level is not a step too low. In your example, if any word updates, both the JText component and the word component affected (only one) will render anyway, so I am not sure whether a cursor at word level can really help you if you keep also a cursor on JText.

This would mean you need a cursor at word-level for high perf reasons and, in this case, I would drop the words cursor on the JText component and use a cursor from the tree to give some word subcursors to the word components.

Something like:

```jsx
var tree = new Baobab(...),
      wordsCursor = tree.select('words');

var JText = React.createClass({
    mixins: [tree.mixin],
    cursors: {

        // Only bind the rendering of this component to some information
        title: ['information', 'title']
    },
    render: function() {        
        var words = [];

        wordsCursor.get().forEach(function(_, i) {

            // Words will receive their cursors and won't require an update of their parent
            // to update themselves
            words.push(<Word key={Math.random()} cursor={wordsCursor.select(i)}/>);
        });

        return (
            <div  className="text">
                <p>
                    {words}
                </p>
            </div>
        );
    }
});
```

I really think our version of the mixin enabling to bind a cursor on a component based on props will help you achieve this more naturally.

But in this case, except for performance reasons (I assume you have a use case far more complicated than your example list of two word, of course), it seems a bit overkill not to let the list of words handle the cursor's state.

**Comment by localhosted** [comment]
Ok, stuff is working. The only awkward part is making React update the components children. As I understand it, the `cursors` property tell the mixin what cursor to listen to and react to updates. But since my data isn't an object with named properties, each child element has to listen to the whole `words` cursor, instead of a cursor pointing to its list. 

In my case my elements have a depth of 3, being the **text** > **words** > **letters**, so whenever a click event fires for one letter, all letters would update.

I guess I have to wait for the outcome of the [issue](https://github.com/Yomguithereal/baobab/issues/110#issuecomment-77749582) you mentioned earlier, because that idea seems to work well with my use case.
