### ISSUE TITLE
How to jest-test react components with baobab mixin?

### ISSUE THREAD

**Issue by mordaha** [Yomguithereal/baobab#132]
It has Null .state when TestUtils.renderIntoDocument

 - TypeError: Cannot read property 'cursors' of null

**Comment by Yomguithereal** [comment]
Good evening @mordaha. I am not very acquainted to Jest. I currently test my mixins [likewise](https://github.com/Yomguithereal/baobab/blob/master/test/suites/mixins.js) and haven't any problems with cursors.

Can you give me a link to your code or write some here so I can test it on my side and see whether I missed something impairing the Jest testing utilities?

**Comment by mordaha** [comment]
Jest automatically mocks any 'require' (or import).

And when you try to make rendered version of component (to test it DOM after):
let myComponent = TestUtils.renderIntoDocument(  <MyComponent /> );

Baobab at that moment is a mock, which does not have .mixin part :)
So, this jest-rendered component will never have .state.cursors part. 
And if component's render() uses .state.cursors.... it fails.

To test with Jest just enough to say jest don't mock the baobab import:
jest.dontMock('baobab');

I forgot to do it, sory :)

**Comment by Yomguithereal** [comment]
Closing this then :)

**Comment by christianalfoni** [comment]
Moving it to the wiki :-)

**Comment by yashikagarg13** [comment]
@mordaha I am trying to write unit test using jest for my React application, that uses Baobab for Application state. And when I `jest.unmock("boabab-react")` I get error `TypeError: Cannot read property 'createFacet' of undefined`. Do you have any idea around this?
