### ISSUE TITLE
Remove dependency for Baobab instance in mixin

### ISSUE THREAD

**Issue by GeReV** [Yomguithereal/baobab#134]
I think it would make it simpler, or at least more flexible, to have a generic React mixin which isn't dependent on the actual tree instance.
This could work nicely with passing cursors down to child elements (ties into #131 ?).

For example, having a `Baobab.Mixin` object, which adds something along the lines of:
```javascript
propTypes: {
  cursor: React.PropTypes.instanceOf(Cursor).isRequired
}
```
It could also work for a `tree` prop:
```javascript
React.createClass({
  mixins: [Baobab.Mixin],
  cursors: { ... } // Assumes this.props.tree exists
  ...
});
```

This way, the React component and the module it's defined in don't need to have a reference to the tree instance.
I would love to just have a tree defined in a single point and just pass cursors from it down to each relevant element.

**Comment by Yomguithereal** [comment]
Hello @GeReV, even if I understand the clear advantages that would mean a mixin not dependent of a particular tree, I wonder whether it would be that comfortable to pass down a tree to each components needing cursors from top to bottom. I feel this would remove one advantage of using cursors which is to bind components to your app's state at any level as you see fit.

However I can see why you'd like to be able to pass the tree from upper components in some cases so your bottom components files does not rely on the tree dependency.

Let me think about it a little more and gather advice from other people.

**Comment by nickdima** [comment]
@GeReV I suggested the same thing here: https://github.com/Yomguithereal/baobab/issues/110#issuecomment-79279111
Another uses case that I have is that server side I'm creating a new tree for every request and attaching it to React's context so I only have it available inside a React component. 
What I did for now is I created a reusable component that creates a react component at runtime which has the baobab mixin. A bit of a hack but it works for now.

**Comment by Yomguithereal** [comment]
So, @christianalfoni, @nickdima, @GeReV,
here is how I understand the mixin problem and its relations with isomorphic applications:

With the current mixin, we must bind components to a precise instance of boabab. We can model it as an impure function:

```js
var tree = new Baobab();

function render(application) {
  // Will do something with the tree reference.
  // Which is defined outside the function.
}

render(app);
```

With a generic mixin, we would have a pure function:

```js
var tree = new Baobab();

function render(tree, application) {
	//...
}

render(tree, app);
```

The second solution seems conceptually better, but there is one issue: how can a component (presumably the root one) transfer tree and/or cursors to every children and this all along the component hierarchy from top to bottom?

The problem with props is that one would have to do it explictly at each level of components which can prove tiresome and which is currently said to be one of react's quirks when dealing with props propagation.

Another solution would be to use a mixin doing so with a context, but, as far as I know (@christianalfoni, correct me if this is wrong), one would have to bind the mixin to every one of this components and this might also prove tiresome.

So I am wondering if there is a solution I did not find or I did not understand from the three of you.

What do you think?

**Comment by GeReV** [comment]
I tend to think both approaches are valid, for the sake of flexibility.
There might be better ways, but I don't know about them.

Passing cursors or trees down the entire React component tree doesn't seem like such a bad idea. 
For example, passing down a cursor which is a subset of the tree, and a subset of that to the next level and so on.

I also like the idea of the components being completely blind to the tree.

Additionally, in my use case, I would like to create the tree together with the rest of the app, since I update it from the server, and so having a "static" tree unrelated to the app seems a bit strange.

**Comment by christianalfoni** [comment]
Hi guys,

We could solve this by using a context and attaching a mixin type of function to the cursor/tree itself. Something like:

```js
var tree = new Baobab();

function render(tree, application) {
    return React.renderToString(application({tree: tree});
}

var html = render(tree, app);
```
And some child component:

```js
module.exports = React.createClass({
  contextType: {
    tree: React.PropTypes.object
  },
  componentWillMount: function () {
    this.context.tree.injectState(this, {
      projects: ['projects']
    });
  },
  render: function () {

  }
});
```
This method would do the same as the mixin basically. It is a bit more intrusive to the component as you would have to wrap existing `componentWillUnmount` etc., but again this would also work with the ES6 class syntax, which is a very good thing.

How do you guys feel about it? :-)

**Comment by Yomguithereal** [comment]
What I am currently pondering and which bothers me is that all those ways necessitate to require React as a dependency (or at least as a peer dependency) to be able to use the PropTypes.

So, here is my question: is this possible to define the types without a direct reference to React?

If not, I am considering the possibility of extracting the mixin from the core library in something like `baobab-react` so that the library can remain agnostic.

**Comment by GeReV** [comment]
@Yomguithereal, I guess it's possible, but the code's [pretty nasty](https://github.com/facebook/react/blob/cff3f35bf7c2c469b8726009070609c69a532c24/src/classic/types/ReactPropTypes.js).

The `baobab-react` idea is actually pretty good!

**Comment by christianalfoni** [comment]
@Yomguithereal @GeReV Might also consider:

```js
var Baobab = require('baobab/react');
```
But the example above does not require Baobab to know anything about the contextType.

injectState just gets an object (this, the component) and attaches the data from the cursors to a state object that is hooked onto the component . It does need to know about `setState` though, which is React specific.

**Comment by Yomguithereal** [comment]
@christianalfoni, this feels a bit verbose compared to the mixin's simplicity. Plus the user would have to attach the tree to the component's context by himself.

I will experiment soon with this solution plus a new mixin detached of any instance reference and an es6 composition class to see where this should be headed.

**Comment by christianalfoni** [comment]
@Yomguithereal Yeah, I agree, it is quite verbose :-) There is a concept that has become quite popular and that is using wrapper components. In React 0.14 there will be a concept of "parent context". So instead of creating a mixin, you would create a parent component, passing cursor values as props. 

With Babel supporting properties I think you could easily use the same concepts both with classes and traditional `createClass`.  

```js
class Projects extends React.Component {
  render: function () {
    return (
      <Baobab.Wrapper cursors={{projects: ['projects']}}>
        <Projects/>
      </Baobab.Wrapper>
    );
  }
}
// And the state is available on this.context.projects inside "Projects"

var Projects = React.createClass({
  render: function () {
    return (
      <Baobab.Wrapper cursors={{projects: ['projects']}}>
        <Projects/>
      </Baobab.Wrapper>
    );
  }
});

// Same thing
```

This arrives in React 0.14, so might be a good idea to wait for that to arrive. My "Formsy-React" project will also require the use of that functionality. Going to write a test on it this week, can give you some more specific feedback on it. But yeah, I think it is worth investigating :-)

**Comment by Yomguithereal** [comment]
Linked to #157.

**Comment by nickdima** [comment]
@christianalfoni wouldn't be cleaner for the wrapper to set the data as props on its children instead of them getting the data from context?

**Comment by christianalfoni** [comment]
Hi @nickdima,

Agreed, though then you would need a mixin or manually wire up the cursors. These wrapper components also often cover a quite big component tree, by using context you do not have to keep passing down by prop. Any child can just grab whatever state they need from the context. That is nice :-)

**Comment by Yomguithereal** [comment]
Hello guys. [baobab-react](https://github.com/Yomguithereal/baobab-react) now passes the tree through context so it can flow in your entire app. The mixins, hoc, decorators, whatever etc. are not bound anymore to a precise instance.
