### ISSUE TITLE
Synchronous updates sticking around causing infinite loop

### ISSUE THREAD

**Issue by jmisterka** [Yomguithereal/baobab#141]
Baobab is in synchronous mode with autoCommit=true and I'm using a change in the model to inform a change to the view.

Using the example below when I update model.pickup, internally baobab commits the change and updates any listeners, but this happens before it clears this._futureUpdate.

The update event triggers the action to change the view. Baobab again commits the change but this time this._futureUpdate isn't empty and is merged in causing it to update view and model.pickup together. 

So, model.pickup is updated twice and continues to be because the listener keeps getting hit with the update event causing an infinite loop.

```javascript
exampleTree = new Baobab({
  model: {
    pickup: 'paris'
 },
  view: 'pickup'
})

exampleTree.select(['model', 'pickup']).on('update', (updateObj) => {
  actions.setView('dropoff'); // imagine this uses an actions file that set's view to 'dropoff' on tree
});
```
It seems to me that for synchronous operation this._futureUpdate should be cleared before the update event is sent so previous synchronously committed changes aren't committed twice.

**Comment by Yomguithereal** [comment]
Hello @jmisterka, checking this asap.

**Comment by Yomguithereal** [comment]
I am not sure you were using the latest version since I changed the `_futureUpdate` name since but you are right anyway. I was firing the event before clearing the transaction's stack. I've released a commit that should handle your issue. Can you tell me whether this work?

**Comment by jmisterka** [comment]
@Yomguithereal, thanks for the quick turnaround, this works now.
Seems like this fixes the weirdness in the asynchronous case as well.
