### ISSUE TITLE
Working with baobab and web workers

### ISSUE THREAD

**Issue by pinyin** [Yomguithereal/baobab#142]
The current document doesn't mention about using baobab in a multi-threaded environment, does that mean I am not supposed to call baobab from another web worker directly?

Baobab's API seems to be very parallel-friendly, so I'm considering wrapping baobab in a dedicated web worker and proxy the web workers API (postMessage/addEventListener pairs) to baobab's APIs.

I don't know if that's necessary. Thanks for any recommendation.

**Comment by Yomguithereal** [comment]
I don't see reasons why Baobab should not work in a web worker context. Wrapping the API to web workers' one should work. However, I do not clearly understand what you are trying to achieve here. Do you need a centralized tree in the main thread and have workers at cursor level? Are you trying to handle a tree from a worker? Are you trying to split a tree?

**Comment by pinyin** [comment]
In my case, I'm just putting a baobab tree in main thread, attaching listeners to other web workers and applying event-sourcing pattern to change the baobab.
I created this issue because the ideas of immutable data and multi-threading are kinda close, so I was wondering if there's a supposed/better way to use Baobab with web workers, like the wonderful integration it already has with React.js.
Thanks for your reply and the excellent work. My issue is solved.

**Comment by Yomguithereal** [comment]
It should definitely work in this case as long as you don't pass something else than raw data from the main thread to the worker. Don't hesitate to link any code you would write concerning this issue here as I think other people may be interested by your particular use case.

**Comment by pinyin** [comment]
The solution is still quite immature and is in a young personal project, in case anyone searched here I'm posting it anyway.

https://github.com/pinyin/sourcelayers

Codes related to baobab and web workers are under directory `/webapp/framework`.

**Comment by Yomguithereal** [comment]
Thanks for sharing @pinyin. This looks like an interesting use case. What's the purpose of the app?

**Comment by pinyin** [comment]
@Yomguithereal Glad you are interested. Hopefully this project would be a modern clone of [OpenGrok](http://opengrok.github.io/OpenGrok/), a web app for browsing source codes. The original solution lacks some functions I need (e.g. taking notes / browsing history ..) and is written in JSP, so I decided to write my own version.
I'm still learning webdev, any advices are welcomed.
