### ISSUE TITLE
chain only works when called multiple times

### ISSUE THREAD

**Issue by jonypawks** [Yomguithereal/baobab#143]
I believe I've traced an issue that I've been having with `$chain` and it appears that the chained calls are only applied when there is multiple queued up in a single update.

I've got a fiddle that reproduces the issue here: http://jsfiddle.net/jonypawks/t3g75er3/1/

You'll notice that "2 dogs" is rendered when we expect "3 dogs" and if you uncomment the second chain call, it outputs "4 dogs" as expected, as well as firing the listener to the update event.

**Comment by Yomguithereal** [comment]
Thanks @jonypawks! This definitely looks like a bug. Let me check this.

**Comment by jonypawks** [comment]
Thanks for the quick response to this report!
