### ISSUE TITLE
Filtering is crippled

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#144]
We have such example:

```javascript
// Retrieving or selecting data by passing a function in the path
var complexCursor = tree.select('palette', 'colors', function(color) {
  return color === 'green';
});
```

It seems that should filter out **all** `colors == 'green'` but it really yields only **first** of them.
So this is `findFirst` not `filter`. 

---

Closed as I've got reasons behind this. The filtering should have access to multiple cursors in general case and it's only possible at component level.

**Comment by ivan-kleshnin** [comment]
No, this is really cripple.

```javascript
cursors: {
    model: ["robots", model => {
      return model.id == this.getParams().id;
    }],
  },
```

`this` is undefined so this blocks obvious use-case with React router.

**Comment by Yomguithereal** [comment]
Hello @ivan-kleshnin,
Concerning your first example, yes, we are not filtering but finding the first relevant item. Expanding to a filter behaviour could be interesting but is not easy to perform. Let me keep the idea somewhere and think about it.

Concerning your second example, this is a known problem that will be solved soon as per PR
#140 but likewise:

```js
== RobotDetailComponent ==
cursors: function() {
  return {
    model: ["robots", model => { return model.id == this.getParams().id;
  };
},
```

and that will be improved in `1.0.0` #139.

**Comment by ivan-kleshnin** [comment]
Ok, glad to hear you're concerned about all this. I will track the progress.

**Comment by christianalfoni** [comment]
@Yomguithereal Would this not be a case for facets really? The filtering I mean?

**Comment by Yomguithereal** [comment]
@christianalfoni, yes, it should. But I should stress the point in the documentation some way. I am currently pondering the idea of having cursors pointing at multiple values in the tree but I fear there would exist some underlying issues with it.

**Comment by christianalfoni** [comment]
@Yomguithereal Hm, maybe a good idea to try out facets first? It seems like a really strong and flexible concept. If it can solve most "special cases" it is great to just have one concept doing that, instead of multiple approaches. Unless we are talking major performance benefits etc :-)
