### ISSUE TITLE
Recommended way to implement forms

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#145]
When I did Reflux-based app I just used `this.state.model` as both initial data for forms
and write target at form changes. It was just a pointer to the same data for both component and store.
so it worked and was more convenient than piping every field through actions (omg).

With Baobab such trick is impossible(?), as data is "immutable". I wonder how people implement their forms and what are recommended approaches. 2-way data flow is very handy with forms so I'd like to have it in some kind.

**Comment by marbemac** [comment]
Great question - I'm just running into this now and will share what I find. Curious to hear other people's solutions. @christianalfoni? @Yomguithereal?

**Comment by ivan-kleshnin** [comment]
@marbemac, I see a few possible directions:

1) Reflect new / edited model state in Baobab. Update Baobab state right from the component. No actions involved in field editing.

> // This is not necessarily a good idea to let your components handle the state updates by
// themselves but you could do it if needed.
this.cursors.name.edit('John');

2) Use Baobab as default data for edited model only. Mirror new / edited model state in Form component. Update Baobab state on submit only. No actions involved in field editing.

@marbemac do see other ways to approach this?

@christianalfoni wrote a good article about forms, but there are no clues about Baobab and model state reflection (if I'm right: focus of article differs a bit).

**Comment by ivan-kleshnin** [comment]
There are two types of forms: with **immediate** save and with **save on submit**. First type of forms is popular in OS settings (immediate reaction, not required to scroll long list of options...) but is not really applicable for creation. When to save? Dunno... So CRUD should be either implemented with a mix of two (complex) or with second type only. That's why I propose to ignore the possibility of **immediate** forms for a while in this issue.

**Comment by Yomguithereal** [comment]
The other thing here is to be able to define whether your Baobab tree, i.e. your app's state, really needs to hold the state of your form, or at least to be in full sync when the inputs change. In most cases, you don't and state component is way simpler and can handle the form alone. In other, however, for whatever reasons, you'll need to store the form's state into the app's one. Only one tricky thing here with React: you'll have to commit the state changes synchronously if you don't want to observe nasty cursor hopping.

```js
this.tree.commit();
```

**Comment by ivan-kleshnin** [comment]
The most complex thing is how to ask external data from component. Every example in the Internet just shows data already preloaded, lol. There is no way to declare external data dependency in component. React has nothing to help your, hooks doesn't accept promises, etc. 

I'm getting very complex and error prone code when trying to emulate that.

**Comment by ivan-kleshnin** [comment]
I've just decided to accept reality, and simply preload **all** data from the start. 
Otherwise React is plainly unusable as all it's API is not composable with async stuff.
*"Practicality beats purity"*

**Comment by Yomguithereal** [comment]
@ivan-kleshnin, what about [cycleJS](https://github.com/staltz/cycle)?

**Comment by ivan-kleshnin** [comment]
@Yomguithereal unfortunately, I don't reach form question there. I continue to elaborate both React and Cycle. CycleJS is a long-distance goal for me as it will be compatible with Web Components and have a lot of other promises but the lack of matherial about RxJS slows everything alot. 

Of of the big problems with React (as I've already said a number of times) is it's hooks. 
Behavior of hooks is predefined and can't be customized. Hooks are limited and limiting. 
They are too class-oriented. In CycleJS you won't have any as you will operate on lower level.

React just merges rendering, control and state aspects in on Component. Seals it and expose hooks.
On the app level you operate with different primitives than on the component level. CycleJS resolves this by providing the same usable primitives (Model, View, Intent) on all levels. That's the main architectural benefit besides all that Rx stuff.

**Comment by ivan-kleshnin** [comment]
I've got working edit form prototype but with huge hacks. Please review and advice how to improve.

```javascript
// EditRobotComponent
export default React.createClass({
  mixins: [State.mixin],

  cursors() {
    return {
      robots: ["robots"], // required to track load status
      loadModel: ["robots", "models", this.getParams().id], // "reference" model (see reset)
    }
  },

  getInitialState() {
    return {
      model: undefined,
      loaded: false,
      loadError: undefined,
      loadModel: {
        name: undefined,
        assemblyDate: undefined,
        manufacturer: undefined,
      },
    }
  },

  componentWillMount() {
    // `componentWillUpdate` is not called at first render, and data is not "changed"
    // so we need to hack this manually. How to handle this case without hack???
    RobotActions.askData();
  },

  componentWillUpdate(nextProps, nextState) {
    if (!this.state.model && nextState.cursors.loadModel) {
      nextState.model = Object.assign({}, nextState.cursors.loadModel);
    }
  },

render() {
    let {models, loaded, loadError} = this.state.cursors.robots;
    let loadModel = this.state.cursors.loadModel
    let model = this.state.model;

    if (!loaded) {
      return <Loading/>;
    } else if (loadError) {
      return <NotFound/>;
    } else {
      return (
        <DocumentTitle title={"Edit " + model.name}>
          ... form ...
        </DocumentTitle>
      );
    }
}

// Actions
export function askData() {
  State.select("robots").set("timestamp", new Date()); // dirty hack to trigger data sharing
}
```

**Comment by ivan-kleshnin** [comment]
React mixins are completely broken. No wonder they deprecate it. 
Baobab mixins provides hook `getInitialState()` where there is already all data I need.
Second version of the same hook `getInitialState()` in component get called **after** but it does not receive data in arguments as it logically should. So the only way to solve such cases is to split components into data-source components and "working" components. Everyone seems to hate mixins now and for a reason. But the root of the problem lies in React inability to provide decent compositional block. Components are extremely complicated. They complect state, rendering, actions, external data input and external data output. They illustrate perfectly God-object anti-pattern. Every component is a little God-object.

**Comment by marbemac** [comment]
Using my query mixin, this became fairly trivial.

https://gist.github.com/marbemac/a18582da8d2912285950#file-mixins-js

```js
var Post = React.createClass({
  mixins: [ StateMixins.query ],

  queries: {
    post: {
      cursors: {
        entries: ['models', 'posts'],
      },
      local: function(_this, data) {
        // using react-router
        var id = _this.context.router.getCurrentParams().postId;
        // if we're editing a post, fetch it
        if (id) {
          return StateQuery.findOne(data.posts.get(), {id: id});
        } else { // not editing a post? return a new one right away
          return new PostModel();
        }
      },
      remote: function(_this, data) {
        return StateActions.findOne(
          StateActions.models.POST, 
          _this.context.router.getCurrentParams().postId,
          false
        );
      }
    }
  }
})
```

In the local function, if there is a postId in the url, we look for the post locally (if not found, it will call the remote function and fetch it via the api). If no postId, then we just immediately return a new Post. Then, in render and all the functions that are called on form input updates, I use/edit this.state.post.result directly.

**Comment by ivan-kleshnin** [comment]
@marbemac I don't really like to keep everything in component, especially external data dependencies. It's a pain to test.

**Comment by ivan-kleshnin** [comment]
@marbemac I don't really like to keep everything in component, especially external data dependencies. It's a pain to test.

**Comment by marbemac** [comment]
@ivan-kleshnin Why is it too much for one component? I understand the concept of the god-object, and don't believe this concept applies to components built in the way described above.

From the wikipedia god-object definition:
```
"Most of such a program's overall functionality is coded into a single "all-knowing" object, which maintains most of the information about the entire program..."
```

The react component described in my post knows nothing about the rest of the program. It knows enough to render itself, and that's it. It is not a god-object.

I actually modeled this after Relay. In relay, each component contains a definition defining the data needs for that component. This is useful, because now a component is self sufficient, and depends only on itself. You can drop it in anywhere and it will just work. It knows nothing about the rest of the system, or other components - it just knows how to render itself.

I'm curious about how you are fetching/managing data for your components? I'm totally open to other solutions! For me, so far, the solution above has been working quite well.

**Comment by lucasmreis** [comment]
I'm updating Baobab tree on `onBlur` event:

    import State from '../state';

    var EmailForm = React.createClass({
      mixins: [State.mixin],

      cursors: {
        email: ['email']
      },

      updateEmail: function(v) { 
        State.set('email', v);
      },

      render: function() {
        return <input 
          defaultValue={ this.cursors.email.get() }
          onBlur={ this.updateEmail } />
      }
    });

I would put it on `onChange` too, but the cursor get kind of crazy. Anyone has a better solution to it?

Back to the code, instead of calling `State.set` inside the React class, I would put it in another module, then it could transform or validate before updating or not the tree.

That way we would have what could be called an `ASV` architecture: Actions > State > View. Does it make sense?

**Comment by Yomguithereal** [comment]
@lucasmreis, you probably have cursor issues because baoab's updates are asynchronous and because react cannot handle controlled input with asynchronous state updates. You should try `tree.commit` to apply tree state changes synchronously in this case.
