### ISSUE TITLE
Can't get root with .root()

### ISSUE THREAD

**Issue by pindamonhangaba** [Yomguithereal/baobab#146]
The following outputs `undefined undefined false` when expected is `object array true`:

    var tree = new Baobab({first: ['1', '2', '3']}),
         cursor = tree.select('first');
    
    console.log(cursor.root().get(), cursor.root().select('first').get(), cursor.root().isRoot());

**Comment by Yomguithereal** [comment]
You are right indeed @pindamonhangaba. Fixing this right now.
