### ISSUE TITLE
.select / .get return all matches, not only the first

### ISSUE THREAD

**Issue by jfsiii** [Yomguithereal/baobab#148]
I'm not sure if this is a feature request or a misunderstanding of the current features, but I'd like a way to get multiple values which match a path. Is this behavior supported?

For example, given a tree of:
```javascript
var tree = new Baobab({data: [ 
  {id: 1, foo: 'bar'}, 
  {id: 2, foo: 'bar'}, 
  {id: 3, foo: 'baz'}, 
  {id: 4, foo: 'bar'}, 
  {id: 5, foo: 'bam'} 
]});
```

`tree.get('data', {foo: 'bar'})` returns a single record, `{ "id": 1, "foo": "bar" }`. As does `tree.select('data', function(o) { return o.foo === 'bar' })`. Since 3 records have `foo` properties with `bar` values, I expected:

```javascript
[ 
  {id: 1, foo: 'bar'}, 
  {id: 2, foo: 'bar'}, 
  {id: 4, foo: 'bar'}
]
```

It seems this would also affect the `solvedPath` property. The current behavior is:
```javascript
> tree.select('data', {foo: 'bar'}).solvedPath
[ "data", 0 ]
```

Perhaps returning multiple values would result in something like:
```javascript
> tree.select('data', {foo: 'bar'}).solvedPath
[ "data", [0, 1, 3] ]
```

Anyway, just curious if there is currently a way to achieve this. Thanks.

**Comment by Yomguithereal** [comment]
Hello @jfsiii, currently cursors only refer to a single unambiguous path so yes, the function finds the first element and does not execute a filter. I should probably clarify this in the documentation. I am thinking about cursors selecting multiple parts of the data but the discussion remains open still. What you would need is to listen to updates of specific parts of the tree, isn't it?

The problem here is mainly the update part. If we could select multiple parts of the tree, what would be the behavior of the update methods?

**Comment by jfsiii** [comment]
> If we could select multiple parts of the tree, what would be the behavior of the update methods?

I thought `select` returned a set of 0 to N matches and the operations (`on`, `set`, `merge`, etc) applied to every member of the set. Something like:

```javascript
var fooBarCursor = tree.select('data', {foo: 'bar'});
fooBarCursor.merge({answer: 42}) // add `answer` property to all matches
fooBarCursor.on('update', ƒ);    // exec ƒ when any matches update
```

It sounds like I'm missing an ambiguous or problematic situation that you see. Can you add some code examples for the situation you're describing?

**Comment by Yomguithereal** [comment]
I added a note on the documentation concerning this particular point. I probably won't evolve towards multi-paths cursors as it would mean fall in a jQuery-like and I don't want to have to support this for the time being. Facets can now be used if filtered data is required anyway.
