### ISSUE TITLE
request - are there any jsfiddle, codepen, etc examples out there anywhere?

### ISSUE THREAD

**Issue by aktxyz** [Yomguithereal/baobab#152]

**Comment by Yomguithereal** [comment]
Hello @aktxyz, there are some examples but they are scattered everywhere. What would you need exactly?

**Comment by luisfontes** [comment]
I got interested after reading this: http://lucasmreis.github.io/blog/a-more-functional-approach-to-angular-with-baobab/

**Comment by lucasmreis** [comment]
This is one of the best explanations I've read, and he applies Baobab to React too: http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html

And @luisfontes , I'm glad that I could spark your interest with the blog! :+1:
