### ISSUE TITLE
Merge boolean values

### ISSUE THREAD

**Issue by nickdima** [Yomguithereal/baobab#153]
This could be a possible bug, but I'm not sure what's going on. It just seems that when calling `merge`, boolean values don't get update. Any idea?

**Comment by Yomguithereal** [comment]
Could be a bug indeed @nickdima. Let me check that.

**Comment by Yomguithereal** [comment]
Could you post your precise use case here @nickdima, please?I fail to reproduce what you describe.

**Comment by nickdima** [comment]
Hmm, I tried also with a simpler scenario and it works, maybe I'm doing something wrong. I'll close this for now and come back if I find an issue. Sorry for the trouble.
