### ISSUE TITLE
Baobab helpers : Cloning function helper uses ArrayBuffer not supported in <IE9

### ISSUE THREAD

**Issue by nluck** [Yomguithereal/baobab#156]
Currently IE9 does not support ArrayBuffer out of the box, running Baobab on anything lower than IE9 would throw undefined and break all rendering on the page.

**Comment by Yomguithereal** [comment]
Hello @nluck, you are right indeed. The mere occurrence of `ArrayBuffer` kills IE. I shall fix this asap.

**Comment by Yomguithereal** [comment]
Issue is normally fixed for IE9 on latest version. Can you try it and tell me whether it works on your side so I can release the patch?

**Comment by nluck** [comment]
This looks good from my end. Tested this in IE9 native on two different machines.
