### ISSUE TITLE
Using without mixin (with 0.13 classes)

### ISSUE THREAD

**Issue by natew** [Yomguithereal/baobab#157]
Just wondering, I'm working on reapp-kit which uses immutable js and fynx currently which gives me some cool cursor functionality, but I like Baobab where you can define inside your component the data you want, and it handles refreshing it for you. I think I could implement this not too hard with Fynx.

Anyway I'm using a new pattern in my app where I have a parent fetcher component that passes data as props:

```
<Store fetch={{ item: ['items', id] }})>
  <Component />
</Store>
```

So Component now gets `this.props.item` from the cursor `['items', id]`. One problem is using this with shouldComponentUpdate is tricky. If your parent component doesn't rely on the same cursor, it won't update, so it won't pass down the props. I guess the next step would be to have Store component listen and do a forceUpdate, not sure if that would work.

Anyway I think a Higher Order Component helper would be nice so in the Component file you'd write:

```
import Cursor from 'baobob';

class Component extends React.Component { }

export default Cursor({ item: ['items', id] }, Component);
```

Then you could have Cursor do a forceUpdate when store updates, which work no matter where in the tree you put the component.

I didn't see any discussion here on HOC or non-mixin usage, is it possible to do this? Any plans?

**Comment by Yomguithereal** [comment]
I am currently working on the v1 version of the library and will rework the mixins completely. I will probably move those to another module called `baobab-react` and propose both mixins and another solution working with ES6 classes. I will probably follow the solution presented [here](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) (which should be close to yours I think). I am not personnally fond of higher order components such as a `Store` one but will try it whatsoever and probably propose them also.

**Comment by natew** [comment]
I ended up getting something working with immutable.js here:
https://github.com/reapp/reapp-kit/blob/319015a7d2ff1b54d8f176a336442de59a3116c8/src/lib/store.js#L19

I love the HOC approach in this use case even though I'm less fond in other cases. It makes sense for your components to all accept props, especially when using immutable data. Now all my classes can accept props, and then a quick wrapper turns them into store listeners:

```js
store.cursor({ item: ['items', this.props.id], other: 'something' }), MyComponent);
```

**Comment by Yomguithereal** [comment]
Thanks for sharing this code @natew. Your example will surely help me when I start experimenting with the possibilities for the v1. However, why do you need `forceUpdate` in your case? This could hinder the benefits of pure rendering. Why isn't this possible just to render children with updated props?

**Comment by natew** [comment]
Force update will only re-render the higher order component which doesn't have anything in it's render function, and you need to forceUpdate because otherwise the child wouldn't get the new props.

If you're using an optimized shouldComponentUpdate (reapp uses one that checks immutable data) then it won't re-render the child, keeping your performance.

**Comment by christianalfoni** [comment]
Hi @natew, 

I have not looked into this implementation too closely, but are you sure? If the passed `Component ` in the example here is a component with nested components they will always render when the `CursorComponent` does a `forceUpdate`. It is not what is contained in the render method that decides what is force updated, it is the actual vDOM tree produced. So to my understanding if `Component` brings in a large vDOM tree it will always render that whole tree.

Again, I might misunderstand and have not tested this specific implementation, but important to be 110% sure on this one :-)

**Comment by natew** [comment]
Says here: https://facebook.github.io/react/docs/component-api.html

"Calling forceUpdate() will cause render() to be called on the component, skipping shouldComponentUpdate(). This will trigger the normal lifecycle methods for child components, including the shouldComponentUpdate() method of each child. React will still only update the DOM if the markup changes."

But of course I'll confirm in usage.

**Comment by christianalfoni** [comment]
Hi @natew ,

Indeed it does :-) Hm, maybe this has changed? There was this "big warning" earlier on using `forceUpdate()` due to it completely messing up your rendering.

But this version of it is a lot better, great! I learned something new :-) Thanks!

Btw, the implementation is similar to what I suggested in this issue too, #134. So I am all for this :+1:

**Comment by christianalfoni** [comment]
Though might be an idea to separate creating a cursor and creating a Component wrapper. So:

```js
var tree = new Baobab({
  foo: 'bar'
});
var cursor = tree.select('foo');

class FooContainer extends Baobab.Component {
  constructor() {
    this.cursors = {
      foo: 'foo'
    };
    super(); // Adds listeners etc.
  }
  // Render is in Baobab.Component, but looks like this
  render () {
    return this.props.children;
  }
}

<FooContainer>
  <MyComponent/>
</FooContainer>
```

**Comment by bebraw** [comment]
For what it's worth I did a silly little HOC like this:

```javascript
'use strict';
import React from 'react';

export default (Component, cursor) => {
  return class Persist extends React.Component {
    constructor(props) {
      super(props);

      this.state = cursor.get();
    }
    componentDidMount() {
      const that = this;

      cursor.on('update', function() {
        that.setState(cursor.get());
      });
    }
    render() {
      return <Component {...this.props} {...this.state} />;
    }
  };
};

// usage: connect(Component, cursor);
```

I'm aware it's not optimized but it works just fine for my simple case. I'm looking forward seeing a real solution. :)

**Comment by Yomguithereal** [comment]
Thanks for you examples @bebraw. I am currently developing the v1 and will soon begin to develop new React integration strategies and all the code presented here will certainly help me do so.

**Comment by Yomguithereal** [comment]
I've started React integration [here](https://github.com/Yomguithereal/baobab-react). There is currently just a mixin. I will start ES6 HOC and wrapper component experiments soon.

Related to #161.

**Comment by Yomguithereal** [comment]
Proposition made in the `baobab-react` repository.

**Comment by bebraw** [comment]
Some notes:

* Can you hit the source through babel? If you want, I can prepare a PR for you to make the module easier to consume.
* `Root(RootComponent, tree)` will trigger warning on many linters as they expect `new Root` in this case. Maybe go with lowercase naming for these.
* `Should cursors' data passed as state or props?` - I would probably go with `state`. If you go with `props`, you can end up in a conflict situation more easily. That's possible with `state` too but it's easier to control I think.
* `The function polymorphism of the cursor mapping should work on this.props or work on props passed as argument?` Can you provide an example?
* `The tree is accessible through context as well as the cursors (but in HOC and wrappers, the user will have to explictly define contextPropTypes and this is tedious).` - Can you provide HOC example for this case?

I'll most likely go with the HOC approach even though the others look nice as well. In ES6 it's either HOC or wrapper anyway.

**Comment by Yomguithereal** [comment]
* What could prevent the sources to be hit through babel?
* I was basing my work upon this seminal [gist](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) and other that all use uppercase so I was thinking this was standard. But I understand your anxiety for linters. Do you have examples where the HOC is not uppercased?
* Sensible reason. I guess state will be default while I'll let the option to switch to props easily.
* I'll provide an example asap.
* Idem. It's just that, in my experiments, if your higher order can use the context, the same cannot be said of the composed component below without explicitly declaring `contextPropTypes`.

**Comment by bebraw** [comment]
> What could prevent the sources to be hit through babel?

Have a look at [dnd-core branch](https://github.com/gaearon/react-dnd/tree/dnd-core) of `react-dnd`. You can see the author transforms the source through babel (just `babel ./modules --out-dir dist-modules`). `package.json` main points at that.

This makes it very easy to consume the library through Node.js without having to apply any transformations of your own.

> Do you have examples where the HOC is not uppercased?

See above. You can see HOCs like `configureDragDropContext` there. But I don't mind uppercasing as long as everything works (easy enough to disable the rule etc.).

> I'll provide an example asap.

Great.

> Idem. It's just that, in my experiments, if your higher order can use the context, the same cannot be said of the composed component below without explicitly declaring contextPropTypes.

I haven't dealt with contexts a lot so perhaps someone other can comment on this better.

**Comment by Yomguithereal** [comment]
> The function polymorphism of the cursor mapping should work on this.props or work on props passed as argument? Can you provide an example?

Following up [here](https://github.com/Yomguithereal/baobab-react/issues/12).

**Comment by Yomguithereal** [comment]
> The tree is accessible through context as well as the cursors (but in HOC and wrappers, the user will have to explictly define contextPropTypes and this is tedious). - Can you provide HOC example for this case?

Following up [here](https://github.com/Yomguithereal/baobab-react/issues/13).
