### ISSUE TITLE
set and unset have different semantics

### ISSUE THREAD

**Issue by kraf** [Yomguithereal/baobab#158]
This doesn't work:
```
tree.unset('a', 'b', 'c') // unsets 'a'
tree.unset(['a', 'b', 'c']) // no change at all
```
but this works:
```
tree.select('a', 'b').unset('c')
```

I understand why it's currently like this, but I would find it more intuitive, it at least `tree.unset(['a', 'b', 'c'])` would remove `c`. What do you think?

**Comment by Yomguithereal** [comment]
You are right and this will be the case in the v1 version currently in development :).

**Comment by Yomguithereal** [comment]
v1 should now solve this.
