### ISSUE TITLE
Maybe I should explain what a baobab is?

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#163]

**Comment by christianalfoni** [comment]
Get a logo, http://99designs.com/, v1.0 birthday present ;-) And give some background to the name and why the project exists. That would be awesome :D

**Comment by pindamonhangaba** [comment]
http://imgur.com/pSxvSkq

**Comment by chasm** [comment]
Anyone who has read [*The Little Prince*](http://www.angelfire.com/hi/littleprince/frames.html) knows what a [baobab tree](http://www.lepetitprince.com/wp-content/uploads/2008/actu2009_gpp_planete2.jpg) is.

**Comment by Yomguithereal** [comment]
Hello @chasm. Unfortunately, I discovered that a lot of people don't know what a baobab is or that The Little Prince exist. This could be a sensible inspiration for a logo however.

**Comment by chasm** [comment]
Not . . . know . . . *The Little Prince*? How is that possible?
