### ISSUE TITLE
Timestamped history - history replay

### ISSUE THREAD

**Issue by pindamonhangaba** [Yomguithereal/baobab#166]
I was thinking on a use case where I want to have two trees, one for application state and another for the ui state. If I want to later replay a users interaction I'd need to be able to sync the steps on each tree.

Also, having a replay system would be useful, even if read-only. Something like:

```
var replay = new BaobabReplay({appState: appStateHistoryObj, uiState: uiStateHistoryObj});
replay.trees; // returns {appState: Baobab, uiState: Baobab }

<Component appCursor={replay.trees.appState} uiCursor={replay.trees.uiState}>

// compares the next history entry datestamp of all trees and determines which get applied
replay.forward();
replay.backward();
```

Not sure how others are using baobab with React, but I don't like using a component's state, instead opting to use a cursor as state. So being able to record each components ui state changes, and later replay them seems like a good use case, even tough I haven't used baobab in production yet.

**Comment by Yomguithereal** [comment]
Hello @pindamonhangaba, in the v1 version (still in dev in the v1 branch but actually usable), you can record the state at a cursor (if you want to record the full state, you can record state at the root cursor).

```js
cursor.startRecording(maxNbOfRecords);
cursor.undo();
```

Would this work for your case?

**Comment by pindamonhangaba** [comment]
The v1 branch seems be a bit better prepared for this. Recording at cursors looks good, the question is if having a replay system is in baobab's roadmap. If yes I could wip up an initial replay system.

**Comment by tnrich** [comment]
+1 for having an undo system that can act on cursors at any level within the tree. I was about to ask whether you would need to make two baobab trees to support undo-redo if you didn't want all of you data undone.

**Comment by Yomguithereal** [comment]
History at cursor level shipped with v1. Could you tell me whether this fits your need? Else we'll continue to work on it of course :).

**Comment by pindamonhangaba** [comment]
Yes. For now it is enough, I still haven't refined my use case yet, so I might revisit this once I have a firmer grasp on baobab.

**Comment by tnrich** [comment]
Awesome to hear it! I have a couple questions I've been wondering about: 

Does the history data of a cursor use structural sharing (like how immutable js would store history), or does each step in the history necessitate its own object? 

I was wondering if you knew of any way to store the history of a baobab cursor to a database (say mongoDB) and then re-load it from the database at another point in time? The cursor.getHistory() call looks like an nice way of getting access to the array of history points, but re-inflating a cursor with history seems a bit more difficult...

Thanks yomguithereal!

**Comment by Yomguithereal** [comment]
For the time being, the history records are being deep cloned (this is not strictly necessary and I will add an option concerning this particular point later).

Re inflating a cursor is as simple as using `cursor.set` with your record actually.

**Comment by Yomguithereal** [comment]
Related to #174.
