### ISSUE TITLE
Usage with async data loaders

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#170]
Data fetching... React ecosystem notoriusly lacks not only libraries but even best-practices at the subject. Fortutanely there are some recent projects that address exactly this issue.

https://github.com/ericclemmons/react-resolver
https://github.com/andreypopp/react-async

Anyone tried to use them with Baobab? Are they after all compatible? That both I mentioned work by wrapping component in higher-order component and setting `props`. They are declared to be isomorphic friendly.

**Comment by Yomguithereal** [comment]
The problem I see with those approaches is that they always consider the fetched state to be owned by the components they affect. However, the fetched data, in most cases, should really belong to the application's state itself, not to a part of the UI. Anyway, it should work with Baobab but would feel strange in my opinion, if those methods are not used on top-level components.

But I've never tried those options in the code myself so I'll take any opinion you have on those @ivan-kleshnin.

Concerning the async data loader, we were thinking with @christianalfoni about hooks that would notify of a tree part being missing or not compliant to what you want. The idea would be to be able to trigger data fetching as soon as the application understands that its data is not complete according to what needs to be used.

**Comment by ivan-kleshnin** [comment]
@Yomguithereal unfortunately I didn't try them myself but I imagine it won't be smooth. 

> The problem I see with those approaches is that they always consider the fetched state to be owned by the components they affect. However, the fetched data, in most cases, should really belong to the application's state itself, not to a part of the UI.

Maybe not always, maybe they just pass it as props but I still agree with the second sentence. Baobab should be somehow involved and I don't see obvious way to involve it with this approach.

> Concerning the async data loader, we were thinking with @christianalfoni about hooks that would notify of a tree part being missing or not compliant to what you want. The idea would be to be able to trigger data fetching as soon as the application understands that its data is not complete according to what needs to be used.

Sounds interesting. By *hooks* you mean some declarative stuff in component? I can't imagine this can be trigger totally outside of component layer.

**Comment by Yomguithereal** [comment]
By hooks I mean an event like `missing`, for instance, that would fire whenever some particular part of the tree is accessed and this part has not a desirable value because data hasn't been fetched yet. This would lazily trigger the async data fetching part (which remains yours to do, Baobab would just notify you that some part of the tree was asked for but was not what one would expect to be, like a falsy value or else).

**Comment by ivan-kleshnin** [comment]
I found an [example](https://github.com/rackt/react-router/blob/e0a15ebc81d76119935fef27e0ab7d7b024b98fd/docs/api/run.md#examples-1) of how to load data with the help of react-router.

Basically you define hook `fetchData` (name is up to user) in every component which requires data. 
Obviously, it may be only those components React-Router is aware of (passed as handlers in routes).
```javascript
export default React.createClass({
  statics: {
    fetchData(params, query) {
      return RobotActions.loadOne(params.id);
    }
  }
  ...
```

Then, at the time of `router.run` we manually invoke those hooks
```
router.run((Application, state) => {
  // you might want to push the state of the router to a
  // store for whatever reason
  // RouterActions.routeChange({routerState: state});

  let promises = state.routes
    .filter(route => route.handler.fetchData)
    .map(route => route.handler.fetchData(state.params, state.query));

  Promise.all(promises).then(() => {
    React.render(<Application/>, document.getElementById("main"));
  });
});
```

This strategy seems decent to me. At least it's much better than my previous "load everything in global space at start" strategy. I'm yet to discover is it good enough / isomorphic friendly / etc.

**Comment by ivan-kleshnin** [comment]
> So the fecthing behaviour wouldn't be declared in components, components would just say: I need this part of the app state (as they currently do with baobab), and when they attempt to get it, the baobab tree would say: you want this but I know the value I have for it is not what you want, do you want to do something about it?

That seems entirely possible but I doubt about merging this stuff into Baobab. Data load is totally different responsibility area, there is no standard AJAX library, etc. I'm sure you're aware of it.

**Comment by Yomguithereal** [comment]
I don't mean Baobab should handle the data fetching and AJAX by itself. I'm just saying that it could provide you with the hooks meaning you need data fetching. You remain free to fetch said data the way you see fit.

**Comment by Yomguithereal** [comment]
On this particular subject, lately I use the `get` event of the tree to trigger data fetching when the gotten data is not "valid" according to criteria I define.

[Here](https://gist.github.com/Yomguithereal/b77e455766fd489fa54d) is an example of abstraction I use on one of my apps and that I will rebuild and publish soon.

**Comment by christianalfoni** [comment]
Hi guys, just putting in my two cents.

As concept I believe it to be a lot better to keep data fetching with the state logic.... as data is state. Components should not care if the data is there or not, just render based on it being there or not. Components should be as pure as possible, ideally just a product of state and rerender when that state changes.

This is something we see with Facebooks Relay. You just define what state the component requires and all data fetching and rendering of the component is handled based on that definition.

So with Baobabs "hooks" you would pretty much get the same concept as Relay. With missing state, go get it, though you have to manually wire it up. But this keeps the components as pure as possible and that is really important in my opinion.

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, this is also my opinion that component should not be responsible of the data fetching since this is state logic. I hope I started to draft something useful here with this weird abstraction.

**Comment by bfitch** [comment]
Hi @Yomguithereal and @christianalfoni. I just started to do some data fetching in a small side project and I'm wondering if any patterns around baobab data-fetching have solidified for you guys.

The two most promising approaches I've seen are @Yomguithereal's [gist](https://gist.github.com/Yomguithereal/b77e455766fd489fa54d) above and @christianalfoni's [excellent article](http://www.christianalfoni.com/articles/2015_04_26_Handling-complex-state-with-Baobab). I think I'll try Christian's approach, but it does seem a bit "low level" and I wonder if anyone has found a nice abstraction for this common task. :)

Thanks for this great library and excellent blog posts!

**Comment by Yomguithereal** [comment]
Hello @bfitch, I personally use on my apps the abstraction you saw on my gist. Unfortunately, I did not have time to completely write and open source it yet. But I'll sure do it when this is completely done and not just a stub. But it is quite easy to imitate what my abstraction does by plugging yourself on the tree's `get` event.

You've got a tiny example of that [here](https://github.com/medialab/aime-core/blob/master/interfaces/admin/js/fetching.js) if you want.

**Comment by bfitch** [comment]
Great @Yomguithereal. Thanks for the tip! I'll try to get something going with this approach.
