### ISSUE TITLE
dev version on npm

### ISSUE THREAD

**Issue by oncletom** [Yomguithereal/baobab#175]
Simply publish it this way:

```bash
npm publish --tag devel # or whatever tag name you'd like
```

Install:

```bash
npm install --save baobab@devel
```

It is slightly smoother than checking from a git URL as npm does not behave similarly with the `update` command.

The following…

```md
# Or for the latest dev version
npm install git+https://github.com/Yomguithereal/baobab.git
```

… would become…

```md
# Or for the latest dev version
npm install --save baobab@devel
```

**Comment by Yomguithereal** [comment]
Hello @oncletom.

You wouldn't get the latest commit on a dev version published on npm. I currently have a beta version available on npm though.

```md
npm install --save baobab@beta
# or
npm install --save baobab@1.0.0-rc1
```

Do you think the 

> ```# Or for the latest dev version
npm install git+https://github.com/Yomguithereal/baobab.git```

part is misleading? If yes, I should probably rewrite this part of the documentation indeed.

**Comment by oncletom** [comment]
> You wouldn't get the latest commit on a dev version published on npm.

This could be automated with [travis deploy](http://docs.travis-ci.com/user/deployment/npm/), by tagging `master` as `beta` systematically. Would have the same effect, but nicer as opting for one or another would simply a matter of package version: `npm i --save baobab@latest` or `npm i --save baobab@beta`.

The git+https is not misleading: I simply point out the git+https npm install behaviour is slightly different from a plain npm registry-based one.

**Comment by Yomguithereal** [comment]
Yes you are right, the install behaviour is different with git+https (notably the no npm hook and the fact the package will be reinstalled on any `install/update`.).

I am not opposed to a dev tag on npm (more frequent than beta therefore). In your experience, at what frequency would you publish dev versions on npm (I'd rather avoid any automatic deploying for the time being)?

**Comment by oncletom** [comment]
I don't know, I never did that — I push a new version every time a new feature comes in. And eventually a beta one in case of breaking change/unsure about stability of a minor-but-not-breaking feature.

I would say do it at a pace which is relevant to the project.

**Comment by Yomguithereal** [comment]
Will deploy a dev package from now on since the v1 has been published. I'll rework the README when the first dev package hits npm.

**Comment by Yomguithereal** [comment]
Some dev versions (often based on incoming features) are now available through npm.
