### ISSUE TITLE
Re-binding cursor on props change in React

### ISSUE THREAD

**Issue by qfz** [Yomguithereal/baobab#176]
In React, Baobab allows binding cursor(s) via a function that return props. But I found that if new props are passed in, the cursors are not re-bound, they stay the same as when component was mounted.

Is there a way to re-bind/update cursors when props change?

**Comment by Yomguithereal** [comment]
This is not currently possible without forcing the component to be recreated for the time being unfortunately. But this should become possible in the future. I'll work on it [there](https://github.com/Yomguithereal/baobab-react).

**Comment by Yomguithereal** [comment]
Hello @qfz. Cursors are now rebound with `baobab-react`.
