### ISSUE TITLE
Setting value on facets

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#180]
Hi @Yomguithereal ,

Just want to congratulate on version 1 first. Really really great work! One thing is Baobab, but just handling the repo, releases, community that is growing etc. Really excellent work, inspiring :-)

I have been thinking about facets a bit more and maybe this idea is going against the concept, but I just wanted to mention it as I think it is rather important. 

I think there is one confusing thing about facet cursors and that is the fact that they do not have an "input" value. When I think about a facet I think of it as translating an "input" to an "output" using depending cursors.

Looking at the the example from the front page:

```js
  currentProject: {
    cursors: {
      id: ['currentProjectId'],
      projects: ['projects']
    },
    get: function(data) {
      return _.find(data.projects, {id: data.id});
    }
  }
```

In this case the 'currentProjectId' is the actual "input". The 'projects' is just a dependency really, at least in comparison. So in more complex examples with many depending cursors it is difficult to understand how a facet works because you have to identify which cursor is the "input".

I also feel it is kind of artificial that you have a `currentProjectId` cursor and a `currentProject` cursor, where you set one cursor, but get the data from a different one. It is confusing compared to how a simple cursor works at least.

So I suggest extending the current functionality with:

```js
  currentProject: {
    value: '123',
    cursors: {
      projects: ['projects']
    },
    get: function(data, value) {
      return _.find(data.projects, {id: value});
    }
  }
```
And when changing this facet you would:

```js
tree.facets.currentProject.set('456'); // Or something similar (Facet API)
```

I can enforce this advantage by giving a more complex example:

```js
  projectRows: {
    value: [],
    cursors: {
      projects: ['projects'],
      users: ['users']
    },
    get: function(data, projectIds) {
      return projectIds.map(function (projectId) {

        // Prevent mutation of project by attaching it as prototype
        var project = Object.create(data.projects[projectId]); 
        project.user = data.users[project.userId];

        return project;
      });
    }
  }
```

So whenever you want to display new projectRows you would just: `tree.facets.projectRows.set(['123', '456', '789'])`. If not doing this you would need a `projectRowsIds` state for input, add it as a cursor on the facet along with the other two cursors that are just dependencies. One place for input and a different place for output.

Does this make sense? :-) Sorry to be so late with this input, but if it makes sense it would be possible to add this functionality without affecting existing.

Okay, thanks for hearing me out :-)

**Comment by christianalfoni** [comment]
Actually, taking this a step further for even more simplicity:

```js
var projectsDisplayedFacet = new Baobab.Facet({
  value: [],
  cursors: {
    projects: ['projects'],
    users: ['users'],
    comments: ['comments']
  },
  get: function (data, value) {
    return value.map(function (id) {
      var project = Object.create(data.projects[id]);
      project.user = data.users[project.userId];
      project.comments = project.comments.map(function (commentId) {
        return data.comments[commentId];
      });
      return project;
    });
  }
});

// Imagine a big state tree for the application where you have different domains
var tree = new Baobab({
  admin: {
    projectsDisplayed: projectsDisplayedFacet
  }
});

// The value set on the facet behaves just like any other cursor value
tree.push(['admin', 'projectsDisplayed'], 'someId');
```

So the benefits here are:

1. You can nest Facets inside your existing tree, which makes them belong to the domain of the application section. This makes it easier to get an overview of your state

2. Facets behave just like a normal cursor, it just converts the input to a different output. Easier to understand and reduces overall complexity of your code and mental image

This is of course a bigger change, but yeah... in theory it could be integrated with existing API :-)

**Comment by Yomguithereal** [comment]
Thanks @christianalfoni,

What I don't like with this `value` proposal is that it actually fragment the app's state. Normally you have your app's state centralized in the Baobab tree, which enable you to easily serialize it and reinject it. With values, your state is no longer centralized and you need some gymnastics again to pass the needed data to you UI. (The `currentProjectId`, even if it sounds clunky, is in fact part of your app's state).

Inserting facets into a Baobab's state is also a bad idea in my opinion because you shouldn't insert anything else than data in the state.

On the same topic, what can actually be done in the v1 but is not documented yet is:

* You can create facets through `tree.createFacet({cursors: {...}})`.
* You can pass facets to facets:

```js
var facet = tree.createFacet({
  facets: {
    name: 'existingFacetNameInTheTree',
    surname: tree.createFacet({...})
  }
})
```

Those exists because they are used internally by react integration.

Anyway, once again :), you open way to great reflexions about what the library should enable its uses to do. I also think that what seems clunky now is to be able to bind components to both cursors and/or facets to achieve what needs to be done.

I have some ideas where you store functions within the state to solve dynamic data like the ones proposed by facets but I lose the dependency system and this cannot be bought.

**Comment by christianalfoni** [comment]
Hi again :-)

Yeah, that is a very valid point indeed and I agree that it is more important to keep a clean state tree regarding types than merging facets into it!

The "input" cursor could of course be handled with a convention on putting that first in the cursors definition too. 

It still feels a bit weird to me having an action changing a state value which "magically" updates a facet used by a component. It just decouples something that I feel is very strongly coupled. But again, I have no idea how to couple this without merging facets with the tree... which indeed is a bad idea :-)

Hm, yeah, how is the syntax now for using facets with React? Is it supported?

Something like?:
```js
var Comp = React.createClass({
  mixins: [tree.mixin],
  cursors: function () {
    return {
      fruit: ['fruit']
    };
  },
  facets: function () {
    return {
      projects: ['projects']
    }
  },
  ...
});
```
Both merges with state?

**Comment by Yomguithereal** [comment]
This is what it will look like when done (some tiny little pieces of code remain to be written for it to work):

```js
var Comp = React.createClass({
  mixins: [tree.mixin],
  cursors: {
    fruit: ['fruit']
  },
  facets: {
    name: 'namedFacet'
  },
  ...
});
```

It will indeed merge with state with precedence given to cursors over facets.

**Comment by christianalfoni** [comment]
Okay, cool, looking good :-)

Anyways, facets is a really great feature. Handle complex state in the state layer, instead of having these "state wrapper components". 

I thought I would fire up a new article on Baobab this weekend. Get to know the new features, play around with facets etc. ;-)

You know if react will be ready with its facets by then?

**Comment by Yomguithereal** [comment]
I certainly hope so :)

**Comment by christianalfoni** [comment]
Cool, keep it up! ;-)

Closing the issue, thanks for discussing!

**Comment by Yomguithereal** [comment]
Facets are now working along with react integration. Just polishing things up and then I'll release an initial `react-baobab` version on npm working with today's `baobab@1.0.1`.

**Comment by christianalfoni** [comment]
:+1:
