### ISSUE TITLE
tree.set(path, '')  doesn't work

### ISSUE THREAD

**Issue by jpablo** [Yomguithereal/baobab#186]
I just found that setting a key with an empty string doesn't work.
```javascript
tree.set('path', '123')
tree.get('path') === '123'
tree.set('path', '')
tree.get('path') === '123'
```
I find this rather cumbersome, because I do need to set the value to an empty string in some cases, and currently I'm forced to unset the attribute, which is not exactly what I want.

Is this to be expected?

**Comment by Yomguithereal** [comment]
This is definitely a bug @jpablo. I'll look to it asap.

**Comment by Yomguithereal** [comment]
This nasty bug has been fixed. A version `1.0.1` will ship tomorrow.
