### ISSUE TITLE
[v1.1] Missing hook

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#188]

**Comment by Yomguithereal** [comment]
@christianalfoni, @jacomyal, following on our conversation about the missing hook. Would something of the kind work:

```js
var tree = new Baobab();

tree.select('path').on('missing', fn);
```

**Comment by christianalfoni** [comment]
I kinda got hung up on the idea of turning it around.

```js
var tree = new Baobab();

tree.select('path').on('cursor', function (path) {
  path // The actual path the cursor was registered to, might be nested
});
```
As you said, it is very difficult to define "missing". By running code on attaching a cursor you can create your own logic for "what is missing" and act upon it in various ways. That way you would also be able to put some state in there before the cursor created runs the `get()` to grab the state.

Maybe I am not looking at this from the same perspective, but yeah, those are my thoughts :-)

**Comment by Yomguithereal** [comment]
This looks more sensible indeed.

**Comment by jacomyal** [comment]
Both `cursor.on('missing', fn)` and `cursor.on('cursor', fn)` look weird to me:
  - When I read `'missing'`, I do not understand exactly when the event would be emitted. I guess it would be when the cursor's value would switch from non-missing to missing?
  - When I read `cursor.on('cursor', fn)`, I do not understand when the event should be emitted either. But this solution sounds more generic and it looks like it might solve more cases. May be something like `'select'`, `'selected'` or `'registered'` would be more explicit?

**Comment by christianalfoni** [comment]
Hi @jacomyal ,

Yeah, 'missing' makes assumptions to what a "missing" value is. In some scenarios it might be undefined, null or maybe if the path does not exist anymore... but then you have 'irrelevant'.

I also agree 'cursor' does not tell you much, but you are right in your assumption. It is when a cursor is registered to the path or subpath. From the alternatives I like `cursor.on('select')`. It just states exactly what it does.

**Comment by Yomguithereal** [comment]
The tree is now able to listen to both the `select` and the `get` event. I am currently hooking my data fetching on it and for now, it has proven to be quite effective. Will provide some code when the abstraction I use looks satisfying.

**Comment by christianalfoni** [comment]
Looking forward to that! Very interesting stuff! :-)

**Comment by Yomguithereal** [comment]
@christianalfoni, @jacomyal: I am currently using an abstraction looking like this:

```js
const client = new APIClient(); // whatever. I use https://github.com/Yomguithereal/djax-client
const store = new LocalStore(); // whatever. A localStorage abstraction
 
// A tree
const tree = new Baobab({
  fetchingUsers: false,
  session: null,
  data: {
    users: []
  }
});
 
// Creating a fetcher
const fetcher = new BaobabFetcher(tree, [
  
  // Stalking get events on the 'session' path
  {
    path: ['session'],
    
    // Function to use to trigger fetching
    get: client.getSession
  },
  
  // Stalking get events on the 'data users' path
  {
    path: ['data', 'users'],
    
    // We might want to use different functions, in order until one returns valid data
    get: [store.getUsers, client.getUsers],
    
    // If we expect specific data and don't want to consider falsey value as invalid
    expect: function(data) {
      return data.length > 1;
    },
    
    // A optional condition to be passed to trigger the fecthing
    condition: isUserLogged
  }
]);
 
// Possibility to add hooks to edit the state when fetching and/or errors etc.
```

It could be extended to trigger persisting to the server also but I am only experimenting with it for the time being.

**Comment by jacomyal** [comment]
@Yomguithereal I like [the multiple `get` functions](https://gist.github.com/Yomguithereal/b77e455766fd489fa54d#file-fetcher-js-L28-L29) a lot.

**Comment by christianalfoni** [comment]
Hi guys,

this interesting indeed! Have a few questions:

1. The "get" method. Does it support returning a promise? That would ensure that following gets with be ignored until the initial get had resolved that promise

2. How would one handle temporary state? For example when grabbing the session I would like to create a temporary object with an `$isLoading` state. We touched on this briefly with facets. Would it make sense to put that with this logic?

F.ex.

```js
const fetcher = new BaobabFetcher(tree, [

  // Stalking get events on the 'session' path
  {
    path: ['session'],

    // Function to use to trigger fetching
    get: client.getSession

    // Bad name, I know ;-)
   temp: function () {
     return {$isLoading: true}
   }
  }
]);
```

3. What about when you want to list 10 users and you do a "get" on each of the 10. Would it be possible with some batching stuff and dynamic props? Something like:

```js
const fetcher = new BaobabFetcher(tree, [
  {
    path: ['data', 'users', '$id'],

    // get ['data', 'users', '123'] and get ['data', 'users', '456'] would result in
    get: function (ids) {
     ids; // ['123', '456']
     // Fetch all of thems in one request
   }
]);
```

Just blurting it out here, but this kind of functionality is really good to have :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni,

1. This could be useful indeed.
2. I was indeed thinking of something of the kind.
3. I need to think about this a bit more.

There is also the other side of the problem to take into account: we should be able to persist data to the server in a similar way too.

**Comment by christianalfoni** [comment]
Are you familiar with Backbone? Maybe it would be nice to think of the cursors as "models". So you could do:

```js
tree.cursor('session').save();
```
You could pretty much "steal" the API of a model, as that is a proven good concept and add it to the tree. Something like:

```js
tree.addModel(['session'], {
  url: '/session'
});
```
And "out of the box" you would be able to save. This increases the scope of Baobab though, and might be better as a separate project. But having this API layer that makes a cursor something that does not only communicate down to your components, but also to the server is pretty cool :-)

**Comment by marbemac** [comment]
@Yomguithereal is this BaobabFetcher available somewhere?

**Comment by Yomguithereal** [comment]
@marbemac, not yet. I need to work on it. But be sure I will release it if I develop it. You can find a very minimalistic impression of how I did it for an app [there](https://github.com/medialab/aime-core/blob/master/interfaces/admin/js/fetching.js).

Besides, you can check out [doob](https://github.com/mistadikay/doob)  by @mistadikay and his [article](https://medium.com/@mistadikay/declarative-data-fetching-in-react-components-with-baobab-e43184c43852) about the same concept.

You can also ask @deepsweet who is also developing something of the kind I think.

**Comment by deepsweet** [comment]
we are working on doob together with @mistadikay, so feel free to ask :)
