### ISSUE TITLE
Array manipulation

### ISSUE THREAD

**Issue by nickdima** [Yomguithereal/baobab#189]
When getting an array from a tree and then modifying it you will also modify the reference in the tree. Is this expected?

```javascript
tree = new Baobab({array: [1,2,3]});
array = tree.select('array').get();
array[0] = 0;
tree.get().array;
// > [0, 2, 3]
```

**Comment by Yomguithereal** [comment]
Hello @nickdima. This is indeed to be expected. Baobab is not an immutable data structure per se for size and performance reasons. However, you should handle it like an immutable data structure.

I might add an option to freeze the content of the tree in `1.1.0` but this would come at a perf cost and should only be used in dev.

**Comment by nickdima** [comment]
OK, I'll close the issue. It was also documented here: https://github.com/Yomguithereal/baobab#common-pitfalls
