### ISSUE TITLE
Efficient data structures

### ISSUE THREAD

**Issue by alexmingoia** [Yomguithereal/baobab#191]
Does baobab recursively iterate over the tree to make shallow copies? Or does it use any kind of efficient data structure for shifting references such as hash map or vector tries? I'm considering using this for a project instead of immutablejs because of immutablejs' lack of good cursor support... but I'm worried about baobab performance of naive reference shifting...

**Comment by Yomguithereal** [comment]
Hello @alexmingoia,

In most of cases handled by Baobab (by this I mean the library does not aim at solving general cases like immutable-js but rather only storing an app's state which is rarely very huge), using hash map or vector tries is overkill and would not really improve the performance. So yes, currently, Baobab walk its trees recursively and does not make use of a more clever data structure.

The last time we checked the performances of the tree, they were quite good and we decided against implementing a different data structure so the library can remain light.

This said I am not opposed to put the question back on the table today. So, if you are willing to help, I am going to reconsider hash maps, vector tries etc. and see whether it makes sense to implement them into Baobab's context.

On a side note, what is your project about? Is this a UI?

**Comment by Yomguithereal** [comment]
Also, be sure that I do not deep clone the tree at each update of course. I only make shallow copies of the relevant items in the updated path like clojure's persistent vectors do, for instance.

**Comment by alexmingoia** [comment]
Yes, I understand it is not an immutable structure but a persistent one. This is fine for me as my project is a FRPish UI (thinking about using this with https://github.com/Raynos/mercury instead of his observ-hash and observ-array modules).

I think it'd be best to first create a suite of benchmarks before implementing clever data structures. I'll try to find some time to add benchmarks next week.

**Comment by Yomguithereal** [comment]
Any news about this @alexmingoia?
