### ISSUE TITLE
Nested arrays

### ISSUE THREAD

**Issue by alexmingoia** [Yomguithereal/baobab#192]
How can I accomplish `[ [ "child array" ], "parent item" ]` ?

This does not work:

```javascript
var tree = new Baobab({ parentArr: [] });
var parentArr = tree.select('parentArr');
parentArr.get(); // => []
parentArr.push(["orange"]);
parentArr.get(); // => ["orange"] but I expect [ [ "orange" ] ]
```

How do I do this? Does Baobab not support nesting arrays?

**Comment by alexmingoia** [comment]
Nevermind... I was using the API wrong (the push stuff is a little confusing sharing the same name as array methods). However, I did find what I think is a bug with the push API:

```javascript
var tree = new Baobab({ parentArr: [ ["green"] ] });
var parentArr = tree.select('parentArr');
parentArr.push(0, "blue"); // should result in [ "green", "blue"]
parentArr.get(); // [["green"], "blue"] // incorrect?
```

**Comment by Yomguithereal** [comment]
Hello @alexmingoia,

The pushed value are handled like they would be with the concat function. I agree this is somewhat misleading and we can discuss the relevance of it if you want. So you'd be able to insert a nested array by doing `cursor.push([['item']])`.

Your second example, however, does sound like a bug. Let me check this and come back to you.

**Comment by Yomguithereal** [comment]
Ok, I think the bug exposed in your second case is now dead.

**Comment by alexmingoia** [comment]
Wow thank you for the quick response! Baobab is an awesome module. It's very useful.

**Comment by alexmingoia** [comment]
I don't think the API here is much of an issue... since you're not usually pushing an array as an element.
