### ISSUE TITLE
Facet Cursor syntax 

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#195]
Continue to experiment with Baobab. Facets look great. One little question / proposal:

Current syntax:
```javascript
cursors: {
  url: ["url"],
  models: ["robots", "models"],
},
get: function(data) {
  let {url, models} = data; 
  ...
}
```

Subjectively cleaner alternative:
```javascript
cursors: [
  ["url"],
  ["robots", "models"],
],
get: function(url, models) {
  ...
}
```

Keys removed, destructuring is lifted to function signature.

**Comment by bebraw** [comment]
:+1:

**Comment by Yomguithereal** [comment]
Why not? This wouldn't be incompatible with the current implementation. Let me thinks about it a bit more and take a decision.

**Comment by Yomguithereal** [comment]
Shorthand implemented in v2.
