### ISSUE TITLE
$cursor pointer only gets data, does not listen to change

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#196]
hi there,

Testing out v1.0 and writing the article. Found this thing:

```js
var tree = new Baobab({
  projects: {
    '0': {
      title: 'foo'
    },
    '1': {
      title: 'bar'
    }
  },
  currentProjectId: '0'
});

var App = React.createClass({
  mixins: [mixins.root],
  render: function () {
    return (
      <h1>Hello world - <Child/></h1>
    ); 
  }
});

var Child = React.createClass({
  mixins: [mixins.branch],
  cursors: function () {
    return {
      project: ['projects', {$cursor: ['currentProjectId']}]
    };
  },
  render: function () {
    return <span>{this.state.project.title}</span> 
  }
});

React.render(<App tree={tree}/>, document.body);

setTimeout(function () {
  tree.set('currentProjectId', '1');
}, 2000);
```

I would expect pointing to a value using a cursor would create a listener on that cursor. In this scenario the component does not update. I have to explicitly add the 'currentProjectId' as a cursor. Is is supposed to work like that?

btw, nice going using context and just inject the tree! Good stuff ;-)

**Comment by Yomguithereal** [comment]
It looks like I did not think this through. I shall fix this erroneous behaviour soon.

If I recall correctly, using context to inject the tree was your idea, wasn't it ;-)?

**Comment by christianalfoni** [comment]
Sweet :-)

Haha, come to think of it, yeah... I even wrote on article on it! :-D
