### ISSUE TITLE
Map functionality?

### ISSUE THREAD

**Issue by psawaya** [Yomguithereal/baobab#197]
Thanks for building this library, I've really enjoyed working with Baobab so far.

Would it be possible to implement a map function on a Baobab cursor, similar to [what cortex has](https://github.com/mquan/cortex#cortex-wrapper-of-array-data-has-the-following-methods)?

Specifically, I'm talking about mapping a list in my Baobab tree to a function is called with a cursor for each child at that branch.

I realize I can do this iteratively with `.leftmost()` and then repeated calls to `.right()`, but I think a map function would be useful.

**Comment by Yomguithereal** [comment]
Hello @psawaya,
I am not sure to understand what cortex's map is doing. Is the objective to update an array at a given cursor?

If yes, would this differ from something like:

```js
var array = cursor.get();
cursor.set(array.map(fn));
```

?

**Comment by psawaya** [comment]
No, I'm not looking to update an array, just get a cursor for each item in an array and have them passed to a function.

This is often useful when building tables within React. I have a cursor in a parent element pointing to a list of items, and I want to render each of them into rows. In Cortex, I can call `map` on that list and pass a cursor for each list item to a separate React component, which renders a table row.

**Comment by Yomguithereal** [comment]
Ok, would this translate to something like this:

```js
var cursors = cursor.get().map((_, i) => cursor.select(i));
```
?

**Comment by psawaya** [comment]
Here's a quick (untested) psuedo-JSX example that explains what I'd like. Instead of using a function like `mapper`, it'd be nice to be able to call `this.cursors.fruits.map` in `FruitsList.render`.

```
var tree = new Baobab({
  fruits: ['apple','orange','pineapple']
});

function mapper(cursor, f) {
  var node = cursor.select(0).leftmost();
  var out = [];
  while (node !== null) {
    out.push(f(node));
    node = node.right();
  }
}

var FruitsList = React.createClass({
  mixin: [tree.mixin]
  cursor: {
    fruits: 'fruits'
  }
  render: function() {
    return <ul>
    {
      mapper(mapper(this.cursors.fruits, function(fruitNode){
        <li>{fruitNode.get()}</li>
      }))
    }
    </ul>
  }
});
```

**Comment by psawaya** [comment]
Yes, that would also work, though it feels a bit wrong to me to call `.get` on the whole list when really I'd just like cursors.

**Comment by Yomguithereal** [comment]
Just a precision: in your example, you just need the value of each items in the list. Do you need a cursor for each item of the list to bind each rendered elements to its cursor or are you just interested in the values?

**Comment by psawaya** [comment]
It was a toy example that just uses the values. In my actual project, I'm mapping to an inner component which modifies the values at a given cursor.

I think that's cleaner than having the child component call the parent component with an index and having the cursor modified there.

I'm completely switching my code over from Cortex to Baobab, and `.map` is literally the only thing I miss about Cortex. :)

**Comment by Yomguithereal** [comment]
Ok. Got it now :). I'll think about it then. I'll check if such methods exist in the zipper world so I can see whether I should choose another name than map.

**Comment by psawaya** [comment]
Thanks!

**Comment by Yomguithereal** [comment]
If I can continue to ask you some questions:

* in which cases do you prefer passing cursors to child components rather than the data they need through props?
* we are definitely speaking of something of the kind:

```js
var a = cursors.map(function(node, i) {
     return something;
});
```

**Comment by psawaya** [comment]
I'm trying to build a table where users can modify data at individual cells. Ideally, I'd take the table data structure (a big array of JSON objects), map each row up to a cursor which is passed to a row element, and then slice up each item in a row element to a cell cursor.

The great thing about baobab is that I can place a listener at the row level, and then fire off a call to my server to update the data there.

And yes, that's exactly the syntax that I'd like. :+1:

**Comment by Yomguithereal** [comment]
`cursor.map` has been added to master branch. I will soon release a beta `1.1.0-rc1` version.

**Comment by psawaya** [comment]
Woah, that was fast. Thanks so much!
