### ISSUE TITLE
is it possible to add new item in the middle of array?

### ISSUE THREAD

**Issue by asfktz** [Yomguithereal/baobab#203]
var tree = new Baobab({
    arr: [
        { id: 1 },
        // <-- how to add a new item without replacing the entire array?
        { id: 2 },
        { id: 3 }
    ]
});

**Comment by serjout** [comment]
splice

2015-04-25 1:51 GMT+03:00 Asaf Katz <notifications@github.com>:

**Comment by Yomguithereal** [comment]
@serjout is right indeed. You can use `cursor.splice`.

```js
var tree = new Baobab({
  list: ['banana', 'apple', 'pear']
}, {asynchronous: false});

tree.select('list').splice([1, 0, 'cherry']);

// will produce ['banana', 'cherry', 'apple', 'pear']
```

But, while actually creating this example, I noticed the library is buggy on that point and will always append the desired items at the end of the list. I therefore need to fix that asap.

**Comment by Yomguithereal** [comment]
The bug is now fixed. The fix should ship with the `1.0.2` version.

**Comment by asfktz** [comment]
Thanks!

**Comment by asfktz** [comment]
is there a way to get the index of the cursor without doing someting like this?: 
var item = tree.select('arr', 'apple').get();
var i = tree.select('arr').get().indexOf(item);

**Comment by Yomguithereal** [comment]
```js
var item = tree.select('arr', 'apple').get();
```

suggests that you are reaching an object, not an array.

Do you mean something of the like of:

```js
var item = tree.select('arr', e => e === 'apple').get()
```

If yes, I guess your solution is pretty much what you should do. I could add sugar on top of the cursor's API to help you do so but I wonder whether it would not be overkill.

**Comment by asfktz** [comment]
what i mean is the for the splice method I need the index of the item:

```js
var item = tree.select('arr', 'apple').get();
var i = tree.select('arr').get().indexOf(item);

tree.select('arr').splice([i, 0, 'cherry']);
```

and my question is if there's a way to get the index without getting the raw array and raw item?

**Comment by Yomguithereal** [comment]
I could give you the possibility to pass a function or a descriptive object as first arg to the splice method but I guess I couldn't do anything more than that.

**Comment by Yomguithereal** [comment]
Closing this in favor of #352.
