### ISSUE TITLE
Mention `commit` method in README?

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab#205]
There's a mention about `autoCommit` flag that refers to `commit` method but no discussion of `commit` method itself. It could be a good idea to cover that.

**Comment by Yomguithereal** [comment]
It would be a good idea indeed.

**Comment by milanlandaverde** [comment]
+1

**Comment by Yomguithereal** [comment]
I added a note about `tree.commit` in the update section. Is that sufficient?

**Comment by bebraw** [comment]
Yeah, at least now you know it's there. :+1:

Maybe it would be a good idea to split up the docs at some point and just leave an overview at README.
