### ISSUE TITLE
Why did I not think of this before?!? :-)

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#208]
Hi @Yomguithereal ,

This is freakin' awesome. We need a "rehydrate" type of method on the tree. Do the following:

- Set up a hot loading webpack workflow, f.ex. use my boilerplate: 

`svn export https://github.com/christianalfoni/webpack-express-boilerplate/trunk ./dir`

- Install Baobab, react etc.

- Create a `state.js` file:

```js
export default {
 text: 'hey'
};
```

- In your `main.js` file:

```js
import Baobab from 'baobab';
import state from './state.js';

let tree = new Baobab(state);

if (module.hot) {

  module.hot.accept('./state.js', function () {
    let newState = require('./state.js');

    // This should be easier to do
    Object.keys(newState).forEach(function (key) { 
      tree.set(key, newState[key]);
    });
  });

}
```

- Now hook up some Component and start changing the `state.js` file

- Voila! Hot application updates using Baobab. Combining this with react-hot-loader you do not only get hot updates on component changes and their internal state, but you also get it on application state

Think of the development flow. You can put your application in any state using a `state.js` file for Baobab and you can develop your components using that state, also hot-reloading! This is a game changer I think :-)

**Comment by christianalfoni** [comment]
Have to do some work on releasing listeners etc., so should end up as a `baobab-hot` plugin for Webpack, but yeah... you get the feel of it :-)

**Comment by christianalfoni** [comment]
Okay, I have been researching a bit. How would you feel about me setting up a new repo: `baobab-hot-loader`? This will allow the hot patching to work "out of the box". A challenge though is that the mixins needs some added behaviour to patch changes to the cursors/facets added to the components. I am a bit unsure of the best strategy for this:

1. baobab-react detects baobab-hot-loader and extends functionality on the mixins

2. baobab-hot-loader requires baobab-react and "configures it to do hot loading"

Anyways, it is just a matter of finding the best solution, but it will require the mixins to be able to "reset" themselves by doing a diff on the cursors/facets object attached to the component.

Anyways, this is really awesome stuff! With `baobab-hot-loader ` and `react-hot-loader` we can create a completely fluent experience of building applications. No more "click click click" to get to the state you need, just change your state file and you are there!

**Comment by christianalfoni** [comment]
Okay, I created a video on this to show off the concept, and also general Baobab stuff. I found a bug in `react-hot-loader` during testing so I hope that gets pulled soon.

[Hot loading application state with Baobab and Webpack](https://www.youtube.com/watch?v=iVYF-_gjJGg)

I got the normal `mixins` running with this, so need to expand to the decorators, wrappers etc. 

And watch out for a pull request :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, I need some time to check all this out but one thing I notice is this:

```js
// This should be easier to do
Object.keys(newState).forEach(function (key) { 
  tree.set(key, newState[key]);
});
```

What about this:

```js
tree.set(newState);
```

This actually works.

**Comment by Yomguithereal** [comment]
Okay, I had some time to check this out. Looks very cool indeed! I ought to try webpack hot loading etc. You can of course go ahead and create `baobab-hot`, I don't see why I should prevent you from doing so :-).

I don't understand the part about mixins reloading very well however. I don't know if this can help you but facets have an undocumented `refresh` method that can be use to, well... refresh them. I use it in the mixins, for instance, when new props are received. [Example](https://github.com/Yomguithereal/baobab-react/blob/master/src/mixins.js#L84).

**Comment by christianalfoni** [comment]
Hi @Yomguithereal ,

I did some more work on this and created pull request. It works very well now in a "none intrusive" way. So if the mixins get that pull request baobab-hot-loader is free to optimize on its end. Only change to mixins is a `componentWillUpdate` where it checks if `baobab-hot-loader` has flagged them as "hot". If so it does a check and updates.

Using webpack I think even the flag check is removed because it will always be false.

**Comment by christianalfoni** [comment]
Okay, so got repo, https://github.com/christianalfoni/baobab-hot-loader, updated now with some documentation. Also got the DIFF logic in there so that any changes done through running application code will not be overridden when you change the state of the tree from the file :-)
