### ISSUE TITLE
Root cursor data updating is not listened?

### ISSUE THREAD

**Issue by tokenvolt** [Yomguithereal/baobab#210]
I was trying to update the whole tree, but it seems that it's not possible to fire an update event.
````js
tree = new Baobab({ 
  first: 1, 
  second: 2 
})
tree.select('first').on('update', someCallback)
tree.root.set({ first: 1.2, second: 2.2 }) // someCallback is not executed
````

Instead I need to use a 'root' key in order to achieve this. Something like this:
````js
tree = new Baobab({ 
  root: { 
    first: 1, 
    second: 2 
  } 
})
tree.select('root', 'first').on('update', someCallback)
tree.select('root').set({ first: 1.2, second: 2.2 }) // now someCallback is executed
````
It this an expected behaviour?

**Comment by Yomguithereal** [comment]
Hello @tokenvolt,
This is clearly a bug. Thanks for noticing it. The 2a917c4 commit should fix it. I'll ship a v1.0.3 soon.

**Comment by tokenvolt** [comment]
@Yomguithereal, thanks for the quick fix!
