### ISSUE TITLE
Facet error when using a cursor to change rendered component

### ISSUE THREAD

**Issue by cassiozen** [Yomguithereal/baobab#211]
I Have a component that conditionally renders `<Login />` or `<Ok />` depending on a value on a Baobab tree:

```
var Main = React.createClass({
  mixins: [branch],
  cursors: {
    userCursor: ['user']
  },

  render() {
    if(this.state.userCursor.id === ''){
      return <Login />;
    } else {
      return <Ok />;
    }
  }
})
```

But as soon as the tree is updated and an user object is set, I get an "Cannot convert undefinded or null to object", on facet.js.

On facet.js, if I add a check before self.cursors everything works, but this is obviously not a permanent solution:
```
 this.updateHandler = function(e) {
    if(!self.cursors) return;
    var paths = Object.keys(self.cursors).map(function(k) {
      return self.cursors[k].solvedPath;
    })
```

**Comment by Yomguithereal** [comment]
Hello @cassiozen, I'll investigate this issue asap. In the meantime, could you show me what your app's state looks like, please?

**Comment by cassiozen** [comment]
Sure:

```
var Baobab = require('baobab');

var tree = new Baobab({
  user: {
    id: '',
    username: '',
    firstname: '',
    lastname: '',
    email: '',
    avatar: ''
  },
  viewStates: {
    login: {
      invalidLogin: false,
      loading: false
    }
  }
});

module.exports = tree;
```

**Comment by Yomguithereal** [comment]
Ok @cassiozen, I traced the bug (a very nasty one I must say) and it seems the event emitter is the culprit here. I need to investigate some things and hopefully fix this.

**Comment by Yomguithereal** [comment]
Well it seems that `emmett`'s behaviour is consistent with node's emitter (see [this](https://github.com/joyent/node/issues/7872)).

I therefore need to add a `killed` flag in the facet to avoid those kind of things.

**Comment by Yomguithereal** [comment]
Ok, tested this just now. This should be fixed as per last commit.

**Comment by jpablo** [comment]
Nice! this was affecting me too.
