### ISSUE TITLE
Check update event when committing non-existent changes

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#213]

**Comment by Yomguithereal** [comment]
@christianalfoni: do you think it could be useful to give an option for the tree to do a simple equality check when setting data on the tree to avoid cases where you wouldn't the tree to trigger an update while you are updating with an identical value?

**Comment by serjout** [comment]
in some cases might need to fire update event manually. 
e.g. call tree.commit() to prevent excess redrawings. and after all updates were applied i using cursor.apply(x => x) to fire update event. imo it isn't bad practice.

**Comment by Yomguithereal** [comment]
So do you think the tree should perform some kind of shallow equality on setters then @serjout? I often find myself checking if a value is equal to the one I am trying to set just to be sure I won't trigger unnecessary updates.

**Comment by christianalfoni** [comment]
You make a good point @Yomguithereal. It is a nice optimization, as long as it is a shallow check :-)

**Comment by Yomguithereal** [comment]
@christianalfoni, this could be a nice optimization but could be a dangerous one if one finds himself not understanding why its tree does not fire an update.

**Comment by Yomguithereal** [comment]
v2 comes with the `pure` option to tackle this issue.
