### ISSUE TITLE
Integrating with React-Router

### ISSUE THREAD

**Issue by marbemac** [Yomguithereal/baobab#214]
I'm trying to wrap my head around the changes in Baobab 1.0. I'm using react-router, and my render function looks something like this:

```js
router.run((Handler, state) => {
  React.render(<Handler {...state} />, document.getElementById('app-container'));
});
```

How would this work with the new root/branch architecture?

**Comment by tokenvolt** [comment]
Hi, @marbemac, did you try to pass it to Handler?
````js
var tree = require('path/to/tree');
// ...
router.run((Handler, state) => {
  React.render(<Handler tree={tree} {...state} />, document.getElementById('app-container'));
});
`````

**Comment by shane13hsi** [comment]
Hi, @marbemac. Assume the routes is

```javascript
<Route name='app' path='/' handler={AppPage}>
    <Route name='subRoute' path='/sub' handler={SubPage}>
    </Route>
</Route>
```

Pass the tree to handler, like @marbemac 's code, then in AppPage, mixin the (baobab-react/mixins').root.

**Comment by marbemac** [comment]
All set thanks guys!
