### ISSUE TITLE
primitive value test

### ISSUE THREAD

**Issue by AutoSponge** [Yomguithereal/baobab#216]
The type test at https://github.com/Yomguithereal/baobab/blob/55c8313d3bf26df83ef5fe31d8d20d1034752261/src/type.js#L52 fails to properly identify Symbol as a primitive (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Primitive_values). I suggest an alternative test:

```js
function ( value ) {
    return value !== Object( value );
}
```

**Comment by Yomguithereal** [comment]
Seems right indeed. Will do so in an upcoming commit.

**Comment by Yomguithereal** [comment]
Hello @AutoSponge. Do you have a benchmark somewhere concerning this function? I am trying to defined which method is the fastest concerning primitive checks for the [typology](https://github.com/jacomyal/typology) library.

**Comment by AutoSponge** [comment]
Try this: https://github.com/AutoSponge/bench

**Comment by Yomguithereal** [comment]
I was speaking about the primitive check shown above :).

**Comment by AutoSponge** [comment]
Woops. I saw https://jsperf.com/testing-value-is-primitive/7 which may need modification for your needs.

**Comment by Yomguithereal** [comment]
Thansk @AutoSponge. Will edit that to check.
