### ISSUE TITLE
TimeMachine

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#222]
Hi @Yomguithereal ,

I was just wondering. The history functionality of Baobab now. It keeps a complete copy of the whole tree for every record? Also each cursor does that the same way?

I have been thinking about how we solve our database on our backend. We have two databases. The first database stores all events passed from the client. So an event is every action done in the client. As these events are stored they also operate on the actual database, creating the current state.

The really cool thing about this is that if anything bad happens to the state database you can just play back all the events and you are back at your current state. The real power of this though is that you can do a lot of cool calculations with these events, stuff you could never do with a typical database structure.

Anyways... I was thinking about Baobab. What if you store all method calls on `set`, `push`, `apply` etc. and their arguments in an "internal database". The memory footprint is a lot smaller than storing complete copies of the whole tree. That way it would be possible to just play back these events to create any state in the tree.

Specifically I am thinking about something like this:

https://www.youtube.com/watch?v=2HK4ENBPcWA

Think of the development power with both the `baobab-hot-loader` and the possibility to "turn back time". I do see challenges of course, but it is something worth researching I think.

I am building a small prototype now, just wrapping the methods. This means that it could of course just be a "plugin" to Baobab, `baobab-timemachine` or something, as it does not really depend on any internals. Just wrapping the methods of the tree.

Anyways, just some thoughts :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. Now, you can record history at cursor level so you can record only specific parts of the tree if needed. You remain free to record the full state by recording at root cursor if needed.

However, Baobab does not store copies of the tree at all. Baobab is a persistent data structure so what is stored are merely references pointing towards older states of your tree.

However, if you need to send those states to a server, you won't be able to do anything else than sending a whole serialization of the tree, or at least only the modified paths.

What you can do is listen to the tree's updates, and send the modified data parts to a server holding its own Baobab tree and reapplying modification on him. Then you can go back in time seamlessly without having to store the precise operations.

But, you might be interested with the precise operation, and this reminds me I should give access the nature of the operation in the update logs.

**Comment by christianalfoni** [comment]
I got so crazy inspired by this and ELM, so I started a new project: https://github.com/christianalfoni/cerebral. It uses a concept of signals, which relates to the actions you would use to update a Baobab tree. The signals are just arguments and mutations, so those are a lot easier and more memory effective to track than complete tree states.

So I think a time machine should rather be implemented in front of Baobab, not inside. So `baobab-signals` or something. That would allow you to revert the tree to its initial state and just play back the signals. Anyways, just blurting out some theories here :-)

**Comment by Yomguithereal** [comment]
Yes but you should however be able to get from the tree the nature of the updates so you can perform your magic afterwards and I intend to do so for v1.2. For the time being, the updates will only tell you the paths that have been updated.

**Comment by Yomguithereal** [comment]
@christianalfoni: you haven't responded whether you saw obstacles concerning the `syncwrite` behaviour in your experience about cerebral :-).

**Comment by christianalfoni** [comment]
Hi @Yomguithereal :-)

My conclusion this far, with Cerebral, is that writes to state should always be synchronous. Async optimization is something I consider to be something that should be handled "outside" of state changes.

To be more specific. In Cerebral a signal is the "entry" point for state changes. It is much like an action with Baobab, though it is a chain of actions. That is where I decide to use requestAnimationFrame. Any state changes are synchronous and when the signal is done (multiple state changes) I synchronously trigger update events.

So what this basically means is that when I want to do state changes JS charges up an animationframe and then runs all state mutations and component updates synchronously (within 16ms). It is not really something Baobab should handle at all I think. If you need performance, use requestAnimationFrame on your action that does the mutations. 

Does that make sense? :-)

There are requests on splitting out the "signals" implementation of Cerebral, which I think baobab could benefit a lot from. I hope to find some time at the end of my vacation to create that implementation. Will set up an issue and you can take a look?

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. I am currently wrapping up a first beta for Baobab v2 with the following changes: write operations are now synchronous while the updates notifications are asynchronous for obvious performance reasons. Plus, the tree now exposes the detail of its transactions so you can replay them elsewhere or display them if needed.

I think this is quite parallel to what you perform with your state in Cerebral. I need to check this more precisely and understand what you mean by signals and signals implementation before doing anything though :-).

**Comment by christianalfoni** [comment]
Sweet! Yeah, signals is a really cool concept. It takes you a step closer to functional programming when handling state changes and it has some other really nice features too. Let you know when I have something to show off :-)
