### ISSUE TITLE
v1.2.0 Roadmap

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#230]
Here are the potentially upcoming features and decisions to be made for v1.2.0:

## Nested facets?

As explained by @ivan-kleshnin and @RJ in #226:

```js
var tree = new Baobab(
  {...},
  {
    facets: { 
      persons: {
        john: {...},
        jack: {...}
      }
  }
);
```

## Nested facets mappings?

```js
var tree = new Baobab(
  {...},
  {
    facets: {
      greeting: {
        cursors: {
          category: {
            one: ['toto'],
            two: ['tata']
          }
        }
      }
    }
  }
);
```

## Variant for facets mapping?

```js
var tree = new Baobab(
  {...},
  {
    facets: {
      greeting: {
        cursors: [
          ['path1'],
          ['path2']
        ],
        get: function(var1, var2) {
        
        }
      }
    }
  }
);
```

## The $cursor conundrum

Should the `$cursor` feature remain (I wouldn't break and go v2 on this since this feature is probably not very used)?

## A splice polymorphism

Possibility to pass function and descriptor object in the index argument of the splice method.

## Memoizing nested reference by cursor or better nested accessor

Related to #200.

## Should syncwrite become standard?

The question remains open.

**Comment by nthtran** [comment]
:+1: for nested facets. I thought it was logical that they could be nested similarly to cursors, only to find out it wasn't possible.

**Comment by ivan-kleshnin** [comment]
@Yomguithereal I don't exactly understand about **Nested Facet Mapping**. What are those strings out there? A names of inputting facets?

@nthtran what do you think about "syncwrites" subject? 
We need usecases and feedback from other guys.

**Comment by nthtran** [comment]
Just started using `syncwrite` and it works fine so far. Should be the default if there aren't any problems with it IMO.

**Comment by RJ** [comment]
`syncwrite` should definitely be the default, imo.

I was having all sorts of headaches before, since i'm processing a stream of messages to build up a tree. Without syncwrite i have to strategically commit() to ensure the shape of my tree is built up before messages are inserted into newly-created leaves.

**Comment by Yomguithereal** [comment]
@ivan-kleshnin, what I was meaning with **Nested Facet Mapping** is the possibility to define your cursors dependencies as nested likewise:

```js
tree.createFacet({
  cursors: {
    persons: {
      daniel: ['daniel'],
      john: ['other', 'part', 'john']
    }
  },
  get: function({persons}) {
    // ...
  }
});
```

But it isn't probably very useful.

**Comment by milanlandaverde** [comment]
Maybe this was answered elsewhere, but what about access to facets within the creation of a facet:

```javascript
const tree = new Baobab(
  {...},
  {
    facets: {
      cursors: {
        // ...
      },
      facets: {
        // ...
      },
      get(cursorData, facetData) {
        // ..
      }
    }
  }
);
```

I think this would prove useful.

**Comment by Yomguithereal** [comment]
Actually, @milanlandaverde, you can already do that. With the exception that keys will be merged into a single data object. I did not document it yet because I wanted to stabilize the API before but I think this is now safe to use it.

**Comment by tnrich** [comment]
+1 for documentation on using facets inside of other facets!

awesome though that it's already implemented!!

I'll be trying that out
