### ISSUE TITLE
Why methods ['apply', 'chain', 'push', 'unshift', 'splice', 'merge'] are not defined in Baoabab instance?

### ISSUE THREAD

**Issue by serjout** [Yomguithereal/baobab#235]
Since v1 we can use polymorphic calls e.g. cursor.splice(['path', 'to', 'array'], [idx, 1]), but these methods are not defined in Baoabab instance yet.

*console output:*
```
store.constructor.name
"Baobab"
store.constructor.version
"1.1.0"
store.set
baobab.js:62 function () {
	      var r = this.root[name].apply(this.root, arguments);
	      return r instanceof Cursor ? this : r;
	    }
store.apply
undefined
store.chain
undefined
store.push
undefined
store.unshift
undefined
store.splice
undefined
store.merge
undefined
store.unset
baobab.js:62 function () {
	      var r = this.root[name].apply(this.root, arguments);
```

**Comment by Yomguithereal** [comment]
You are right, I only give some methods from the root cursor to the tree. The concerned line is [this](https://github.com/Yomguithereal/baobab/blob/master/src/baobab.js#L68) one if you want to fiddle something for a PR. I won't be able to update the code before at least tomorrow.

**Comment by Yomguithereal** [comment]
The issue should be fixed as per last commit @serjout. Could you please verify?
