### ISSUE TITLE
Unsetting/Splicing Items of Arrays

### ISSUE THREAD

**Issue by luniki** [Yomguithereal/baobab#236]
I am experimenting with Baobab using the example at https://github.com/Yomguithereal/baobab#polymorphisms

One of the things did not work the way I was expecting: Removing an item of an array seems to be quite tedious:

```
var Baobab = require("baobab");

var tree = new Baobab({
  palette: {
    name: 'fancy',
    colors: ['blue', 'yellow', 'green'],
    currentColor: 1,
    items: [{id: 'one', value: 'Hey'}, {id: 'two', value: 'Ho'}]
  }
},
{
    asynchronous: false
});

removeItemById("one");
console.log(tree.get("palette", "items"));

function removeItemById(id) {
  var itemsCursor = tree.select("palette", "items");
  var item = itemsCursor.get({ id: id });
  itemsCursor.splice([itemsCursor.get().indexOf(item), 1]);
}
```

Is this the recommended and idiomatic way to remove array items by id?

**Comment by Yomguithereal** [comment]
Hello @luniki,
I am currently considering a `splice` polymorphism enabling you to pass a function as index so you can do this kind of thing more comfortably.

**Comment by Yomguithereal** [comment]
Unset should now work with arrays. As for the splice polymorphism: #352.
