### ISSUE TITLE
Actual working examples would speed adoption

### ISSUE THREAD

**Issue by chasm** [Yomguithereal/baobab#237]
I'm following the examples in the README and they aren't working for me. Piecemeal examples are almost worthless -- they presume too much. Nothing beats a real working example, especially if the code is elegant, clean, and commented with explanations.

I'd be happy to help, but first I have to get something working!

**Comment by Yomguithereal** [comment]
Hello @chasm. Could you please indicate the examples not working so I can start by fixing those please?

**Comment by chasm** [comment]
Sorry if I was unclear. I did not mean that the current examples do not work. I meant that they are incomplete. They show only the Baobab code removed from context. This means that the user has to spend time figuring out how this code fits into her other code, and what it will work with.

The more full, working examples (and the less fake they are), the better. At least one would be nice -- say in a baobab-example repo. But one for each style would be great. I would put the priority on ES6 as I think most people who've come this far this early are probably using Babel, but ES5 examples would be nice as well.

For example, I copied the decorator examples word for word into my code and they simply didn't work. I doubt the examples are wrong -- something else was missing in my code.

I'm desperately behind on some work (thanks in part to lack of good examples everywhere, not just here), but I will try to put together something by next week. An example of an example. Heh . . .

**Comment by gersongoulart** [comment]
+1. Struggling to understand how to use Baobab with react. Examples in `baobab-react`'s README.md file are incomplete and removed from context. I'm currently trying to figure out a way how to watch one project in an array of projects by id, the closest README.md gives me is as such:

```
Those mappings can be defined likewise:

**Using paths**

var mapping = {
  cursors: {
    name: ['user', 'name'],
    color: ['palette', 'colors', 1]
  }
};
```

I've been knocking my head on the wall trying to get that but not getting anywhere. Basically I'd like to do something along the lines of:

```js
var ProjectItem = React.createClass({

	// ...

	cursors: function (props, context) {
		return {
			headers: ['views', 'projects', 'headers'],
			selection: ['selections', 'projects', { id: props.project.id }],
			pendingUpdates: ['pendingUpdates', 'projects', { id: props.project.id }]
		};
	},

	// ...

});
```

Which of course does not work, and I have no idea of how to do something of similar effect.

Reading through Baobab's code doesn't help much with the understanding as the project is split between baobab and react-baobab and the code have minimum amount of comments.

I'd love to help further improve the documentation but before I can do so I need to better understand the project, and that is very hard to do with the current documentation and code base. :(

**Comment by ivan-kleshnin** [comment]
@chasm [this](https://github.com/Yomguithereal/baobab/issues/262) should help

**Comment by AutoSponge** [comment]
I'd be happy to work up one of my examples but, to be honest, it seems most people here use React. I don't. I'm using virtual-dom or paperclip.js. If you want to see an example that doesn't use React, let me know. Otherwise, I'll keep going alone :)

**Comment by chasm** [comment]
Oh, I'm looking closely at virtual-dom and Cycle.js, which is lovely and just went 1.0. Happy to see such examples. The React part is almost irrelevant.

**Comment by Yomguithereal** [comment]
I'd love to see non-React examples. After all, the aim of this library was to remain unopinionated and usable as a modular brick elsewhere. Personally, I use dekujs with it lately as I grew tired of React's sheer amount of verbosity for tiny projects.
