### ISSUE TITLE
Bug with facets

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#239]
I discovered a bug with facets. They should calculate synchronously when `syncwrite` is true, right?
Otherwise there is a little meaning in them. But there should be some bug causing infinite loop in my case.

1) I set URL params in `app.js ` like this:
```js
// Update URL primary state
urlCursor.set("handler", handler);
urlCursor.set("route", url.routes.slice(-1)[0].name);
urlCursor.set("params", params);
urlCursor.set("query", query); // <-- !!!
```

2) I have a facet which recalculates whenever url query changes
```js
facets: {
  urlQuery: {
    cursors: {
      query: ["url", "query"], // <-- !!!
    },

    get: function (data) {
      ...

      return {
        filters: cleanedQuery.filters,
        sorts: cleanedQuery.sorts,
        offset: cleanedQuery.offset,
        limit: cleanedQuery.limit,
      };
    }
  },
```

3) I have a code which uses this facet
```js
export default function establishIndex() {
  console.debug("establishIndex");

  let urlCursor = state.select("url");
  let urlQuery = state.facets.urlQuery.get(); // <-- !!!

  ...
  setIndexOffset(urlQuery.offset); // this is just wrapped cursor.set("offset", newOffset);
  ...

  loadIndex();
}
```

4) I have a code which falls into an infinite loop because facet isn't properly recalculated
```js
export default function loadIndex() {
  ...
  let offset = cursor.get("offset"); // <-- !!! offset is not updated here because facet still return old data somehow
  ...

  if (total) {
    let maxOffset = getMaxOffset(total, limit);
    if (offset > maxOffset) {
      indexRouter.transitionTo(undefined, {offset: maxOffset}); // <-- !!! this causes infinite loop
    } else {
      if (!isCacheAvailable(total, offset, limit, pagination)) {
        fetchIndex(filters, sorts, offset, limit, models, pagination);
      }
    }
  } else {
    fetchIndex(filters, sorts, offset, limit, models, pagination)
      .then(() => {
        let newTotal = cursor.get("total");
        if (newTotal) {
          let maxOffset = getMaxOffset(newTotal, limit);
          if (offset > maxOffset) {
            indexRouter.transitionTo(undefined, {offset: maxOffset});
          }
        }
      });
  }
}
```

The code above works ok when I debug, but falls into infinite redirect loop at normal runs which IMO proves there is some async stuff going wrong with facets.

**Comment by ivan-kleshnin** [comment]
I understand that my example is rather hard to get

Link for possible playground and more context: 
https://github.com/Paqmind/react-ultimate/blob/master/frontend/scripts/actions/load-index/robot.js#L25

**Comment by Yomguithereal** [comment]
Hello @ivan-kleshnin, I need some time to investigate this. But my first guess would be that the facets does not update in a `syncwrite` and only on the tree's async update.

**Comment by scabbiaza** [comment]
Facets are very helpful, without them my code was much more messy. Thank you for that, @Yomguithereal. 

I want to support that issue, because I had similar errors. And yes, the error doesn't show up all the time, but in some cases.

**Comment by Yomguithereal** [comment]
@scabbiaza, I assume you are using the `syncwrite` mode? Just checking to see where I should investigate.

**Comment by ivan-kleshnin** [comment]
> @scabbiaza, I assume you are using the syncwrite mode? Just checking to see where I should investigate.

Yes, she does.

**Comment by Yomguithereal** [comment]
Well I do prefer this case than the contrary :).

**Comment by ivan-kleshnin** [comment]
[This](https://github.com/Yomguithereal/baobab/issues/264) is probably the same bug.
I'm going to verify V2 updated Baobab-React release.

**Comment by Yomguithereal** [comment]
I guess this is now closed for v2.

**Comment by ivan-kleshnin** [comment]
Fixed since `1.1.2`. 
Can't check V2 without updated **Baobab-React**, but I guess it should be ok.

**Comment by Yomguithereal** [comment]
There is and updated `baobab-react@dev` already if you want to make some tests.

**Comment by Yomguithereal** [comment]
Linked to Yomguithereal/baobab-react#66.
