### ISSUE TITLE
selectById

### ISSUE THREAD

**Issue by vjpr** [Yomguithereal/baobab#241]
Is there a way to search the tree for an id?

E.g. Say you have a tree and want to re-order an element to anywhere else in the tree. After updating the database I need to delete it from its current place, then move it to its new place.

**Comment by Yomguithereal** [comment]
Hello @vjpr. Sorry for not noticing this issue faster. I am not sure whether I answer this question somewhere else but you can use functions and descriptive objects to select specific items in arrays stored in the tree:

```js
var tree = new Baobab({
  users: [
    {id: 0, name: 'Jack'},
    {id: 1, name: 'John'}
  ]
});

// Using a function
var jackCursor = tree.select('users', function(u) { return u.id === 0; });

// Using a descriptive object
var johnCursor = tree.select('users', {id: 1});
```

This is also true for the `get` function.

**Comment by vjpr** [comment]
How about moving `anchor1` to `floor2` below?
I think it gets unneccessarily complex.
An advantage of baobab is being able to have deeply nested trees and using cursors to focus on one part of it. But its really verbose to manipulate trees. I think 4 levels of nesting is not so uncommon.

Maybe something like https://github.com/dchester/jsonpath would help?

```
buildings
- building1
-- floors
--- floor1
---- anchors
----- anchor1
- building2
-- floors
--- floor2
---- anchors
----- anchor2
```

**Comment by Yomguithereal** [comment]
Let me check that. I'll also check how functional zippers work according to moving nodes.

**Comment by bard** [comment]
+1 for a method to search a node through the whole tree. Consider for example visualizing a tree with a clickable treemap: it would be nice to click a square and easily retrieve the matching node in the click handler with something like `tree.find({id: event.target.id})`.

**Comment by Yomguithereal** [comment]
Actually @bard you can already use something of the kind by using descriptor objects in an array:

```js
tree.select('array', {id: myId});
```

Do you suggest something that would search the whole tree?

**Comment by bard** [comment]
@Yomguithereal yes, exactly, something like locate or `find -name 'foobar'`.

**Comment by Yomguithereal** [comment]
Ok. Let me consider adding something of the kind in `v2` then.

**Comment by bard** [comment]
Fantastic, thanks!
