### ISSUE TITLE
How to easily move a node in a tree

### ISSUE THREAD

**Issue by vjpr** [Yomguithereal/baobab#242]
My schema looks like this:

```
buildings:
  id: building1
  floors: [
    id: floor1, anchors: [ {id: anchor1} ]
  ]
```

In my backend an `anchor` belongs to 1 or 0 `floor`s.

I want to move an `anchor` to another `floor` of another `building`, or remove it from a building.

At the moment its overly verbose and complex. I think its a pretty common use case though.

Here is the code I use to move it:

```
  moveMarker({model, building, floor, position}) {

    const opts = {building, floor, position}

    return axios.patch('/api/anchors/' + model.id, opts).then(({data, status}) => {

      tree.commit()

      /////////////////////////////////
      // Remove from previous floor
      /////////////////////////////////

      // Find existing anchor.
      // NOTE(vjpr): Until we commit the tree we don't know if this is accurate.
      let existingAnchor = jspath.apply(`..anchors{.id === "${model.id}"}[0]`, tree.data.buildings)

      // Make Baobab path to existing anchor.
      let existingAnchorPath = [
        'buildings',
        existingAnchor.buildingId,
        'floors',
        {id: existingAnchor.floorId},
        'anchors'
      ]

      const existingAnchorParentCursor = tree.select(existingAnchorPath)
      let arr = existingAnchorParentCursor.get()
      arr = _(arr).filter(x => x.id !== existingAnchor.id)
      existingAnchorParentCursor.set(arr)
      console.log({arr})

      /////////////////////////////////
      // Add to dest floor
      /////////////////////////////////

      if (data.floorId) {

        // Make Baobab path to new floor.
        let destFloorAnchorsPath = [
          'buildings',
          existingAnchor.buildingId,
          'floors',
          {id: data.floorId},
          'anchors',
        ]

        // Move to new floor.
        const destFloorCursor = tree.select(destFloorAnchorsPath)
        destFloorCursor.update({$push: data})

      }

      tree.commit()

      /////////////////////////////////

    }).catch(res => {

      console.error(res)
      //tree.set(path, {id, $error: res.data})

    })

  }

}
```

Is there a better way to do this without changing the schema?

Is there a schema that would work better - like keeping a separate collection of `anchors`.

**Comment by Yomguithereal** [comment]
Hello @vjpr,
I need some time to read your example but I am wondering whether your use case would be simpler out of Baobab: what I mean here is: would your data manipulation here as complex outside of Baobab's structure? I am trying to assess whether we are trying to find sugar here or to solve a data manipulation problem.

**Comment by vjpr** [comment]
I think this use case is quite common and could be generalised to "how to manipulate lists of lists", or "how to reproduce Trello's data model" in Baobab.

It would be really cool to have a Trello-like example for Baobab (in React) which would probably unearth a lot of these use cases.
