### ISSUE TITLE
Facet question

### ISSUE THREAD

**Issue by kevbook** [Yomguithereal/baobab#243]
So I have a question, lets say my facet is below. I want to control if the facet update is fired. Is there a way to do that?

```  
facetA: {
    cursors: {
      layout: ['layout'],
      layout2: ['layout2']
    },
    get: function(state) {
      
       // Can I do something where the facet update event is not fired?
       if (state.layout === false) return false;

      // Perform like usual
       else return { updateData: true };
    }
  }
```

**Comment by Yomguithereal** [comment]
Hello @kevbook,
I am not sure I understand what you are trying to achieve here. Could you explain your use case a bit more?  Why do you need to know whether the facet fired in its getter?

**Comment by sheerun** [comment]
I think he wants something like `shouldComponentUpdate` for facets.

**Comment by Yomguithereal** [comment]
It seems like it indeed @sheerun.
