### ISSUE TITLE
Cerebral as a signalling  addon

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#244]
Hi @Yomguithereal,

I have been working on a project called Cerebral, https://github.com/christianalfoni/cerebral, and a demo here gives you a good impression, http://www.christianalfoni.com/todomvc/. I wrote an article and got a comment about why not use Baobab as the state storage. I initially chose to run with my own immutable-store because there were lots of implementation details I was not sure of. But now that everything is clear to me I am strongly considering making Cerebral work with Baobab.

But I have a question I wanted to ask you:

With Cerebral requestAnimation frame is used on the signal input and everything after that is synchronous, except when "remembering" where everything is synchronous. Is it possible now, with Baobab options, to allow Cerebral to make multiple updates to the tree, then commmit and trigger the "update" events synchronously too? React will batch up all the "setState" so it should not matter if it runs sync or async

If this is currently not possible, but could be with an option I would gladly work on making Cerebral work with Baobab :-)

So specifically this is what I need:

1. When a mutation is done to the tree it is batched until "tree.commit()" is run
2. When the "tree.commit()" is run the update events are triggered synchronously

Thanks!

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, the behavior you describe should be the one currently used by Baobab when not using `syncwrite`. Updates are batched until next frame or next user explicit commit. Then, when you commit the events are run synchronously. You can toggle off the `autoCommit` option if you want to remain the only master of when the tree should commit.

So is that a limit to the `syncwrite` behavior you found there, by the way?

I hope I understood you question correctly :-).

**Comment by christianalfoni** [comment]
HI @Yomguithereal , ah, okay, good. That is what I need :-)

I got a bit too excited when I created this issue. After some more thought I see some challenges in making Cerebral compatible with Baobab. That said, Baobab could definitely have a separate implementation in front of it which gives the same features as Cerebral. The project is currently in its infant stage, but growing fast, so when it reaches a hopefully stable version I would be glad to create something similar working with Baobab... for now it can just be an example of what is possible to do when you store your state like you do with Baobab :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni,
could you precise which are the issues that prevent you from making them compatible please?

**Comment by christianalfoni** [comment]
Hi again,

The signals and store implementation of Cerebral was not very clear to me when I started, so they are just a bit too intertwined now. I have to rethink some implementations and make them completely independent of each other. So its a matter of structure really.
