### ISSUE TITLE
Clarify "incorrect facets mapping" error

### ISSUE THREAD

**Issue by hanbzu** [Yomguithereal/baobab#254]
Using Baobab I have found that it's quite frequent to run into the "incorrect facets mapping" error:

      baobab.Facet: incorrect facets mapping.   facet.js:47

While it's clear I have some typo somewhere or I failed to require something, wouldn't it be a good idea to explain this error a little bit?

I mean, explaining at what point Baobab checks for that and where to trace the error.

**Comment by hanbzu** [comment]
This time I found it was due to using ['facetName'] instead of 'facetName'. I think it's easy to run into this because of the facets API. But I'll close this since its covered in issue #195

**Comment by Yomguithereal** [comment]
Nonetheless, a more helpful error message wouldn't hurt :).
