### ISSUE TITLE
Question about array mutation and React shouldComponentUpdate

### ISSUE THREAD

**Issue by kevbook** [Yomguithereal/baobab#255]
A common use case for using this library is with React and pureRenderMixin. So lets say I have a data array.
```js 
var data = [
{ id: 1, someKey: 'abc' },
{ id: 2, someKey: 'abc' },
{ id: 3, someKey: 'abc' },
];
curset.set('data', data);
```

And now i want to add selected to id: 2, so that the new state of data becomes
```js
{ id: 1, someKey: 'abc' },
{ id: 2, someKey: 'abc', selected: true },
{ id: 3, someKey: 'abc' },
];
```
How can I do this, in a way that each `{ id: 1, someKey: 'abc' }` is a React Component, that checks for shouldComponentUpdate , and component 1 and 3 should not be updated.

**Comment by Yomguithereal** [comment]
Hello @kevbook: if you use the PureRenderMixin, then only the second component will update since 1 and 3's references won't be altered.

**Comment by kevbook** [comment]
Sorry for not being clear, my question is in baobab, how can I update the data array to only update the the 2nd item?

**Comment by Yomguithereal** [comment]
Ok, let's assume you have a cursor selecting your array in the tree, here is what you can do:

```js
// If you know the index
cursor.set(['2', 'selected'], true);

// If you don't know the index
cursor.set([{id: 2}, 'selected'], true);

// Or
cursor.set([function(e) {return e.id === 2}, 'selected'], true);
```

**Comment by kevbook** [comment]
Thank you.
