### ISSUE TITLE
unset shouldn't creates path (if they absent)

### ISSUE THREAD

**Issue by ostinru** [Yomguithereal/baobab#260]
I am not sure, but I expect that Baobab will not create empty objects in unset() and update()+$unset

code:
```
      it('shouldn\'t crate paths.', function() {
        var tree = new Baobab({one: {} }, {asynchronous: false}),
            cursor = tree.select('one');

        assert.deepEqual(cursor.get(), {});
        cursor.unset(['a', 'b', 'c']);
        assert.strictEqual(cursor.get(), {});
      });
```

Expected reuslt: {}
Actual result: {a:{b:{}}}

**Comment by Yomguithereal** [comment]
Hello @ostinru.
This is definitely a bug. Unfortunately it is not that easy to fix. I have to reflect on that to find a painless way to fix it.

**Comment by Yomguithereal** [comment]
This issue is now fixed in v2.
