### ISSUE TITLE
Can validation be run on tree creation?

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#263]
Hey @Yomguithereal, 

Quick question:

Can the validation function we specify be run on the baobab tree upon its creation? Right now it looks to me like it isn't being run until something is updated within the tree, but I think it would be nice to be able to have the validation be done on the initial creation as well to make sure the data you're instantiating the tree with is all valid. 

Also, +1 to the ideas voiced in #56 of (1) having some sort of shortcut to validate just specific parts of the tree and (2) having a way for the validation function to determine what happens when invalid data is encountered.

Thanks a bunch!

**Comment by Yomguithereal** [comment]
Hello @tnrich,
for the moment the tree does not validate initial data but it seems you are right and this should normally be done.

For a temporary workaround, you can do the following:

```js
// rather than
var tree = new Baobab(initialData);
// do
var tree = new Baobab();
tree.set(initialData);
```

Concerning (1), for the time being, the validation function is passed the affected paths in the tree so you can fiddle something concerning validation of only some parts.

You would like (2) to be able to choose "à la carte" what happens for validated data?

**Comment by tnrich** [comment]
Hey @Yomguithereal,

Thanks for the temporary workaround!

An idea I had that could be pretty nice, would be to have the validation function looks a bit more like this:
```
var tree = new Baobab({
	palette: {
		colors: ['yellow', 'purple'],
		name: 'Glorious colors'
	}
}, {
	validate: {
		palette: {
			_baobabValidate: function(previousState, newState) {
				if (!newState) {
					return {
						newValue: {
							colors: [],
							name: 'Thomas'
						}
					};
				}
			},
			colors: {
				_baobabValidate: function(previousState, newState) {
					if (!newState) {
						return {
							newValue: []
						};
					}
				},
			},
			name: {
				_baobabValidate: function(previousState, newState) {
					if (name !== 'Thomas') {
						return {
							newValue: 'Thomas'
						};
					}
				},
			}
		}
	}
});
```
It's maybe a little verbose right now, but I like having the ability to arbitrarily validate any node in the tree and return a new value that can be used for it. 

What do you think about that?

**Comment by Aetet** [comment]
I think baobab tree is not best place for validation. Because in baobab tree we does not write business logic. We just describe what data we have and how we can get it, no more. I think validation must be in widgets, which know what data is suitable for them and which is not. And in actions, because they know how to update specific parts of baobab tree.

**Comment by Yomguithereal** [comment]
@tnrich: I am currently trying to fix that but I find myself having a problem: should I throw when initial data is invalid whereas normally it would emit an event (but since you cannot listen to that event before instantiating it would be moot to validate the tree).

**Comment by Yomguithereal** [comment]
Validation now runs on instantiation.
