### ISSUE TITLE
Facet update not triggered when "child" facet updated

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#264]
Hey @Yomguithereal, 

I am having an issue with one of my facets not being updated even when another facet it should be listening to is updated.

For example, say I have this tree:
```
facets: {
     rowData: {
			cursors: {
				sequenceData: ['vectorEditorState', 'sequenceData'],
			},
			facets: {
				bpsPerRow: 'bpsPerRow',
			},
			get: function(state) {
				return prepareRowData(state.sequenceData, state.bpsPerRow);
			}
		},
		visibleRowsData: {
			cursors: {
				visibleRows: ['vectorEditorState', 'visibleRows']
			},
			facets: {
				rowData: 'rowData'
			},
			get: function(state) {
					//do something
			}
		}
}
```

When the rowData facet is updated, I want the visibleRowsData facet to be updated as well, but visibleRowsData isn't updating. Is there something I'm missing about this? I was reading in #240 about facets updating "lazily". Does this have something to do with that? 

Thanks!

**Comment by Yomguithereal** [comment]
Hello @tnrich,
Are you using the `syncwrite` mode? For the time being, facets won't be reloaded until next frame.

One workaround would be to use `tree.commit` to force the tree to write changes.

**Comment by tnrich** [comment]
Hey @Yomguithereal , yes, I'm using syncwrite mode. I am calling tree.commit() after setting the new state. However, the parent facet still doesn't seem to be updated even though the child facet it is listening to is being updated. Any thoughts?

**Comment by tnrich** [comment]
I also tried to call tree.commit after the child facet is updated, but that doesn't seem to work either:

```
    rowData: {
			cursors: {
				sequenceData: ['vectorEditorState', 'sequenceData'],
			},
			facets: {
				bpsPerRow: 'bpsPerRow',
			},
			get: function(state) {
				var self = this;
				setTimeout(function (argument) {
					self.tree.commit();
				}, 10);
				return prepareRowData(state.sequenceData, state.bpsPerRow);
			}
		},
```

**Comment by tnrich** [comment]
hey @Yomguithereal, any thoughts on solving this issue? would a runnable example of the code in question help?

**Comment by Yomguithereal** [comment]
An option would be to update data at a cursor you are listening in the second facet (with the same value so it will trigger an event anyway) and see whether it can change something. I need to work on this bug.
