### ISSUE TITLE
Using "once" in combination with "off" fires constantly

### ISSUE THREAD

**Issue by ayalpani** [Yomguithereal/baobab#267]
Hi,

thanks a lot for Baobab, we have successfully planted it deep inside our applications core. Unfortunately we are facing a bug which turns out to be a serious show stopper for us, blocking important further work. Actually, it isn't a bug in Baobab itself but in the Emmet dependency, so I have already filed a bug report (and a test spec to  be fulfilled) there too:

https://github.com/jacomyal/emmett/issues/20

With this issue, I wanted to raise attention to this problem, as you are also contributing to emmet.
Best,
Arash

**Comment by Yomguithereal** [comment]
Hello @ayalpani, I think @jacomyal is checking this issue right now. I'll upgrade Baobab's deps as soon as the emitter is fixed.

**Comment by Yomguithereal** [comment]
Bug is now fixed on `emmett`. Will update Baobab's deps soon and release v1.1.1

**Comment by ayalpani** [comment]
Thanks so much @Yomguitherea l!!

**Comment by Yomguithereal** [comment]
Hello @ayalpani. I just published v1.1.1 so this issue should be fixed now.

**Comment by ayalpani** [comment]
Many thanks @Yomguithereal , I will try it out!
