### ISSUE TITLE
Some ideas about fasets

### ISSUE THREAD

**Issue by zerkalica** [Yomguithereal/baobab#269]
My experiments with dependency injection pattern: https://github.com/zerkalica/immutable-di
It's like baobab, but not so powerfull.
I think, baobab or nuclear-js are some specific realizations of di pattern and i try to find most common solution for state hanling and dependency resolve.

1. No singletones, di container can resolve deps, create instances, handle state, subsribes listeners and creates cursors
2. Add some static info for di on script load for functions, classes, react components and etc
3. On load stage calculate which state paths our dependencies use, build map: dependencyId => [state paths]
4. Recursively resolve deps
5. Lightweight and separate cursor class - adapter pattern, we can provide any data-manipulation library: native objects, immutable-js, etc
6. Each dependency instance puts to di-container cache after first resolve
7. After state update, clear cache only for deps, which paths has been affected
8. Use sub/pub for di-compatible listeners, after state update get all registered listeners from container, listeners which depends on affected state paths will be executed.

example:
```js
const container = new Container(new NativeCursor({
    config: {
        logger: {
            opt1: 'test1'
        }
    }
}))

function ConsoleOutputDriver() {
    return function consoleOutputDriver(str) {
        console.log(str)
    }
}
Factory()(ConsoleOutputDriver)

@Class([
    ConsoleOutputDriver,
    ['config', 'logger']
])
class Logger {
    constructor(outputDriver, dep, config) {
        this._outputDriver = outputDriver
        this._config = config
    }
    log(val) {
        this._outputDriver('val:' + val + ', opt:' + this._config.opt1)
    }
}

container.get(Logger).log('test')
```

**Comment by Aetet** [comment]
And I think facets must have opportunity to return function for passing user arguments. It's very handy when we have nested structure and nested field can have computed values. like this:
```js
var tree = new Baobab({
  cells: [{
     cards: [{id: 1, title: 'first'}, {id: 2, title: 'second'}],
     colCount: 1
     // rowCount must be here, but it is computable. 
     // Based on cards.length and colCount
  }]
});
```
```js
rowCount: {
cursors: {
   cells: ['cells']
},
get: function(cells) {
   return function (id) {
     let cell = cells[id];
     let colCount = cell.colCount
     return cell.cards.length / colCount;
  }
}
}
```
And in widget we can do something like:
```js
class A extends React.component{
  render() {
     let {cells} = this.props;
     let cellViews = cells.map(cell => <Cell rowCount={rowCount(cell.id)} />)
  }
}
branch(A, {
  cursors: {
     cells: ['cells']
  },
  facets: {
     rowCount: 'rowCount'
  }
  
})
```

So what's the best way to do that?

**Comment by Yomguithereal** [comment]
Hello @zerkalica, you might be interested by the discussions going on #240 concerning the evolutions of the facets and dependencies.
