### ISSUE TITLE
Request for a nonminified version of code under build/baobab.js

### ISSUE THREAD

**Issue by davidcalhoun** [Yomguithereal/baobab#270]
Would be really handy to have a rollup in the code under build/baobab.js, which would be nicer for developing.

Thanks!

**Comment by Yomguithereal** [comment]
Hello @davidcalhoun. Would a script building a concatenated version of the files in the `package.json` be enough for your needs? The only reason why I have a `build` file stocked in the repository is bower and I would like not to multiply build files since it messes with versionning.

**Comment by davidcalhoun** [comment]
That would definitely be helpful.  For now I just uncommented the Uglify step in the Gulp file and tweaked the output to baobab.js instead of baobab.min.js.

Just trying to get this imported into my company's "third party" repo, so the less steps we have to do each time Baobab needs to get updated, the better.  :)

**Comment by Yomguithereal** [comment]
@davidcalhoun: as per last commit, `npm run build` or `gulp build` will produce a concatenated version alongside the minified one.

**Comment by davidcalhoun** [comment]
Awesome, that works.  Thanks!
