### ISSUE TITLE
using baobab with JSPM

### ISSUE THREAD

**Issue by AutoSponge** [Yomguithereal/baobab#272]
When using with JSPM, you have to point the config.js file to the built file `"baobab": "github:Yomguithereal/baobab@1.1.1/build/baobab.min",` because the source files use `require(*.js)` which causes SystemJS to interpret `*.js.js` and fails to find any files.

**Comment by Yomguithereal** [comment]
Hello @AutoSponge. Why would SystemJS work like this whereas every other module system works differently? A lot of people (I would say a vast majority) use `.js` in the required path. I personally use this to discriminate what is loaded from the exterior of the module and what is internal and relative (even if, yes, the `./` is pretty self explanatory).

Let me document myself about JSPM and such to see what can be done.

**Comment by Yomguithereal** [comment]
Does that work differently with `"baobab": "npm:baobab@1.1.1"`?

**Comment by AutoSponge** [comment]
I'm looking here: http://wiki.commonjs.org/wiki/Modules/1.1#Module_Identifiers

~3 = Module identifiers may not have file-name extensions like ".js".

What you're using is ignore by node but more specific implementations, like SystemJS will bomb.

Right now I'm using the compiled version because it doesn't expose deps so I don't have any issues. All of your files use this syntax, so until it's fixed, you can't directly use this lib with JSPM or SystemJS.

**Comment by Yomguithereal** [comment]
I'll probably need to fix my requires then not to include the `.js`. Do you happen to know the reasons why they choose to drop the `.js` on ES6 modules? This sounds a little bit crazy to me.

**Comment by Yomguithereal** [comment]
I am currently writing v2. I will drop the `.js` in it so nobody is left behind.

**Comment by Yomguithereal** [comment]
Done in v2.

**Comment by myitcv** [comment]
Just to add that in my experience with `jspm` version `0.16.0-beta.3` (which uses `SystemJS` version `0.17`) things work out of the box

```
jspm install npm:baobab
```
