### ISSUE TITLE
immutable option prevents multiple updates

### ISSUE THREAD

**Issue by idris** [Yomguithereal/baobab#273]
When using `immutable: true`, making multiple updates to the tree in the same call stack does not work.  JSBin demo here: https://jsbin.com/pobitepopu/1/edit?html,js,output

You'll notice that in the JSBin, `moo` is never set.  However, if you set `immutable: false` everything works fine.  Other ways to solve it include setting `asynchronous: false` or `syncwrite: true`.

**Comment by Yomguithereal** [comment]
Hello @idris. This looks like a bug indeed. Let me check if I can fix this on v1 before v2.

**Comment by Yomguithereal** [comment]
Hello @idris. This should not be a problem anymore for v2.
