### ISSUE TITLE
Easily convert between immutable and non-immutable data

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#276]
Hey @Yomguithereal, I've switched over to use the immutable:true option and am liking it for the most part. One thing I find myself doing a lot is calling:
```
var myMutableObject = Object.assign({},tree.select('path', 'to','my','immutable-object').get());
myMutableObject = manipulateObjectInSeveralWays(myMutableObject, outsideData);
tree.select('path', 'to','my','immutable-object').set(myMutableObject);
```

I was wondering how difficult it would be to implement something like @christianalfoni 's .toJS method that he has in cerebral:
let todo = cerebral.get('todos', 0);
todo.title; // "foo"
todo.title = 'bar';
todo.title; // "foo"
let copy = todo.toJS();
copy.title = 'bar';
copy.title; // "bar"

I think it would be a nice built in convenience that would save having to use Object.assign() calls all the time and maybe could be optimized to work with the Object.freeze method you've used to implement the immutability stuff (just a thought).

Thanks a bunch! I'm looking forward to v2!

**Comment by Yomguithereal** [comment]
Hello @tnrich. There is no other method than cloning to unfreeze an object. So yes, I could expose the library's cloning methods or else. 

However, the library's setters are optimized to work with frozen trees etc so, when possible and if you want best performance, you should use the lib setters. Your example, for instance, could be simplified by creating a cursor.

Now also that in v2, the tree will always be in syncwrite mode and that setters will return the affected node so you can work comfortably with immutable data.

**Comment by Yomguithereal** [comment]
Any news about this @tnrich?

**Comment by tnrich** [comment]
No news. I still think it would be nice to have a tree.get().unfreeze() method. Doesn't necessarily have to be that syntax, but something like that.

**Comment by tnrich** [comment]
Hey @Yomguithereal , I'm wondering if it's an anti-pattern to have moneky's modify the data that is getting passed to them. Here's my issue: 

Right now my app takes in a sequenceData object that contains a bunch of info about the sequence such as annotations, the sequence itself, and other meta data. I then add to that sequenceData object various other properties based on the initial data it contains. Here's a simplified example:

tree = {
	sequenceData: {
		sequence: 'atg',
		features: [{
			name: feature1,
			start: 1
			end: 2
		}]
	},
	specialAnnotation: Monkey([
		['sequenceData', 'sequence'],
		function(sequence) {
			return checkContainsSpecialAnnotation(sequence) ? {
				name: 'specialAnnotation'
			} : null
		}
	]),
	combinedSequenceData: Monkey([
		['sequenceData'],
		['specialAnnotation'],
		function(sequenceData) {
			var clonedSeqData = JSON.parse(JSON.stringify(sequenceData.specialAnnotation))
			clonedSeqData.specialAnnotation = specialAnnotation;
			return sequenceData
		}
	]),
}

The JSON.parse(JSON.stringify()) seems like it could get somewhat costly with large sequenceData objects. 

Is there a better way to do this? I am using Cerebral and Baobab together now so need to have baobab be immutable. Should I just call a sequenceData.set() call from within the Monkey? Your thoughts would be appreciated. Thanks!

**Comment by Yomguithereal** [comment]
Monkeys should remain pure and do not produce side effects. So yes, setting data in the tree from a monkey is an anti-pattern. But then, your use case is different: you need more information on an already existing list. You have two solutions there:

1. the one you use, i.e. to have a monkey returned a "completed" version of your data.
2. Set the complementary information on the data itself once and for all when you write them.

I don't know exactly your use case so I cannot choose for you but indeed, modifying immutable data requires some amount of cloning anyway. The thing is the `JSON.parse` trick is deep and cannot perform those cloning operations in an optimal way. You should probably use shallow cloning helpers such as lodash's one for instance. And, if you are not afraid of ES6/7, there are some sweet ways to perform what you want with JS's new syntax elements (notably the "object rest spread"):

```js
// Example:
var o1 = {one: 1};
var o2 = {...o1, two: 2};
>>> {one: 1, two: 2}
>>> o1 !== o2
```

**Comment by tnrich** [comment]
Hey @Yomguithereal thanks for the response. My use case gets a little more complicated. I was actually already using lodash's assign to make the above more reasonable. The real challenge comes after the above, when I want to set more derived properties on the sequence data's annotations themselves:  

```js
tree = {
	sequenceData: {
		sequence: 'atg',
		features: [{
			name: feature1,
			start: 1
			end: 2
		}]
	},
	specialAnnotation: Monkey([
		['sequenceData', 'sequence'],
		function(sequence) {
			return checkContainsSpecialAnnotation(sequence) ? {
				name: 'specialAnnotation'
			} : null
		}
	]),
	combinedSequenceData: Monkey([
		['sequenceData'],
		['specialAnnotation'],
		function(sequenceData, specialAnnotation) {
			var clonedSeqData = lodash.assign({}, sequenceData, {specialAnnotation: specialAnnotation})
			return sequenceData
		}
	]),
	computedSequenceDataWithAnnotationOffsets: Monkey([
		['combinedSequenceData'],
		function(sequenceData) {
// here I want to calculate the y offsets for the annotations and set them on the annotation 
// itself if possible, but it doesn't seem feasible to do that without some 
// sort of deep cloning of the original sequence data. Any thoughts on doing that? 
			sequenceData.features.forEach(function(annotation){
				annotation.set('yOffset',calculateOffsetOfAnnotation(annotation))
			});
			sequenceData.specialAnnotations.forEach(function(annotation){
				annotation.set('yOffset',calculateOffsetOfAnnotation(annotation))
			});
			return sequenceData
		}
	]),
}
```

It seems like I can either do a somewhat expensive deep-clone, or ... do something else? Maybe I should think of a slightly better way of doing things so I only need to do a deep clone one time? 

Thanks for your thoughts! They're much appreciated.

**Comment by Yomguithereal** [comment]
You just need to map your arrays and shallow clone the relevant parts to add your information.
