### ISSUE TITLE
Is it possible to replace an item in an array?

### ISSUE THREAD

**Issue by hanbzu** [Yomguithereal/baobab#277]
I guess the way to do it is with method 'splice' but:

Let's say I want to change the content of element at index 0. I want to replace banana with cherry:

```javascript
var tree = new Baobab({
  list: ['banana', 'apple']
});

// It works!
tree.select('list').splice([0, -1, 'cherry']);
```
But if I have only one element in the array:

```javascript
var tree = new Baobab({
  list: ['banana']
});

// It does not work! I get: ['cherry', 'banana']
tree.select('list').splice([0, -1, 'cherry']);
```

It looks as if, in that case, the item is added to the beginning instead of being replaced. It's possible that I didn't get my splice parametres right but I didn't find help on that.

**Comment by Yomguithereal** [comment]
Hello @hanbzu, the simplest wa

**Comment by SaphuA** [comment]
@hanbzu @Yomguithereal I'm pretty sure that -1 should be a 1. It works on my project.

**Comment by Yomguithereal** [comment]
Need to check if my version is consistent with this behavior then.
