### ISSUE TITLE
V2 Firefox error

### ISSUE THREAD

**Issue by frontengineer** [Yomguithereal/baobab#290]
V2 baobab@dev branch instantiation failing in Firefox
ex: var tree = new Baobab({})
throws('this tree project undefined');
![screen shot 2015-07-15 at 12 13 48 pm](https://cloud.githubusercontent.com/assets/10609184/8707610/9c47ce8c-2aeb-11e5-8290-1b4ef9d6bf8c.png)

Switching to old V1 branch has no issue.  Thank you.

**Comment by Yomguithereal** [comment]
Hello @frontengineer. I have found the culprit: `Object.prototype.watch` which is implemented in Firefox ([reference](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/watch)).

I'll fix this asap and release a `2.0.0-dev7`.

**Comment by Yomguithereal** [comment]
`2.0.0-dev7` is now available through `baobab@dev`.

**Comment by frontengineer** [comment]
Cool. Thank you.

**Comment by frontengineer** [comment]
Confirmed.
