### ISSUE TITLE
[v2] ability to check if cursor is relevant

### ISSUE THREAD

**Issue by deepsweet** [Yomguithereal/baobab#291]
hi.

could you please bring back `relevant` property to cursor or `get(false)` as it was there before? I just want to know if cursor is irrelevant w/o firing `get`-event.

**Comment by Yomguithereal** [comment]
I can do that but I am unsure how exactly. I hesistate between a `relevant` property that would need to be recomputed at each update or a `isRelevant` method or something like this.

**Comment by deepsweet** [comment]
you can make `relevant` property as a lazy getter like `get relevant() { ... }` (instead of recalculating it from different places), or make it as a true method `isRelevant()` – both options are ok for me.

**Comment by deepsweet** [comment]
just make sure that it doesn't fire `get`-event :)

**Comment by Yomguithereal** [comment]
What about `tree/cursor.exists` to which you can pass a path and that would return a bool?

**Comment by deepsweet** [comment]
if you think that this approach is really necessary – ok. any way to check for relevance is good for me.

**Comment by Yomguithereal** [comment]
Ok, just released `2.0.0-dev8` with `tree/cursor.exists`.

**Comment by deepsweet** [comment]
thanks!
