### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#293]
When we subscribe on update notifications
```js
colorsCursor.on('update', function(notification) {
  console.log('Selected colors have updated:', colorsCursor.get());
});
```
I think there is a possibility that `notification.data.data` will be different from `colorsCursor.get()` as data behind `colorsCursor.get()` may be updated since then.

There is nothing specifically bad about it, but I think we should rather rely on `notification.data.data` and do not promote `colorsCursor.get()` style. What do you think?

**Comment by Yomguithereal** [comment]
You raise an interesting point here. I used not to provide the data in this event before and introduced here for convenience but I guess you are right. Moreover, this would improve performances.

**Comment by Yomguithereal** [comment]
Are you working with v2 here?

**Comment by ivan-kleshnin** [comment]
With v1. I've just started to review v2 documentation :)

**Comment by ivan-kleshnin** [comment]
Let's close older issues to not get overwhelmed.

**Comment by Yomguithereal** [comment]
The event's structure comes from the [`emmett`](https://github.com/jacomyal/emmett) library. I cannot remove this nesting under data.

Is the tree/cursor's data still relevant in the event since you proposed to drop it in favor of `.get`?

**Comment by ivan-kleshnin** [comment]
> Is the tree/cursor's data still relevant in the event since you proposed to drop it in favor of .get?

I desperately need `previousData` which can't be accessed otherwise.
I think `.get()` should be discouraged rather than event payload.

**Comment by Yomguithereal** [comment]
`previousData` obviously won't get away as this is very useful and even used internally sometimes.

Sorry, I misread the first text of your issue and was thinking you were advocating the contrary.

Let me adapt the documentation to drop the `.get`.

**Comment by Yomguithereal** [comment]
The `.get` has been dropped in the documentation example.

**Comment by ivan-kleshnin** [comment]
Great. Let's close this one, then.
