### ISSUE TITLE
Additional operators for Array data

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#295]
We have 4 operators to add data to Array

```
tree.push -- add to end (single value)
tree.concat -- add to end (from array)
tree.unshift -- add from start (single value)
tree.splice -- add [& remove] in custom place
```

and only 1 to remove data from Array

```
tree.splice -- add [& remove] in custom place
```

I think these two are logically required.

```
tree.pop -- remove from end
tree.shift -- remove from start
```

Just as about `.reverse()` question I stick to the opinion that developer himself has to decide about performance and memory issues. JS does not limit us from, say, sorting a huge array and Baobab also shouldn't.

**Comment by Yomguithereal** [comment]
I am ok with `pop` and `shift` but they ask further questions: Baobab's setters currently return the affected node's data. However, `pop` and `shift` are method that notoriously return the removed value. What should we do in Baobab's case?

**Comment by ivan-kleshnin** [comment]
I think it's pretty normal that some operations return affected data and some operations return special values like removed ones. Returned values are kind of "shortcuts", we always can fire additional commands to get more.

Maybe it's even better to name it `take` / `takeLast` and `drop` / `dropLast`?

```js
pop <=> takeLast(1)
shift <=> take(1)
```

More flexible and future proof cause we may decide to add `takeWhile`, `dropWhile` lately.

**Comment by ivan-kleshnin** [comment]
Maybe it's better to name them `drop(1)` / `dropLast(1)` and make it return affected value to keep this symmetry? Moreover it will be better future-proof naming (think of `take`, `dropWhile`, `dropRepeats` etc).
If you need to access the removed value, you should `get` it before removal.

**Comment by Yomguithereal** [comment]
In a sense this is already working like this since I forgot that splice returns the affected array, not the dropped part.

**Comment by ivan-kleshnin** [comment]
Splice signature is overcomplex. I always need to go to the documentation to recall what arguments should be there and in what order.

**Comment by Yomguithereal** [comment]
I am afraid JavaScript's standard `splice` isn't simpler.

**Comment by ivan-kleshnin** [comment]
Exactly. So `splice` is a last resort, everyone uses simplier commands whenever possible.

**Comment by Yomguithereal** [comment]
Will probably go for `drop` and `dropLast`.

**Comment by rohitlodha** [comment]
Is there any preferred way to sort an array or should I sort and replace the array in tree?

**Comment by Yomguithereal** [comment]
@rohitlodha: I guess it depends whether you think your data you hold the sorted array as itself. I yes, then sort the array before setting it and here you go. Else, I think you would rather create a monkey that would compute a sorted version of said array.

**Comment by rohitlodha** [comment]
@Yomguithereal  I was wondering if I can use the fact that array elements are immutable and reused, while its only the array that is changing. So, react DOM just reorders it nodes instead of full refresh.

**Comment by Yomguithereal** [comment]
The computed node will return the same immutable objects stored within your initial array. Only the sorted array reference should differ from the original one.

**Comment by rohitlodha** [comment]
@Yomguithereal 
Is there any way I can add to the array, if the value does not exist( keeping array with unique values).
If I get indexOf and then push will it work or there are multi-thread scenarios where it can fail? I am new to JS and find multi-threading in js very confusing.

**Comment by Yomguithereal** [comment]
Hello @rohitlodha. What you want is a kind of Set structure it seems. Your approach seems valid (keep in mind that you seem to check the existence of an element in `O(n)` rather than keeping your data in an object index that would be `O(1)`.

There is no multi-threading in JavaScript, or, at least, not in the language itself. So there are no scenarios where your operation can fail. Stacks are synchronous while their execution in time is not (yet you'll never have concurrent stacks, so you are safe).

**Comment by rohitlodha** [comment]
@Yomguithereal Its an ordered set, so I do not know if there are alternatives. Thanks for the clarification.

**Comment by Yomguithereal** [comment]
@rohitlodha ordered set can be optimally created by combining both an array and an object but it will take more memory and is a pain to implement. I guess that if you don't have too many items you are safe.

**Comment by tnrich** [comment]
@yomguithereal, any movement on this one? I'd love to use pop/push functionality. Thanks!

**Comment by Yomguithereal** [comment]
No movement yet but I guess it's not very hard to implement so I could do it quite quickly in a near future.

**Comment by Yomguithereal** [comment]
@tnrich: just added cursor.pop/shift, can you test on master and tell me whether this fits your needs please?
