### ISSUE TITLE
[v2] README review

### ISSUE THREAD

**Issue by boogheta** [Yomguithereal/baobab#297]
- [x] 1st sentence: add "through events" at the end

- [x] 2nd sentence: put "such as Clojure's ones" between parentheses

- [x] Updates/cursor level: add to the example a simple syntax of nested data to better explicit what the first nested data example does
```
// Nested path
var newData = cursor.set({one: {two: 'world'}});
```

- [ ] Give a way to easily find the list of possible events in the doc, their current formatting does not allow to spot them easily

- [x] make explicit the difference between write and update events

- [x] Advanced/polymorphisms 1st phrase: "THERE are many ways"

- [x] tree/cursor.project: not very useful to users so put at the list bottom instead of the to

- [x] tree/cursor.serialize: "avoiding computed data" is an obvious ref to facets, although for profane users it needs to be explicitely mentioned, AND moved down after facets are actually introduced

- [x] tree/cursor.exists: in the first example (`tree.exists()`), maybe add something like "obviously always true, except when having specifically set the root of the tree to undefined using `tree.set(undefined)`" for better understanding

- [x] Traversal: maybe put the root cursor part above the rest (before up)

- [x] Computed data: in the second sentence, I would keep the old analogy with facets (`as a "view" or "facet"`) that I personally find quite easier to apprehend

- [x] Computed data example: typos before the last example command: "// Just note thaT computed data node IS read-only"

- [x] History: "Baobab lets you record the SUCCESSIVE stateS"

- [x] Philosophy: Maybe explicit UIs as User-Interfaces at least in the title

**Comment by Yomguithereal** [comment]
Danke schön @boogheta.

**Comment by ivan-kleshnin** [comment]
I would also prefer to have a formalized list of available methods for each datastructure with examples rather than just examples.

Something like:

### &lt;Object&gt; Cursor

#### `.merge(key:String, a:<Object>)` 
#### `.merge(a:<Object>)`

Merges objects shallowly.

##### Example

```js
// cursor.get() = {x: "x"}
cursor.merge({y: "y"}); 
// cursor.get() = {x: "x", y: "y"}
```

**Comment by Yomguithereal** [comment]
This section of the documentation could indeed probably use more formal definitions.
