### ISSUE TITLE
Cannot read property '_computedDataIndex' of undefined

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#299]
Hey there @Yomguithereal, I've been trying to switch over to v2, and I'm running into a mysterious error that doesn't seem to be thrown every time I reload the page. I'm not quite sure what's causing this problem, but my facets don't seem to be updating quite correctly. Here's the stack trace: 

```
Uncaught TypeError: Cannot read property '_computedDataIndex' of undefined(anonymous function) 
@ cursor.js:229_getComparedPaths 
@ cursor.js:222Cursor._updateHandler 
@ cursor.js:164Emitter.emit 
@ emmett.js:445commit 
@ baobab.js:369(anonymous function) @ baobab.js:316
```

![image](https://cloud.githubusercontent.com/assets/2730609/8769530/34af9842-2e54-11e5-86fe-d17f12436b8b.png)

Any insights into this kind of issue or tips for debugging this?

**Comment by Yomguithereal** [comment]
Hello @tnrich. Would it be possible for you to show me what your tree looks like and to what path you bound your component please?

**Comment by tnrich** [comment]
Hey @Yomguithereal, 
Here are the path's in the component I think is screwing things up:
```
  cursors: {
    // visibilityParameters: ['vectorEditorState', 'visibilityParameters'],
    charWidth: ['vectorEditorState', 'charWidth'],
    preloadRowStart: ['vectorEditorState', 'preloadRowStart'],
    averageRowHeight: ['vectorEditorState', 'averageRowHeight'],
    viewportDimensions: ['vectorEditorState', 'viewportDimensions'],
    preloadBasepairStart: ['vectorEditorState', 'preloadBasepairStart'],
    selectionLayer: ['vectorEditorState', 'selectionLayer'],
    // caretPosition: ['vectorEditorState', 'caretPosition'],
    visibleRowsData: ['$visibleRowsData'],
    // rowData: 'rowData',
    totalRows: ['$totalRows']
  },
```

Here is what my tree looks like: 

```
var tree = new baobab({
  vectorEditorState: {
    topSpacerHeight: 0,
    bottomSpacerHeight: 0,
    averageRowHeight: 100,
    // preloadBasepairStart: 300,
    charWidth: 15,
    CHAR_HEIGHT: 15,
    // FONT_SIZE: 14,
    ANNOTATION_HEIGHT: 15,
    minimumOrfSize: 50,
    tickSpacing: 10,
    SPACE_BETWEEN_ANNOTATIONS: 3,
    preloadRowStart: 0,
    // preloadRowEnd: 9,
    showOrfs: true,
    allowPartialAnnotationsOnCopy: false,
    showCutsites: true,
    showParts: true,
    showFeatures: true,
    showAxis: true,
    showReverseSequence: true,
    viewportDimensions: {
      height: 500, //come back and make these dynamic
      width: 500
    },
    selectionLayer: {
      start: 12,
      end: 9,
      selected: true,
      cursorAtEnd: true
    },
    mouse: {
      isDown: false,
      isSelecting: false,
    },
    caretPosition: -1,
    visibleRows: {
      start: 0,
      end: 0,
    },
    sequenceData: validateAndTidyUpSequenceData(sequenceData),
    clipboardData: null
  },
  $bpsPerRow: {
    cursors: {
      viewportDimensionsWidth: ['vectorEditorState', 'viewportDimensions',
        'width'
      ],
      charWidth: ['vectorEditorState', 'charWidth'],
    },
    get: function(state) {
      return Math.floor(state.viewportDimensionsWidth / state.charWidth);
    }
  },
  $sequenceLength: {
    cursors: {
      sequenceData: ['vectorEditorState', 'sequenceData'],
    },
    get: function(state) {
      return state.sequenceData.sequence ? state.sequenceData.sequence.length :
        0;
    }
  },
  $aminoAcidRepresentationOfSequence: {
    cursors: {
      sequence: ['vectorEditorState', 'sequenceData', 'sequence'],
      circular: ['vectorEditorState', 'sequenceData', 'circular'], //decide on what to call this..
    },
    get: function(state) {
      return getAminoAcidRepresentationOfSequence(state.sequence, state.circular); //might not want to pass circular here..
    }
  },
  $orfData: {
    cursors: {
      sequence: ['vectorEditorState', 'sequenceData', 'sequence'],
      circular: ['vectorEditorState', 'sequenceData', 'circular'], //decide on what to call this..
      minimumOrfSize: ['vectorEditorState', 'minimumOrfSize'],
    },
    get: function(state) {
      return findOrfsFromSequence(state.sequence, state.circular, state.minimumOrfSize);
    }
  },
  $rowData: {
    cursors: {
      sequenceData: ['vectorEditorState', 'sequenceData'],
      bpsPerRow: ['$bpsPerRow'],
    },
    get: function(state) {
      return prepareRowData(state.sequenceData, state.bpsPerRow);
    }
  },
  $totalRows: {
    cursors: {
      rowData: ['$rowData'],
    },
    get: function(state) {
      if (state.rowData) {
        return state.rowData.length;
      }
    }
  },
  $combinedSequenceData: { //holds usual sequence data, plus orfs, plus parts..
    cursors: {
      sequenceData: ['vectorEditorState', 'sequenceData'],
      orfData: ['orfData'],
    },
    get: function(state) {
      return assign({}, state.sequenceData, {
        orfs: state.orfData
      });
    }
  },
  $visibleRowsData: {
    cursors: {
      visibleRows: ['vectorEditorState', 'visibleRows'],
      rowData: ['$rowData']
    },
    get: function(state) {
      console.log('state: ' + state.visibleRows.start + "  " + state.visibleRows.end);
      if (state.rowData && state.visibleRows) {
        return state.rowData.slice(state.visibleRows.start, state.visibleRows.end + 1);
      }
    }
  },
  $selectedSequenceString: {
    cursors: {
      sequence: ['vectorEditorState', 'sequenceData', 'sequence'],
      selectionLayer: ['vectorEditorState', 'selectionLayer'],
    },
    get: function(state) {
      if (state.sequence && state.selectionLayer && state.selectionLayer.selected) {
        return getSubstringByRange(state.sequence, state.selectionLayer);
      } else {
        return '';
      }
    }
  }
});
```

**Comment by tnrich** [comment]
Hey @Yomguithereal , I investigated further and it looks like it is on the 'visibleRowsData' that things are screwing up:
![image](https://cloud.githubusercontent.com/assets/2730609/8780821/5b1069fa-2ec0-11e5-8eab-a7d5256de68b.png)

**Comment by tnrich** [comment]
If you want, you can clone the repo and investigate directly:
https://github.com/tnrich/webpackTrial

Instructions for getting it up and running it are on that page. I'm working on the "baobabV2" branch.

**Comment by Yomguithereal** [comment]
Ok, it seems that somehow the watcher cursor of your component is killed within an event loop and this causes havoc. The emitter's behavior is not faulty and works as the node one would so I probably need to add some safeguards here to be sure an event won't create those kind of issues.

Let me try to fix this and get back.

**Comment by Yomguithereal** [comment]
Just released `baobab@2.0.0-dev10`. Can you try it out and tell me whether this fixes your issue?

**Comment by tnrich** [comment]
Will do. Thanks for looking into this

**Comment by tnrich** [comment]
Hey @Yomguithereal, your changes have indeed seemed to fix the specific error that I came across. Thanks for that!

However, I am still having a (potentially unrelated) issue with facet updates. In the tree above, you can see the  '$visibleRowsData' facet is composed of two cursors, 'visibleRows' and '$rowData'. I'm not sure why, but updates to 'visibleRows' don't seem to be triggering '$visibleRowsData' to be updated as well. 

Perhaps because '$rowData' is itself composed from two facets? Or maybe some other reason..? Do you have any suggestions for how to go about debugging this issue? I believe that this case had been fixed in the latest version of 1.x.x but the switch to 2.x seems to have broken it.

**Comment by tnrich** [comment]
Hmm, perhaps I'm misunderstanding the nature of facet updates. I'll try to illustrate how I think they work with an example below:

```
    const tree = new Baobab({
      data: {
        number: 1
      },
      computed: {
        $one: [['data', 'number'], function (x) {
          console.log('hit: ' + x);
          return x;
        }],
      }
    });
    tree.get('computed', '$one');
    
    tree.set(['data', 'number'], 5);
    tree.set(['data', 'number'], 6);
    
    tree.get('computed', '$one');
    //hit: 1
    //hit: 6
```
Running this example, only 'hit: 1' and 'hit: 6' are being logged to the console. If I understand correctly, 'hit: 5' is never logged because the facet's are 'lazily computed', and no tree.get('computed', '$one') call was made to force the facet to update. 

This seems like okay behavior in certain cases, but it also makes it difficult to rely on facet data to be up to date within a component:

For example, say I have a simple React component that listens to a single facet and then displays the value of the facet. Then say the underlying data for that facet has changed. What I had assumed would happen by default (but perhaps doesn't actually occur) is that my component would somehow trigger a new get() call on the facet, which would then be updated so that the component listening to it would display the recent data. This, however, doesn't seem to be the case, probably because the component has no way to tell if the facet has new data to give it because the facet only loads when needed.

Am I understanding facet behavior correctly? If so, how should I get my component listening to the facet to always stay updated with the most recent changes in underlying data? Perhaps there's a way to notify a facet that there is a component actively listening to it and thus it shouldn't lazy load?

Thanks so much!
Thomas

**Comment by Yomguithereal** [comment]
@tnrich: the facet's data is lazy on `get` indeed. So, as long as you do not try to get its data, it won't compute. However, if any of the paths on which the facet is dependent is updated, then, internally, the facet will know that its data is not up to date anymore so, next time you get it, it will be recomputed.

The example you show above is then normal. Normally, component bound to a facet will need to get said facet to tie it to props so they should get the facet's data and triggering a recompute if needed.

Could you write here a minimal example of what seems not to work for you in this case. It's still possible I have an unresolved bug that I'd need to fix.

**Comment by tnrich** [comment]
Okay, I think I narrowed down what the error could be arising from. It appears that if a cursor holds an object, it doesn't get updated properly.  Here's a minimal example:

``` javascript 
    const tree = new Baobab({
      rows: [1,2,3,4,5],
      visibleRows: {start: 0, end: 0},
      $rowLength: [
        ['rows'],
        function(rows) {
          return rows.length;
        }
      ],
      $specialRows: [
        ['rows'],
        function(rows) {
          return rows;
        }
      ],
      $visibleRowsData: [
        ['$specialRows'],
        ['visibleRows'],
        function(specialRows, visibleRows) {
          console.log('hit!');
          console.log('specialRows', specialRows);
          console.log('visibleRows', visibleRows);
          return specialRows.slice(visibleRows.start, visibleRows.end);
        }
      ],
    });
    tree.get('$visibleRowsData');
    tree.select('visibleRows').set({start:1,end:4});
    tree.get('$visibleRowsData');
```

Here, 'hit!' is only logged once to the console.

I hope that this is indeed *the* bug.

**Comment by Yomguithereal** [comment]
Ok, let me check that and fix this tomorrow :).

**Comment by Yomguithereal** [comment]
Hello @tnrich. The bug should be fixed in `2.0.0-dev11`.

**Comment by Yomguithereal** [comment]
Thanks for fighting on the frontline @tnrich :).

**Comment by tnrich** [comment]
Awesome thanks @Yomguithereal !

**Comment by tnrich** [comment]
Hey @Yomguithereal , I did the update and it seemed to have made things a little better but there still seem to be issues. I'll work on identifying them.

**Comment by Yomguithereal** [comment]
I released `2.0.0-dev12` in the meantime. This could have fixed some of your issues, per chance.

**Comment by tnrich** [comment]
Thanks @Yomguithereal , I'll check it out!

**Comment by tnrich** [comment]
Hey @Yomguithereal, I've been writing a few simple tests in my code to make sure the tree I'm using behaves as expected. It's too early to say for sure, but from what I can tell, the tree is performing as expected. 

I just did a big clean-up of my code and got rid of the react-router stuff I had in there and it seems to be working better already. I think there might have been issues with the baobab-react mixin not playing nicely with the react-router code. It might be worth looking into whether or not other people are also experiencing issues when using baobab-react with react router.

**Comment by tnrich** [comment]
Closing this as my issues have seem to gone away. I wonder if anyone using react router is still experiencing any strangeness. I unfortunately don't know because I removed it from my app.
