### ISSUE TITLE
`update` vs `chain`

### ISSUE THREAD

**Issue by elibarzilay** [Yomguithereal/baobab#301]
I'm not sure about the intention, but when I try this:

    var t = new Baobab({x: 0});
    var c = t.select("x");
    c.chain(add1);
    c.chain(add1);
    t.commit();
    var z = c.get();

I get a 1.  Two `apply`s make it 1 (which seems to follow the text), and the only way I managed to get a 2 is to use `apply` followed by a `chain`.  This seems weird since it means that you need to know whether this is the first update or not--?

So my guess is that there is something that I didn't get and therefore this is likely a documentation issue...

**Comment by Yomguithereal** [comment]
Normally, using two consecutive chains should give you `2`. If this is not the case, this is indeed a bug. Know however that `chain` has been dropped from v2 since the tree is written synchronously while keeping the updates asynchronous for performance reasons.

**Comment by elibarzilay** [comment]
Yes, I saw the v2 text very briefly, enough to see that switch.  And yes, adding a `{asynchronous: false}` will indeed make it return a `2`.  So this should probably be closed -- but in case you'll want to address it, that code was all that I had in an otherwise empty page, and I looked at the `z` value on the Chrome REPL.

**Comment by Yomguithereal** [comment]
It should also return `2` with `{asynchronous: true}` normally. If not, we do have a problem.
