### ISSUE TITLE
`left`/`right` vs `down`

### ISSUE THREAD

**Issue by elibarzilay** [Yomguithereal/baobab#302]
There is some inconsistency between moving left/right and moving down that had me confused for a bit: if a cursor is on an object, using `left` throws an error saying "cannot go left on a non-list type".  But if I use `down`, it just returns `null` -- throwing the same error would be much nicer.

Another small issue is the documentation on these things: the two titles are "going up in the tree" and "Going left/right/down in lists".  When I read this, I completely missed the "in lists", and half-expected it to work in objects too.  I think that it would help if the text had an explicit note saying that the latter three operations are only applicable when you're on a list.  (Possibly with an example that shows an error.)

**Comment by Yomguithereal** [comment]
Hello @elibarzilay. You are right, I will add more precisions concerning this in the docs. However, can you tell me whether your issue with `down` applies with the v1 or the upcoming v2 please (if I recall correctly, `down` would now throw in v2 currently)?

**Comment by elibarzilay** [comment]
As you guessed -- I used v1 (at least I think I did -- I just copied the minified file that is mentioned in the README).
