### ISSUE TITLE
Deep reference shifting using JSON

### ISSUE THREAD

**Issue by coma** [Yomguithereal/baobab#307]
Would it be a good idea to allow deep reference shifting using the ```javascriptJSON.parse(JSON.stringify(..))``` trick?

If that's sounds sensible then what about sending a getter function on every event rather than the data itself?, something like:
```javascript
var tree = new Baobab({
	name : 'The Dude',
	stuff: {
		pets: [{
			name: 'Nemo'
		}]
	}
}, {deepReferenceShifting: true});

tree.select('stuff').on('update', function (event) {
	
	var myNewObjectJustShifted = event.data();
});
```

I'll work on a PR if you like the idea, cheers.

**Comment by Yomguithereal** [comment]
Hello @coma. While the getter idea for event data is good and will probably be implemented soon in the `dev` version for performance/laziness reasons (but with a getter method, not a function), I don't really understand why you want to perform deep performance shifting. Baobab is a persistent data structure that will only shift affected reference for performance reasons. Using the JSON trick is not really more performant that classical deep cloning.

**Comment by coma** [comment]
Hey @Yomguithereal, that was fast!

Well, I'm trying to avoid [this](http://codepen.io/comakai/pen/pJOXXo?editors=001):
```javascript
var tree = new Baobab({
    name : 'The Dude',
    stuff: {
        pets: [{
            name: 'Nemo'
        }]
    }
});

tree.select('stuff').on('update', function (event) {

    console.log(event.data.data.pets[0]);
});

tree.get('stuff').pets[0].age = 34;
tree.select('stuff', 'pets').push({name: 'rambo'});
```

and since I've being using Baobab like [this](http://codepen.io/comakai/pen/VLGoYX?editors=001):
```javascript
var tree = new Baobab({
    name : 'The Dude',
    stuff: {
        pets: [{
            name: 'Nemo'
        }]
    }
}, {immutable: true});

tree.select('stuff').on('update', function (event) {

    console.log('event', event.data.data.pets[0]);
});

tree.get('stuff').pets[0].age = 34;
console.log('frozen', tree.get('stuff').pets[0]);

// Copy it for local usage like:
var stuff = JSON.parse(JSON.stringify(tree.get('stuff')));
stuff.pets[0].age = 34;
console.log('copy', stuff.pets[0]);

// Tree update
tree.select('stuff', 'pets').push({name: 'rambo'});
```

Would it be a good idea to let us configure the get method instead (and change the data for the data getter on the event obviously)?

**Comment by Yomguithereal** [comment]
Ok, so your problem is actually to be able to work with frozen object as if they were mutable then reinject them in the tree afterwards? Why not use the tree/cursor's setters themselves? I am unsure whether you use v1 here or the upcoming v2 but know that, for convenience, setters now return the affected node:

```js
// Example
var tree = new Baobab({hello: 'world'});
var newHello = tree.set('hello', 'monde');
```

**Comment by Yomguithereal** [comment]
The thing is I could provide you with cloning getters that would let you access safe unfrozen objects. The issue there is that it has a perf cost that you should try to avoid in some cases.

**Comment by Yomguithereal** [comment]
Linked to #276.

**Comment by coma** [comment]
On my current project (we are thinking of using Baobab for it, THANKS BTW!), my team and I found useful to break all the references in order to avoid all kind of issues and since most of the time or objects contain other object the JSON trick become pretty handy, so, I want to shield the whole thing rather than following some conventions.

We want to handle simple javascript objects in our methods, that's why I'm asking for this. Instead of just using the setters for every property, we want to mutate that simple object and set it updating the tree.

**Comment by Yomguithereal** [comment]
If your issue is with the frozen objects given by the tree then yes, you only have two solutions:

* clone or deepClone the data receive from the tree (which is costly).
* use an immutable data handling library with custom immutable setters (which baobab provides you already, in a way).

If you choose the cloning path, I advise you to check some benchmark because I am not sure the JSON trick is the fastest one. You can check how Baobab performs it [there](https://github.com/Yomguithereal/baobab/blob/v2/src/helpers.js#L124-L174) if you want or you can use lodash/underscore utilities to do so easily.

I could add dedicated options/methods regarding cloning in the future but I am still gathering use cases here.

**Comment by Yomguithereal** [comment]
One thing also, if you choose to clone the gotten data, I think it is quite safe for you to disable the tree's immutability so you can gain some perfs since everyone is going to act on data with different references than the tree's ones.

**Comment by coma** [comment]
Sure, I won't need the immutability option if I can cut all the references. I'm checking the cloner method now.

**Comment by Yomguithereal** [comment]
What I can do, if you want it, is to expose some of the lib's helpers so you may use them if needed.

**Comment by coma** [comment]
We have finally adopted another strategy for our app, anyway, passing a getter method on the events rather than the actual data would be great and providing a mechanism to modify getters/setters would be awesome.

Closing, thanks!
