### ISSUE TITLE
better approach for a cascading changes in a baobab tree

### ISSUE THREAD

**Issue by cocodrino** [Yomguithereal/baobab#314]
Hi @Yomguithereal !...I've a little question because I don't know which could be the better approach in this case, suppose than my tree has a 'login' field, when I set this field in my authentication component I need retrieve a list of results using ajax and fill other field (articles,friends or whatever)

I know than cascading changes are considered bad in flux and using the dispatcher and waitfor I can change the two stores,  but in baobab I can't find the correct solution:

1) authenticationComponent must not change other fields except those related to authentication
2) I could write a function outside my react components watching for login field changes and then retrieve the articles and fill my tree
3) inside my List or Articles components watch for changes in login and then retrieve the articles...
4) create a function which set the login details and then retrieve the articles  (this seems to be the best approach) 

also in the readme I can see this
```js

// I am not saying this is what you should do but
    // anyway, if you need to access cursors:
    this.cursors.name.set('Jack');

```

is better idea create auxiliar functions which changes the tree instead of access directly to the cursor?
setName('Jack') instead of  this.cursors.name.set('Jack');

thanks!!...

**Comment by cocodrino** [comment]
at the end I created a function which set the login details and load the details, I think than the resulting code is pretty clear and simple, thanks!...

I'm still curious about the text in the readme about change the cursors directly

thanks!

**Comment by Yomguithereal** [comment]
Hello @cocodrino. As a general rule, you should indeed avoid to update the tree from the component themselves. Even if I let the user access the cursors from the component just in case, you would rather use an action layer à la Flux that will update the tree.

**Comment by Yomguithereal** [comment]
```
                         ┌────────────────────┐
           ┌──────────── │       State        │ ◀───────────┐
           │             │    (Baobab tree)   │             │
           │             └────────────────────┘             │
        Renders                                          Updates
           │                                                │
           │                                                │
           ▼                                                │
┌────────────────────┐                           ┌────────────────────┐
│        View        │                           │       Actions      │
│ (React Components) │  ────────Triggers───────▶ │ (Functions/Events) │
└────────────────────┘                           └────────────────────┘
```

**Comment by cocodrino** [comment]
thanks so much @Yomguithereal I've found than the code is pretty clear and simple in that way...a last question: if I need change a cursors based in the data stored in other baobab field, is it a good approach?

```js

var currentTweets2 = data.tree.select('tweets', function(ob){
    var _c = data.tree.get(["currentTweetViewOption"]);
    return ob.id == _c
});

var currentTweets = function () {
    var _c = data.tree.get(["currentTweetViewOption"]);
    return data.tree.select('tweets', {id: _c})
};

```

I know than facets is the correct solution when you need get some view, but it's read only, what is the best approach in this case?

thanks again

**Comment by cocodrino** [comment]
thank so much @Yomguithereal, right now I'm migrating a small flux dummy project and I notice than my baobab code is much more clear and simple now, thank you

**Comment by Yomguithereal** [comment]
Don't hesitate to link to your code if it's Open Source so we can exchange about the strategies used.
