### ISSUE TITLE
v2, component updates not propagated in some cases

### ISSUE THREAD

**Issue by marbemac** [Yomguithereal/baobab#315]
Ok so I've been pulling my hair out trying to track this error down in my app, and I finally decided to create an isolated repository that reproduces the issue(s).

I'm not sure if this is a baobab issue, or a baobab-react issue.

Please pull this repository down (it's a very very simple app that uses baobab). Instructions to run it are in the readme.
https://github.com/marbemac/baobab-playground

Steps to reproduce:
1) Type in a username
2) Click submit, error should show up
3) Try and change the username. The baobab tree is correctly updated (type state.get() in the web developer console), but the components (ui) are not updated.

This seems to happen when a parent component listens to the same cursor as a child component? If you remove the "session" cursor from components/App.jsx, everything will behave as expected. I'm not sure what the underlying issue(s) is with baobab/baobab-react.

**Comment by Yomguithereal** [comment]
Ok @marbemac. Will check this tomorrow morning.

**Comment by marbemac** [comment]
Awesome, thank you :).

**Comment by tnrich** [comment]
I think this could be the issue I've been experiencing as well.

**Comment by Yomguithereal** [comment]
Ok, I got it. The fault lies with `baobab-react` `componentWillReceiveProps`. Fixing this asap.

**Comment by Yomguithereal** [comment]
Ok, the issue seems to be fixed now. I released `baobab@2.0.0-dev13` and `baobab-react@1.0.0-dev2` to tackle this. Beware however for the latest `baobab-react` dropped cursor access for components as it is enforcing bad practices.

**Comment by marbemac** [comment]
Awesome, thank you, a whole host of weird behavior in my app is now fixed :)!

Yes, cursors in components = bad - I used them in that playground example simply because it was faster to implement. Thanks again!

**Comment by Yomguithereal** [comment]
I will probably add a lightweight action layer in `baobab-react` soon so we can experiment things (in a hot reloadable way of course).

**Comment by tnrich** [comment]
Thanks @Yomguithereal and @marbemac! I believe this fixed some of the strange issues I've been seeing.
