### ISSUE TITLE
Cleanup tree

### ISSUE THREAD

**Issue by markuplab** [Yomguithereal/baobab#317]
Hello @Yomguithereal. Im looking best way to reset all keys in tree to ```{}```. Need your help.

**Comment by Yomguithereal** [comment]
Hello @markuplab. If what you want is to reset the tree completely, you can do `tree.set({})`. If what you want is to reset every leaf key to `{}`, then you'll have to create a recursive function that will set the keys one by one, as with a basic JavaScript object.
