### ISSUE TITLE
Can facet history be recorded?

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#321]
Hey @Yomguithereal,
I know cursor history is a thing. Now that facets are treated more similarly to cursors, does that also mean that facets can be recorded and undone/redone?

I guess it would mean recording their underlying cursors? 

I don't think this is a thing but I thought it'd be interesting to ask.

Thanks!

**Comment by Yomguithereal** [comment]
Hello @tnrich. Normally you should be able to record to facet's data indeed. The thing that should not work is this case is probably the `undo` feature since you cannot write data at facet's path.

**Comment by tnrich** [comment]
A neat, and perhaps very complicated add-on to baobab could be to record all of the cursors involved in the creation of a facet. Then by stepping back through the changes on each cursor in chronological order, you could theoretically "undo" facets. Do you think making something like this would be feasible?

**Comment by Yomguithereal** [comment]
Facet history should work without further ado now.
