### ISSUE TITLE
Baobab and Cerebral are friends!

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#322]
Hi there,

Just wanted to let you know that I have released a Cerebral Package using React and Baobab. It runs with the current dev version. It will be nice to see how Facets are coming a long to test that also.

Also planned to use the official `baobab-react` project when it supports V2. 

But you can actually play around with it now and it works just fine :-)

https://github.com/christianalfoni/cerebral-react-baobab

For people unfamiliar with Cerebral, it is a state controller with its own debugger. Check out www.christianalfoni.com/todomvc to try it out.

**Comment by marbemac** [comment]
I am using Cerebral and Baobab and loving it! I'm on my own Cerebral fork for now, but will transition to yours Christian now that the rewrite is published :). Great work to both @christianalfoni and @Yomguithereal, thank you guys.

**Comment by saulshanabrook** [comment]
@charlieschwabacher Great news! I will try it out. Thank you to both of you as well.

**Comment by christianalfoni** [comment]
@Yomguithereal Just a quick question. Version 2 of Baobab. Is is supposed to be able to do mutations and synchronously get those changes? In Cerebral now I am doing a commit() when a signal is done, the state changes does not seem to be available until I do that commit? Would be great if you could clarify that :-)

**Comment by marbemac** [comment]
@christianalfoni I believe if you set the asynchronous option to false when instantiating the tree you'll get what you're looking for. However, I found that with signals/actions, it is most effective to also turn autoCommit to false, and sprinkle "commit" actions in my signals. The commit action just calls state.commit(). This way, we have the benefits of asynchronous Baobab (which makes it possible to store input data in the tree, for example), and also get to batch action changes together.

For example, say we have a route change signal like this:

```js
sFactory.add('projectsRouted',
  RouterActions.setUrl,
  RouterActions.setCurrentPage,
  RouterActions.sidebarProjectsOn,
  commit
)
```

If you leave autocommit on, this signal would result in at least 3 tree update events (since asynchronous is false), which are sent out to components and trigger the re-render logic. By turning off autoCommit, and sprinkling commit actions in, we can dramatically reduce the number of updates Baobab sends out to components (or whatever is listening to the tree events), as a result of actions/signals.

**Comment by marbemac** [comment]
Ignore the incorrect "Cerebral" syntax there, I'm still using my implementation, but the concepts are all the same.

**Comment by christianalfoni** [comment]
Hm, hm, hm... I really do not want to expose the tree when using Cerebral, it should just work :-)

But I checked out a bit more. It seems that `syncwrite` is set to false still. When that is set to `true` I get the correct behaviour. 

From V2 documentation:

"Syncwrite

The tree now write synchronously only but will continue firing its update events asynchronously for obvious performance reasons."

This does not seems to be turned on yet in V2. Actually I do not care about the "update" event from Baobab, because Cerebral triggers its own update when the signal is done running.

I do see that it would be good to batch up mutations and commit them, but I have a feeling it is premature optimization. It is better that all mutations instantly runs. More predictable. Which is why `syncwrite` will be set to true by default in V2.

I think... ;-)

**Comment by marbemac** [comment]
Also, what is the asynchronous option set to in your case? I believe you need to have it set to false, to avoid cursor jumping when storing input state in the tree.

**Comment by tnrich** [comment]
Excited to try it out! Awesome work @christianalfoni and @Yomguithereal

**Comment by Yomguithereal** [comment]
Great news @christianalfoni. I'm finally coming back to life after some times in dire places without the Internet.

To answer your first question @christianalfoni: yes, writes are synchronous in the tree so you can read them as soon as you've written them (quite like the old `syncwrite` behavior). However, updates remain asynchronous by default and can still be controlled by the user if needed.

**Comment by christianalfoni** [comment]
Awesome to have you back @Yomguithereal :-D Looking forward to getting that last stuff in place to officially release the Cerebral React/Baobab package!

**Comment by Yomguithereal** [comment]
So, as a summary, what can help you with?

**Comment by christianalfoni** [comment]
It is actually just the issue I put up #324 . Everything else seems to be working great :-)

**Comment by Yomguithereal** [comment]
Problem with the `serialize` method?

**Comment by christianalfoni** [comment]
Ah, no, did not see the issue yet :-) Let have a looksy and get back to you!

Though I was wondering... on this syncwrite. When I do changes I indeed am able to get the state back, but if I do a `tree.get()` the changes are not there. Is it because I directly try to get the state from where it was changed? I can test an explain better if this did not make any sense :-)

**Comment by Yomguithereal** [comment]
This seems strange indeed. Can you sketch a use case so I can assess the problem please?

**Comment by christianalfoni** [comment]
Hm, just got some time to test this and now it seems to work without setting `syncwrite`. Dunno if there has been an update to the Baobab project or maybe I was just misunderstanding something. Anyways, forget about this for now :-)
