### ISSUE TITLE
V2 facets, import/export

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#324]
Hi @Yomguithereal!

I was thinking about how you would handle extracting and importing the state when cursors are present in the tree.

In immutable-store it works like this:

```js
var store = Store({
  items: {
    'foo': {}
  },
  list() {
    return {
      value: ['foo'],
      deps: {items: ['items']},
      get(value, deps) {
        return value.map((ref) => deps.items[ref]);
      }
    };
  }
});

store // { items: {foo: {} }, list: [{}] } 
store.export() // { items: {foo: {} }, list: ['foo'] }
```
I think this is important so that you can serialize the tree, send it to the server for storage (or whatever) and later import the state again, either using a normal `set()`, or with immutable-store, `store.import()`.

And yeah, just to point it out, functions can not be serialized. Like the state itself here, and the `get` in Baobab facets.

**Comment by tnrich** [comment]
Hmm I was wondering about this recently as well. It seems like with the unification of facets and cursors, clean import/export of entire trees was broken.

**Comment by Spendar89** [comment]
I'm also having trouble with this. Any sort of update call breaks if any of the cursor's children are facets.  Would love to know of a workaround.

**Comment by Yomguithereal** [comment]
Hello, to export raw data from the tree, you can use `tree/cursor.serialize` that will get rid of the computed nodes. Moreover, trees and cursors implement a `toJSON` method that use this `serialize` method so you can do `JSON.stringify(tree)`, for instance.

@Spendar89, could you sketch a minimal use case I could test to fix your issue, please?

**Comment by christianalfoni** [comment]
Okay, cool! I think serialize will do the trick!

The only thing missing is how you could insert the serialized state again. An example would be:

```js
var tree = Baobab({
  admin: {
    foo: 'bar',
    $facet: {}
  }
})

var state = tree.serialize(); // {admin: {foo: 'bar'}}


tree.set(state); // Now facets are gone?

tree.import(state); // Would just insert each path, not destroying paths
```
Would that makes sense?

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. I see the problem here. Unfortunately, I don't see any other option that a merge really. Something of the kind:

```js
var tree = Baobab(merge(serializedState, {admin: {$facet: {}}}));
```

I think you mentioned doing something of the kind with `immutable-store`, no? What was the solution you came to?

**Comment by Aetet** [comment]
Hey @Yomguithereal . At our project which was inspired by baobab we solve the problem separation facets from state tree. Check it out:
https://github.com/zerkalica/immutable-di#react-all-in-example

I think Facet must be a function which return a function which wait for a state as argument as we do at immutable-di. And of course that is very usefull, because we can use different impelementations of cursors such as Native cursor or Immutable cursor or cursor based on baobab.

So we can separate all facets from state which is good:
```js
var abbaFacet = Facet({
  a: ['tis', 'a']
})(function bloomyFacet({a}) {
  return a + 10;
})


@root
@statefull({
    abba: abbaFacet,
    changeAction: ChangeAction
})
class Application extends React.Component {
  handleClick () {
    this.props.changeAction(100);
  }
  render () {
    return <div onClick={this.handleClick.bind(this)}>Bloom: {this.props.abba}</div>
  }
}
```

This idea helps us completely hidden direct state manipulation from user. He just receive api for a change by di and not see state except passing him through root widget.

**Comment by Yomguithereal** [comment]
@ivan-kleshnin: this is one point we did not foresee in our quest to put facets into the state itself, no? Any idea regarding this particular issue?

**Comment by zerkalica** [comment]
IMHO, facets as state path abstraction is not good idea.
You must register/deregister all facets in baobab manually (looks like event emitter pattern: events.on - attach facet, events.off - detouch facet, this principle may produce a lot of bugs) No standard way to declare our facets in different projects.
You can access facet only trough string key: cursor.get('facetName') - this looks like service locator pattern. String 'facetName' is bad abstraction: how to find realization of 'facetName'? No interface provided, no information about declaration path in our project, no ide support, we can't jump to facet declaration, it's not native for js.

Check angular.di example: https://github.com/angular/di.js/blob/master/example/kitchen-di/dishwasher.js Any dependency is function + decorator.

Getting facet data in this way looks like cursor.get(FacetFn): object

In immutable-di we use same principle: any facet is function + decorator with deps spec. No manual registration needed, no problem with ide completion or jumping to function declaration. Base brick is function, not a state path.

Our facet look like this:

```js
// MyFacet.js
import {Path} from 'immutable-di/define'
import AnotherFacet from './AnotherFacet'

function MyFacet(part1, part2, anotherFacet) {
  return anotherFacet(part1, part2)
}

export default Facet({
  part1: Path(['tis', 'a']),
  part2: ['tis', 'b'], // autoconverted to Path(['tis', 'b'])
  anotherFacet: AnotherFacet
})(MyFacet)
```

How you can see facets future?
What is your proposal for them, should they be the part of state or exist indepently?

**Comment by ivan-kleshnin** [comment]
> @ivan-kleshnin: this is one point we did not foresee in our quest to put facets into the state itself, no? Any idea regarding this particular issue?

What issue exactly? A lot of controversial things were said.

**Comment by christianalfoni** [comment]
@Yomguithereal With immutable-store there is an `export` and `import` method. The export method grabs that actual values of a mapped state, not the mapped values. When you use `import` it traverses the existing default tree and sets each branch. Since a mapped state is also updated with `set` it just works.

https://github.com/christianalfoni/immutable-store#import-and-export

I see the benefit of facets suggested here, it is basically how it works in current version as I see it. It definitely works, but it has a bit of a different perspective. In the examples above the facet is more related to the component that is going to use it, rather than some general state you want all your components to use... as if it just was normal state. I personally like to define all my state at one spot and components does not know anything about how that state is produced. It is just one concept of exposing state to the components.

On the other hand I see the arguments :) But there is nothing wrong with having both? You either decide to use "internal facets", defines with $ or functions, as in immutable-store. Or you can create external facets that you specifically expose to components?
