### ISSUE TITLE
using "merge" after "set" deletes changes

### ISSUE THREAD

**Issue by kraf** [Yomguithereal/baobab#327]
When I use `merge` after using `set` before to change a few values all my changes from the `set`s are lost, e.g.

```javascript
var tree = new Baobab({a: 'old', b: 'old'});

function test() {
  tree.set('a', 'new');
  tree.merge({b: 'new', c: 'new'});
}

test()
console.log(tree.get()) // => { a: 'old', b: 'new', c: 'new' }
```

**Comment by Yomguithereal** [comment]
Hello @kraf. I guess you are using v1? Anyway, this shouldn't happen indeed. V2 should not have this problem any more. As a temporary workaround, you can enable the `syncwrite` option of the tree.

**Comment by kraf** [comment]
Nice, you released 2.0.0! I've been following your "monkey business" because I was building almost the same thing as a kind of plugin. It's really awesome you are putting this much effort into the library, thanks a lot for all the work.

**Comment by Yomguithereal** [comment]
Well I hope it will work as expected :). Out of curiosity, is your plugin's code open source somewhere? The monkeys' API won't change but I am still pondering the underlying implementation. There are actually some discussion about it in #348.

**Comment by kraf** [comment]
It's not, because I aborted in an early stage after realizing you were working on it. My initial stab at this was kind of a mess to be honest, I just wanted to get an overview of all the areas that would be touched. I will try to find some time to look into it and help out.

**Comment by Yomguithereal** [comment]
Do you happen perchance to have coded a dependency solving algorithm while doing so? I will probably need one very soon.

**Comment by kraf** [comment]
No I didn't have one yet, using monkeys in monkeys was out of scope for me. Do you create some kind of dependency graph already? I'll read your code today in the evening to get up to speed.

**Comment by Yomguithereal** [comment]
For the time being, the library will handle first recursion level very well and any other level after that given that you register your monkeys in the recursion order. But for more complex cases, I guess I'll need to do dep graph solving. But I am still pondering whether the lib actually needs this level of complexity.
