### ISSUE TITLE
cursor.push Causes Erroneous Triggering of cursor.select(i) Update Event

### ISSUE THREAD

**Issue by mjhasbach** [Yomguithereal/baobab#328]
Why does the following situation occur?

```js
var Baobab = require('baobab'),
    tree = new Baobab({array: [0]});

var arrayCursor = tree.select('array'),
    arrayIndex0Cursor = arrayCursor.select(0);

arrayIndex0Cursor.on('update', function(e) {
    if (e.data.data === e.data.previousData) {
        console.log('The data at tree.array[0] did not change, so why is this event firing?');
    }
});

arrayCursor.push(1);
```

If I wanted to know the array had been mutated, I would have used `arrayCursor.on('update', ...)`.

**Comment by Yomguithereal** [comment]
Hello @mjhasbach. Are you working with v1 or v2? I shall investigate the issue. It might comes from a wrong handle over falsey values.

**Comment by mjhasbach** [comment]
The issue occurs with both 1.1.2 and 2.0.0-dev13.

**Comment by Yomguithereal** [comment]
Ok, I've found the problem. That's because I assume that the `push` operation applies to the array as a whole rather than its last index. This makes the cursors on the array's elements fire also. Need to fix this.

**Comment by mjhasbach** [comment]
It would also be cool to be able to create a cursor that maintains its reference to an array element after its position in the array changes. That would clean up my code in several different places. If you agree, I can open a separate ticket if you want.

Current:
```
var Baobab = require('baobab'),
    tree = new Baobab({array: ['bacon']}),
    arrayCursor = tree.select('array'),
    baconCursor = arrayCursor.select(0);

console.log(baconCursor.get()); // bacon

arrayCursor.unshift('eggs');

tree.commit();

console.log(baconCursor.get()); // eggs
```

Desired:
```
var Baobab = require('baobab'),
    tree = new Baobab({array: ['bacon']}),
    arrayCursor = tree.select('array'),
    baconCursor = arrayCursor.select(0);

console.log(baconCursor.get()); // bacon

arrayCursor.unshift('eggs');

tree.commit();

console.log(baconCursor.get()); // bacon
```

**Comment by Yomguithereal** [comment]
Actually, you can already do something of the kind by using a function or a descriptor object in the cursor's path:

```js
// For instance
var Baobab = require('baobab'),
    tree = new Baobab({array: ['bacon']}),
    arrayCursor = tree.select('array'),
    baconCursor = arrayCursor.select(function(e) { return e === 'bacon'; });
```

**Comment by mjhasbach** [comment]
Whoops, I overlooked that feature when reading the documentation. Thanks for the tip!

**Comment by Yomguithereal** [comment]
No problem @mjhasbach. Hope it will simplify some operations for you :-).

**Comment by Yomguithereal** [comment]
The push operation should now not trigger the update of sibling cursors within an array.
