### ISSUE TITLE
cursor.serialize is undefined v2

### ISSUE THREAD

**Issue by kevbook** [Yomguithereal/baobab#329]
Example
```
var cursor = tree.select();
console.log(typeof cursor.serialize); // undefined
```

**Comment by Yomguithereal** [comment]
Hello @kevbook, I cannot reproduce your issue. The same code as yours produce `"function"` on the latest dev version.

**Comment by kevbook** [comment]
I am sorry, Its not an issue. I have npm v3.2x. It flattens the dependencies, and somehow messes up the dist build.

**Comment by Yomguithereal** [comment]
Ok. Should I check with npm v3 just to be sure something is not broken?

**Comment by kevbook** [comment]
npm v3 is in beta. Its not an issue with your package. NPM is just beta.
