### ISSUE TITLE
#unset array item.

### ISSUE THREAD

**Issue by DylanPiercey** [Yomguithereal/baobab#338]
Lets say we have a structure like:

```javascript
var struct = new Baobab({
    todos: ["first", "second"]
});
```

It would be handy to be able to unset items in the array as an alternative to splice.

```javascript
struct.select("todos").unset("0"); // Remove first item.
struct.select(["todos", "0"]).unset(); // Same as above.
```

The second notation would be handy for things like mapping:

```javascript
// inside some component
struct.select("todos").map(todo => <Todo todo={ todo }/>);

// Inside of the todo component
<button onClick={ ()=> todo.unset() }>Remove</button>
```

Thoughts?

**Comment by Yomguithereal** [comment]
Hello @DylanPiercey. Actually you can already use `unset` on array if I am not mistaking (you might want to check that to be sure however, at least on incoming v2).

`cursor.map` already exists also. However I wouldn't vouch for components altering the tree themselves. Usually people use an action layer to alter the tree.

Something like this:

```
                         ┌────────────────────┐
           ┌──────────── │       State        │ ◀───────────┐
           │             │    (Baobab tree)   │             │
           │             └────────────────────┘             │
        Renders                                          Updates
           │                                                │
           │                                                │
           ▼                                                │
┌────────────────────┐                           ┌────────────────────┐
│        View        │                           │       Actions      │
│ (React Components) │  ────────Triggers───────▶ │ (Functions/Events) │
└────────────────────┘                           └────────────────────┘
```

**Comment by DylanPiercey** [comment]
@Yomguithereal thanks for the reply. For large projects I am using an action layer, I simply thought that this would be a handy hack.

I am currently not using the 2.0 branch but it's good to know that this is their.

Thanks!
