### ISSUE TITLE
[v2] Relative paths in facets

### ISSUE THREAD

**Issue by saulshanabrook** [Yomguithereal/baobab#339]
For my use case, relative paths would reduce a lot of repetition. I have some deeply nested facets that commonly refer to their siblings or direct parents. I have [uploaded a full example here](https://gist.github.com/saulshanabrook/8dc6e6f66d24b9576dc0#file-state-js) of part of my codebase which has many facets that could be greatly simplified with relative paths.

Some idea for syntax:

* If you start the path list with `.`, this means it should be relative to the current facet. Like `['.', 'siblingToFacet']`
* Any number of `..` items will go up one path level. Like `['.', '..', 'siblingOfParent']`. Or since this would only be used after `.`, the first `.` would be superfluous, so could just be:  `['..', 'siblingOfParent']`.

While this proposed syntax is very succinct and relatively clear, it would conflict with any `.` or `..` keys in the tree. These effectively couldn't be accessed.

Hm, maybe using [ES6 symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) would make sense. They [can be transpiled with babel](https://babeljs.io/docs/learn-es2015/#symbols). 

You would expose them in the package, and when parse the path you could look for them.

Maybe something like this:

```javascript
import {parent, relative} from 'baobab'

...
[relative, 'sibling']
...
[parent, 'siblingOfParent']
```

**Comment by Yomguithereal** [comment]
Hello @saulshanabrook. This was mentioned a while ago while we were discussing v2's facets. We had difficulties however to choose a correct standard to do so. Do you have some suggestions?

**Comment by saulshanabrook** [comment]
@Yomguithereal Just edited my question with some ideas.

Yeah @zerkms [said earlier](https://github.com/Yomguithereal/baobab/issues/240#issuecomment-111022688)

>>  Is it time to add a kind of relative path support and, most notably, do we enable facets to register path dependencies in a relative fashion (something along ['./users'] for instance in our example)?
>
>Just as in Node relative paths will make data restructuring harder. 
>I think it does not worth the added complexity.

**Comment by Yomguithereal** [comment]
@jacomyal, does `.` and `..` might apply as a conflicting key for you?

**Comment by Yomguithereal** [comment]
I would personally vouch for `.` and `..` as I find symbols to be cumbersome and not useable by ES5 (which is still the norm, let's not forget it).

**Comment by saulshanabrook** [comment]
@Yomguithereal If you compile with Babel, you should be ok though, no?

**Comment by hyusetiawan** [comment]
In my humble opinion (yeah i don't abbreviate :D), I vote to not support relative paths. Though it does cut down on the repetitions but it does introduce direct dependence from one component to the other, I would rather have a full path to each data so it is easy to trace how the data flows.

**Comment by Yomguithereal** [comment]
Hello @hyusetiawan. I guess enabling relative paths wouldn't force anyone to use them if they don't want to. I think @saulshanabrook wasn't specifically speaking about paths for components but rather only for facets' dependencies.

**Comment by saulshanabrook** [comment]
Yeah only for the inputs to facets.

**Comment by saulshanabrook** [comment]
@Yomguithereal awesome! Thank you so much for all your great work.
