### ISSUE TITLE
[v2] Using merge() on first level of tree broke facets updating

### ISSUE THREAD

**Issue by giant-polovincak** [Yomguithereal/baobab#343]
```js
const t = new Baobab({
  user: {
    name: '',
    surname: '',
    fullName: Baobab.monkey({
      cursors: {
        name: ['user', 'name'],
        surname: ['user', 'surname']
      },
      get: ({name, surname}) => `${name} ${surname}`
    })
  }
});
```
updating name or surname with `set()` work good
```js
t.select('user').set('name', 'John');
t.select('user').set('surname', 'Doe');
```
result of `user.fullName` will be `John Doe` now

```js
t.select('user').merge({
  'name': 'John',
  'surname': 'Doe'
});
```
but `merge()` used on first level subtree broke updating all monkeys and result of `user.fullName` will be `undefined undefined`

...
Using merge on deeper level seems work ok again
```js
  user: {
    identity: {
      name: '',
      surname: ''
    }

t.select('user', 'identity').merge({
  'name': 'John',
  'surname': 'Doe'
});
```

**Comment by Yomguithereal** [comment]
Hello @giant-polovincak, are you seeing this for at least `2.0.0-rc1` or `2.0.0-dev14`?

**Comment by giant-polovincak** [comment]
@Yomguithereal on verions `2.0.0-dev14`

**Comment by Yomguithereal** [comment]
Thanks, I start investigating.

**Comment by Yomguithereal** [comment]
@giant-polovincak : latest commit should have fixed the issue by now. Will publish a new dev version soon. Thanks!

**Comment by Yomguithereal** [comment]
`2.0.0-dev15` is now published.

**Comment by christianalfoni** [comment]
Ah, great, I had this issue too :-)

Will there be a new release candidate soon? Running on rc2 with this issue now

**Comment by Yomguithereal** [comment]
If there are no more bugs to be found I will even release a first `2.0.0`.

**Comment by christianalfoni** [comment]
:+1:
