### ISSUE TITLE
Using baobab in an npm module, integrating it with another tree

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#345]
Hey there @Yomguithereal and others, 

I had a theoretical question about the best way to integrate one baobab tree into another. 

Basically I'm building an npm module which relies on baobab to trigger updates in react components. I'd like to then require that npm module in another project that also has its own baobab tree. Is there a clean way to access to the module's baobab tree from the outside project? Or perhaps it would be better to inject a baobab tree from the outside project into the module where the module's tree could attach to it?

I'm sure I could figure out some sort of solution, but was wondering if anyone had any experience doing something like this in another project.

Thanks for your time!

**Comment by Yomguithereal** [comment]
Hello @tnrich. I am not sure to fully understand what you try to do but if you need the first module's tree, why don't you make this module export it or at least make it accessible? If what you search is a way for Baobab to return you its existing instance, then you cannot because I think it would be bad to have an internal instances register for the two following reasons:

* Your first module might rely on a different Baobab version and will make such register moot.
* This would mean easy memory leaks for unaware people.

Is your code open source? We can discuss it further here if you want.

**Comment by codonovan** [comment]
Not sure if this will work for you as I've not done this with npm modules. However all my components, within a project, have a state.js with an object literal representing it's state.

```javascript
export default {
  searchbox: {
    selected: 'objects',
    terms: ''
  }
};
```
In the root of my project I have a another state.js file that imports all the other state and merges it via lodash and then exports it for Baobab to use.

``` javascript
import { merge } from 'lodash-compat';
// component sub states
import carousel from './components/carousel/state.js';
import searchbox from './components/searchbox/state.js';
// etc
const AppState = {
  test: "test"
};
const modules = [
  carousel,
  searchbox
];
export default merge(AppState, ...modules);
```

**Comment by tnrich** [comment]
Hey @codonovan , that's an interesting idea that is pretty close to what I want to do. Just a few questions for you: 
How do you handle namespacing issues (what if one state also has a 'test' property)? 

How do you get access to the top level baobab tree in your components?

How do you handle merging facets?

@Yomguithereal, that's an interesting point you bring up about the dangers of exposing the baobab tree to outside modules with their own trees. Unfortunately my project is currently being developed on a private repo so we can't discuss it there quite yet although sometime in the future it will be released as open source.

Thanks both of you for your input. It's much appreciated!

**Comment by codonovan** [comment]
Namespacing just works, if using the components name as the root object property. Using the example above if we add a 'test' property to the searchbox and the carousel component we end up with a tree like

``` javascript
{
  searchbox: {
    selected: 'objects',
    terms: '',
    test: '' // ['searchbox', 'test']
  },
  carousel: {
    test: '' // ['carousel', 'test']
  },
  test: 'test' // ['test']
}
``` 

Facets also Just Work&#8482; using a new example
``` javascript
// src/components/user/state.js
import { monkey as facet } from 'baobab';
export default { 
  user: {
    name: 'Fred',
    surname: 'Bloggs',
    fullname: facet({
      cursors: {
        name: ['user', 'name'],
        surname: ['user', 'surname']
      },
      get: function(data) {
        return data.name + ' ' + data.surname;
      }
    })
  }
}
```
``` javascript
// src/state.js
import { monkey as facet } from 'baobab';
import { merge } from 'lodash-compat';
// component sub states
import user from './components/user/state.js';
// etc
const AppState = {
  test: "test",
  surnameFirst: facet({
      cursors: {
        name: ['user', 'name'],
        surname: ['user', 'surname']
      },
      get: function(data) {
        return data.surname + ', ' + data.name
      }
    })
};
const modules = [
  user
];
export default merge(AppState, ...modules);
```

Your second question has caused me to reconsider my approach. I'm 3 projects in with Baobab and I've not had to do that yet! My projects, so far, lean more towards web sites than web apps. I guess the state I have along side a component can be considered local state in pure react terms. The AppState I declare at the root level of the project is my global or shared state. This has served me well within the context of a single project but I think it fails in terms of npm modules.

While I'm here. Thanks @Yomguithereal Baobab has radically changed the way I approach front end development improving my productivity and happiness! Really looking forward to using Baobab with my first react native project...

**Comment by tnrich** [comment]
Hmm, thanks @codonovan for the detailed examples. They're super helpful. Your approach definitely seems promising. I like how you co-locate the state requirements next to the component that uses them. It's a little like facebook's relay in that way. 

Figuring out a good way to access the top level tree would be nice. 

I still have an even simpler question though, how do you update "local" state?

Say in your example you have:

```
// src/components/user/state.js
import { monkey as facet } from 'baobab';
export default { 
  user: {
    name: 'Fred',
    surname: 'Bloggs',
    fullname: facet({
      cursors: {
        name: ['user', 'name'],
        surname: ['user', 'surname']
      },
      get: function(data) {
        return data.name + ' ' + data.surname;
      }
    })
  }
}
```

How would you go about updating that state from another file within the component, say, an "action" file or a react component?

Normally I would do it like:
```
// src/components/user/changeNameAction.js
var tree = require('../state.js');
module.exports = function changeName(newName) {
    tree.set(['name'], newName);
};
```

But in this case, state.js isn't actually a baobab tree, its just a javascript object. 

How do you get access to the actual tree to make updates and set listeners?

**Comment by Yomguithereal** [comment]
Thanks for the insight @tnrich & @codonovan. Never had the opportunity to code an application needing state namespacing yet. But the way you do it @codonovan seems sensible. What I might add in the future and that might help you is relative paths for facets/monkey so that your dynamic nodes under some of your divided namespaces might remain unaware of the final full tree's structure. You can see the discussion concerning this in #339.

@tnrich you might be interested by the minimal action system I am currently introducing for v2 `baobab-react` [here](https://github.com/Yomguithereal/baobab-react/tree/v2).

**Comment by codonovan** [comment]
Hi @tnrich,

I'm using [Cerebral](https://github.com/christianalfoni/cerebral) with [cerebral-baobab](https://github.com/christianalfoni/cerebral-baobab) so I gather up my actions like I do with my state and then bind both of them with Cerebrals controller which is then passed down through my components in reacts context. This [post](https://saulshanabrook.herokuapp.com/organizing-cerebral-code/) was my original inspiration.

Using just babob you could do this via the export in state.js
``` javascript
let baobab = new Baobab(merge(AppState, ...modules));
export default baobab;
```

I think I misunderstood your original question about accessing the top level tree. Has this helped at all?

**Comment by MichaelOstermann** [comment]
What if you have a scenario like you have 2 already existing and disconnected baobab trees (so no plain objects that you could conveniently merge) and you would like to make a third tree that either joins both, with/without computed properties depending on both trees, or just pluck & join specific cursors from each tree?

I'm trying to do something like I have trees containing database stuff. Then I have other trees that contain my UI data, which depend on different database trees, or even other UI trees. I do not want my views to know which trees they need, I want to pass a single final result to my views. Would that be possible?

**Comment by Yomguithereal** [comment]
Hello @MichaelOstermann. I guess you could listen to both your trees' update events to build or update the third one *à la carte*. Then plug your UI components to the third tree and it should work.

**Comment by MichaelOstermann** [comment]
Thanks for the advice, I went with a similar route like you described and it works! :)

**Comment by Yomguithereal** [comment]
Nice to know it works. Is your code open source per chance? I'd love to see how you are performing all this.

**Comment by MichaelOstermann** [comment]
I'm sorry, it's closed source but I can do a separate mockup if you like!
