### ISSUE TITLE
deepMerge

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#349]
Hi @Yomguithereal , there seems to be a bug with deepmerge. When I merge in a property with array it converts it to an object. Have not looked too much into it. Thought I would mention that it might be beneficial to use an existing lib for this? Just less maintenance :)

**Comment by christianalfoni** [comment]
Okay, this was actually the reason why https://github.com/Yomguithereal/baobab/issues/348 did not work

**Comment by Yomguithereal** [comment]
So deepmerge converts array into objects? This is cumbersome indeed. Let me check that. Do you have a minimal use case?

Note that for the time being I do not support monkeys beneath array nodes for performance reasons. But this might change.

**Comment by christianalfoni** [comment]
What I did was:

1. Create a tree with a monkey, typical relational example where you have object with data and to lookups with a monkey
2. Do some changes
3. Serliaze tree
4. Merge initial state object and serialized tree and `set()` the tree again

In this case the array that held the ids for monkey reference got converted to an object

**Comment by Yomguithereal** [comment]
It indeed seems that my merging function does not take Arrays into account. Silly me...

**Comment by christianalfoni** [comment]
Hehe, that explains it then :)

**Comment by Yomguithereal** [comment]
What's to be expected in our case? To consider array as leaves? Or should we try more complex things?

**Comment by christianalfoni** [comment]
Hm, what do you mean? Should not arrays just be a value?

**Comment by Yomguithereal** [comment]
Should I browse the arrays to merge things in them or such? Or should we consider arrays as basic values such as strings and numbers?

**Comment by christianalfoni** [comment]
Ah, understand now. Hm, when it comes to import/export tree I can not see why you would want to merge an item into an array. With completely generic merging yes, but not in this context. Though just my opinion :)

**Comment by christianalfoni** [comment]
Would consider just using this project? https://github.com/KyleAMathews/deepmerge. Well tested and used by a lot of people :-)

But maybe you use it internally? Not sure how fast it is

**Comment by Yomguithereal** [comment]
I'd rather not use an external library because my internal merge has some monkeys specificities. Plus I don't like how this lib is concatenating the arrays and its use of `forEach` that will slow down the perfs.

**Comment by Yomguithereal** [comment]
I will consider arrays as primitive values for the time being and we shall see very quickly whether this is a problem or not :).

**Comment by christianalfoni** [comment]
Hehe, sounds good to me! :+1:
