### ISSUE TITLE
Log out tree

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#350]
Hi @Yomguithereal ,

It seems that when you log out the tree monkeys are exposed as "getters". That is a bit troublesome when debugging.

Maybe there should be a way to get the tree with the values of the monkeys? So basically three scenarios here:

1. `tree.get()` just like it works now. Got the exposed "getters" for monkeys. Used in components etc.
2. `JSON.stringify(tree)` just like it works now. The tree without monkey values
3. `tree.something()`. The tree as a JSON like object with monkey values (no "getters")

The reason for point 3 is that Chrome does no let you debug "getters". They are just functions, can not look at the value they return :-/

Personally I think explicit methods would be valuable here as it gets a bit complex with these three scenarios. 

1. `tree.get()` = Normal version of tree, to grab values. Monkeys are "getters"
1. `tree.export()` = Get tree without monkeys
2. `JSON.stringify(tree)` = Get string version of tree with the values of the monkeys
3. `tree.import(someState)` = Will let you import some object

That way Cerebral could `JSON.parse(JSON.stringify(tree))` to get a clean representation of the tree. That would be nice :)

**Comment by Yomguithereal** [comment]
Let me check that :). Chrome lets you see the getter's return if you click on the ellipsis if I record correctly though.

**Comment by Yomguithereal** [comment]
Any update about this @christianalfoni.

**Comment by christianalfoni** [comment]
We made a fix on this in Cerebral, where we serialize/parse the data before sending it to the debugger. That said, I am not sure if monkeys still appear when logging. I see @guria states that on gitter channel, though I am not sure which version he is referring to. I would say we can close this and set up a new issue if it still occurs

**Comment by Guria** [comment]
chrome console doesn't allow to expand objects returned by getters aka monkeys. Is there a way to log whole tree which will contain pre computed monkey values instead of getters?
![](http://i.imgur.com/wAwmfKM.png)

**Comment by Yomguithereal** [comment]
Thanks @Guria. I am thinking of adding an option (for dev only, not prod) that would let the monkey write data not in a lazy fashion for convenience.

**Comment by Guria** [comment]
Great, thanks

**Comment by Yomguithereal** [comment]
Following up on #354.
