### ISSUE TITLE
Facets are broken in rc3

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#351]
I updated from `2.0.0-dev12` to `2.0.0-rc3` and app starts to fail.
The reason is facets do not evaluate anymore but return it's own value in state:
```js
state.get("something", "$currentItems"); 
// [["path-A", ...], ["path-B", ...], ["path-C", ...], function() {...}]
```

**Comment by Yomguithereal** [comment]
Hello @ivan-kleshnin, I recently changed the way computed data works to avoid some quirks about the `$` sigil and boost performance somehow. See [this](https://github.com/Yomguithereal/baobab/tree/v2#computed-data-or-monkey-business) for the updated doc.

**Comment by ivan-kleshnin** [comment]
I'll recheck the case again. Thank you!
I somehow missed the name update.

**Comment by Yomguithereal** [comment]
No problem @ivan-kleshnin.

**Comment by ivan-kleshnin** [comment]
Everything works.
