### ISSUE TITLE
Monkeys aren't lazy

### ISSUE THREAD

**Issue by Zache** [Yomguithereal/baobab#362]
Monkeys are automatically and eagerly evaluated when first creating the Baobab tree. They are also evaluated eagerly after being replaced at runtime (something that doesn't seem to work correctly when the tree is non-persistent).

A [Fiddle](http://jsfiddle.net/Zacharias/wj0x0a5q/) demonstrating this issue.

Related monkey issues: #348 #354

**Comment by Yomguithereal** [comment]
Hello @Zache. You are right indeed. Let me check #363.
