### ISSUE TITLE
Monkey and undefined state

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#364]
Hi there,

A monkey seems to break if the state value is undefined. I think it would be wise to allow the monkey to stay, though not run if any of the cursors are undefined. Just return undefined itself. When the depending state value is inserted it will run as normal.

Does that make sense? :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. I am not sure I fully understand what you describe here. Could you add a practical example please?

**Comment by christianalfoni** [comment]
Yeah, sorry, was a bit in a hurry :-)

```js
{
  messagesToDisplayIds: [],
  messagesToDisplay: Monkey({
    cursors: {
      ids: ['messagesToDisplayIds'],
      messages: 
    }
  })
}
```

**Comment by Yomguithereal** [comment]
And what would be the expected behavior here?

**Comment by christianalfoni** [comment]
Update issue :-) Return undefined from Monkey if any cursors are undefined. Run `get` when all are defined

**Comment by Yomguithereal** [comment]
This seems a bit magical. Shouldn't the getter handle the case where one of its dependencies is non-existent and return whatever seems fit?

**Comment by christianalfoni** [comment]
Hm, yeah, good point. I thought of the monkey is "invalid". But yeah, just giving it the value `undefined` when running the get seems more natural indeed :-)

**Comment by Yomguithereal** [comment]
Plus this is the current behavior and I have nothing to change :P

**Comment by christianalfoni** [comment]
Hehe, it broke the app on our end, but yeah... if I checked the error better I would probably not have created the issue :-) Would be nice to wrap those gets in a try/catch to give an error of: "Something wrong with your monkey: ${message}".

**Comment by Yomguithereal** [comment]
Try/catch cannot be optimized by JS engines and are performance hogs unfortunately.

**Comment by christianalfoni** [comment]
I thought it was only a scope problem? Catch creates a new scope, but that only happens of course only when it catches.

Anyways, React took a step forward will all its custom errors. In development mode it is really nice to get extra help as errors/bugs are what we spend most of our time on ;-)

**Comment by Yomguithereal** [comment]
I perfectly agree with this and whenever possible I try to give useful feedback to the user but this particular case really makes me fear performance issues. Maybe I could try something when in dev mode or else.

**Comment by christianalfoni** [comment]
Yeah, it would be really nice in dev mode. But yes, completely agree on not running try/catch for performance reasons :-)
