### ISSUE TITLE
typescript interface definitions

### ISSUE THREAD

**Issue by bcherny** [Yomguithereal/baobab#370]
for https://github.com/borisyankov/DefinitelyTyped

**Comment by Yomguithereal** [comment]
Hello @bcherny. Why not? But I must admit I am a TypeScript beotian and I do not know how to write those definitions. Would you know how to write them?

On a side note, are you using Baobab in a TypeScript envrionment? I remember some people having trouble dealing with cursors etc. in a statically typed environment.

**Comment by bcherny** [comment]
I'm new to typescript as well, and am not at all confident about the definitions I wrote. Will work to improve them a bit and put up a pr, unless someone else gets to it before I do.

And no, I've had no issues with running baobab in a statically typed environment so far.

**Comment by Yomguithereal** [comment]
Don't hesitate to ask if you have trouble finding the type of data handled by the public API.
