### ISSUE TITLE
Tree is missing cursor methods (isRoot, isLeaf)

### ISSUE THREAD

**Issue by SaphuA** [Yomguithereal/baobab#371]
The created tree is missing some cursor methods like `isRoot` and `isLeaf`. `tree.root.isRoot` does exist, however.

**Comment by Yomguithereal** [comment]
Hello @SaphuA. Why would you like to have those methods at tree level?

**Comment by SaphuA** [comment]
I made a generic method to traverse my cursors. I was expecting the root tree to be a cursor as well. It's not a big deal, just would make sense to me.

**Comment by Yomguithereal** [comment]
The tree itself is not accessible through cursors only. Cursors will only get back to the root cursor, never to the tree itself. Maybe your generic method should use the root cursor instead of the tree (`tree.root` or `tree.select()`.

**Comment by Yomguithereal** [comment]
Any update @SaphuA?

**Comment by SaphuA** [comment]
This can be closed. Thanks!
