### ISSUE TITLE
add non-minimize version to the build folder

### ISSUE THREAD

**Issue by kirjs** [Yomguithereal/baobab#385]
Currently only `baobab.min.js` is there.

**Comment by Yomguithereal** [comment]
Yes. And the only reason why it is here is bower. If I could I would drop it altogether. Do you need the concatenated version to be in the repository @kirjs?

**Comment by kirjs** [comment]
In this case I'd suggest either drop it all together, or have both versions. 
Non minified version helps a lot with development, and it would be nice to have quick access to it.
