### ISSUE TITLE
Debugger or something to see Baobab fired change events

### ISSUE THREAD

**Issue by rohitlodha** [Yomguithereal/baobab#389]
I would like to see the events fired and number of listener received. This can help in performance audit. Is there any tool that can help it?

**Comment by SaphuA** [comment]
I don't think there's anything available but it should be fairly easy to utilize [Events](https://github.com/Yomguithereal/baobab#events) and build something yourself.

**Comment by Yomguithereal** [comment]
@rohitlodha: actually, Baobab event emitting is handled by the [emmett](https://github.com/jacomyal/emmett#emmett) library. You have ways to listen to every events fired and retrieve the listeners etc.

**Comment by Yomguithereal** [comment]
@rohitlodha, any update on this? Does it work for you?
