### ISSUE TITLE
Can function be data?

### ISSUE THREAD

**Issue by rohitlodha** [Yomguithereal/baobab#391]
I have some code where I want to store function in a node. It works all fine till I try to execute the function and then it silently crashes.

**Comment by markuplab** [comment]
https://github.com/Yomguithereal/baobab#philosophy

> Only data should enter the tree

**Comment by Yomguithereal** [comment]
@rohitlodha functions shouldn't be data indeed as they are not serializable (at least in JavaScript). But can you describe your use case a bit more? Why do you need this function in the tree?
