### ISSUE TITLE
Using complex objects with attached functions and array buffers with/alongside baobab

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#394]
Hey @Yomguithereal , 

So I'd like to use an npm module called ntseq (https://github.com/keithwhor/NtSeq)

and use it in conjunction with baobab like so (this is just one example): 

```js
    ntSeq: deriveData([
        ['sequenceData',
            'sequence'
        ],
        function(sequenceString) {
            var seq = (new Nt.Seq()).read(sequenceString); //sequenceString = atgc
            return seq;
        }
    ]),

    reverseComplement: deriveData([
        ['ntSeq'],
        function(ntSeq) {
            var a = ntSeq.complement().sequence();
            return a; //a = gcat
        }
    ]),
```

This doesn't work if I'm using baobab's immutable option, but it does work if immutability is turned off.

Is there anything I should watch out for here? Or is there a better way to do what I'm trying to do. 

Thanks!
Thomas

**Comment by Yomguithereal** [comment]
Hello @tnrich. This is an interesting use case indeed. The thing is that the data returned by monkeys is indeed made immutable. But since your monkeys return specific objects etc. the freezing fails. There can be solutions (none currently apart from disabling immutability or fiddling with internals) and I am willing to implement them. Let me check that more thoroughly.

**Comment by tnrich** [comment]
Here's the solution I've come up with currently:

```js
var Nt = require('ntseq');
var ntSeq;

module.exports = {
    sequenceData: { //tnr: sequence data gets passed in and overrides this object
        sequence: '',
        features: [],
        translations: [],
        parts: [],
    },

    ntSeq: deriveData([
        ['sequenceData',
            'sequence'
        ],
        function(sequenceString) {
            ntSeq = (new Nt.Seq()).read(sequenceString);
            //return a blank object here, we're just using the baobab monkey 
            //system to update a locally stored ntSeq object
            return {};
        }
    ]),

    reverseComplement: deriveData([ //tnr: example of ntSeq usage
        ['ntSeq'],
        function() {
            //use the local ntSeq variable
            var a = ntSeq.complement().sequence();
            return a;
        }
    ]),
}
```

I'm not sure how robust it is. Basically I'm using baobab's monkeys to manage updates to an object that is held outside the tree

**Comment by Yomguithereal** [comment]
@tnrich it seems you might do better by listening to the needed path in the tree and updating your objects there, no?

Something along the way of:

```js
tree.select(path).on('update', callback);

// or if you need to subscribe to several paths
tree.watch({one: path1, two: path2}).on('update', callback);
```

**Comment by tnrich** [comment]
The problem I forsee with that is that the object needs to be used by subsequent monkeys.

**Comment by Yomguithereal** [comment]
Yes you are right. It would be a problem if this need to be used by subsequent monkeys. The thing is normally the tree should host anything but raw serializable data. @christianalfoni do you have an opinion about this?

I could add some options to enable some monkeys to return things other than raw data but I must think about it.

**Comment by tnrich** [comment]
Hey again @Yomguithereal, I just so happened to run into this same issue again, but for a different part of my app, so I thought I'd document it: 

In this particular use case, I've got a bunch of annotations to a sequence that each have an associated range (i.e. start: 10, end:20, start 100, end: 2000 etc.). In one of my components, I'll only be viewing a small subsection of the entire sequence at a time, and so need to quickly figure out which annotations land in that subsection. To make that look-up really fast, I'd like to store the annotation ranges in an "interval tree" data structure using a library like: https://github.com/shinout/interval-tree2. What I'm unsure of is how to go about using the interval tree data structure in conjunction with cerebral/baobab. 

If I could, I'd like to compute the interval tree as a monkey based on the existing annotation ranges, and then require it in my components. unfortunately, it doesn't seem like cerebral/baobab wants complex objects being stored in the state tree (pojo's only). 

I think I can maybe solve this by having the interval-tree live outside of the baobab tree, use baobab's monkeys to update it, and reference it/do calculations with it in subsequent monkeys that only persist serializable data to the tree. It doesn't seem like a very clean solution however..
