### ISSUE TITLE
reference an action from another action

### ISSUE THREAD

**Issue by larryhengl** [Yomguithereal/baobab#395]
Hi, quick Q: can we refer to an action from within another action?

in actions.js
```
export function action1(tree,blah1){ return blah1}
export function action2(tree,blah2){
  // return actions.action1(blah)   ??
  // return this.action1(blah)   ??
  // return tree.context.actions.action1(blah)   ??
}
```
thx!

**Comment by tnrich** [comment]
If I'm understand correctly, I think you can using:
```
return action1(tree,blah2)
```

**Comment by Yomguithereal** [comment]
Hello @larryhengl. What about the following:

```js
export function action1(tree,blah1){ return blah1}
export function action2(tree,blah2){
  return action1(tree, blah2);
}
```

**Comment by larryhengl** [comment]
yeah, tried that.  i get something like,
```Uncaught ReferenceError: action1 is not defined(…)```

**Comment by Yomguithereal** [comment]
This is quite strange. Are those line in the same file? I'll check ES6 binding rules but this should work.

**Comment by larryhengl** [comment]
yes, the function exports are in the same actions.js file.

**Comment by Yomguithereal** [comment]
I guess you are using Babel as transpiler?

**Comment by Yomguithereal** [comment]
Just tried the following:

```js
export function one() {
  console.log('hey');
}

export function two() {
  one();
}
```

with

```js
import {two} from './sha'
two();
```

and this work perfectly.

Is your code open source somewhere so I can help you better?

**Comment by larryhengl** [comment]
yes, babel v6 with the es2015 preset plugin

**Comment by larryhengl** [comment]
sure. the project is here... https://github.com/larryhengl/myvariantjs-demo

the state tree and actions files are under src...
https://github.com/larryhengl/myvariantjs-demo/blob/master/src/app/

my example above was a simple abstraction, but what I was shooting for is in actions.js I have 
[export function fetchData(tree,exampleN) {}](https://github.com/larryhengl/myvariantjs-demo/blob/master/src/app/actions.js#L132)
and
[export function formatRequest(tree, searchType) {}](https://github.com/larryhengl/myvariantjs-demo/blob/master/src/app/actions.js#L173) 

and in a react component i am making an action call to fetchData. 
[this.actions.fetchData(this.actions.formatRequest(searchType))](https://github.com/larryhengl/myvariantjs-demo/blob/master/src/app/components/InputExact.jsx#L45)

this works fine, but as you can see i am pushing the formatRequest action call into the fetchData action call.  I was thinking to simplify that to just making the fetchData action call, and internally that would call the formatRequest action.

**Comment by Yomguithereal** [comment]
I see that [this](https://github.com/larryhengl/myvariantjs-demo/blob/master/src/app/components/InputExact.jsx#L65) line binds the `_handleSubmit` function to `null`. Therefore `this.actions` does not exist in your function, no?

**Comment by Yomguithereal** [comment]
Sorry for closing. I misclicked.

**Comment by larryhengl** [comment]
my understanding was that react does autobinding to the component, and that is what i see in the handler.  even if i supply `this` to the _handleSubmit call, or even if I pass `this.actions` as the scope/context. i see the same error no matter what i pass as the `this` arg.

perhaps this is a baobab-react issue?  seems the bindActions delegation is keeping the tree context but losing the source component scope. i am totally guessing there.  would be cool if the actions were global and attached to the tree (even if they are not serializable) so that at least they can see eachother without caring about scope.
