### ISSUE TITLE
Watchers bug related to computed field

### ISSUE THREAD

**Issue by markuplab** [Yomguithereal/baobab#398]
Hello @Yomguithereal!

Please, look at this example:
http://plnkr.co/edit/ntgBPoCBZOp6E0vIpphH?p=preview

```js
var tree = new Baobab();

tree.set(['filters', 'list'], ['first', 'second']);
tree.set(['filters', 'activeIndex'], 0);

tree.set(['filters', 'computed'], Baobab.monkey(
  ['filters', 'list'],
  ['filters', 'activeIndex'],
  function (list, activeIndex) {
    return list.map(function(name, index) {
      return {
        name: name,
        isActive: index === activeIndex
      }
    });
  }
));

var watcher = tree.watch({
  value: ['filters', 'computed', 0, 'name']
})

var data = watcher.get();
console.log(data);

setTimeout(function(){
  console.log('Timeout end');
  
  var delayedWatcher = tree.watch({
    value: ['filters', 'computed', 0, 'name']
  });
}, 0);
```

When we try watch computed fields before transaction end, it's throw error:
```
Uncaught TypeError: Cannot read property 'relatedPaths' of undefined
```
But if we get watcher value, all is good.
It's fixes if we start watch fields at nextTick, but it's don't good way, in the case of which, we must have much flow control.

**Comment by Yomguithereal** [comment]
Hello @markuplab. I think this issue is related to #393. I should be able to fix it soon normally.

**Comment by markuplab** [comment]
Ok, big thanx.

**Comment by markuplab** [comment]
Hi, do can say when it bug will be fixed? Maybe, you need help to fix it?

**Comment by Yomguithereal** [comment]
The bug should be fixed now. Will soon release a `2.2.0` as soon as #399 is merged.
