### ISSUE TITLE
No way to unbind event handler functions

### ISSUE THREAD

**Issue by jmullo** [Yomguithereal/baobab#403]
I don't see any way to unbind event handler functions.

I need an equivalent of tree.release() that only removes the event handlers but doesn't wipe out all the tree data.

**Comment by Yomguithereal** [comment]
Hello @jmullo. Both the tree and the cursors are extending the [emmett](https://github.com/jacomyal/emmett) library event emitter. They therefore both have an `off` method you can use to unbind single handlers.

**Comment by jmullo** [comment]
Ahh, thanks. I suggest adding that to the documentation :)

**Comment by Yomguithereal** [comment]
Actually this already is in the [documentation](https://github.com/Yomguithereal/baobab#nb) :smile:. But I admit I should put it first.
