### ISSUE TITLE
Issue with .babelrc and "optional" configuration

### ISSUE THREAD

**Issue by srcspider** [Yomguithereal/baobab#406]
I'm having some strange issues compiling with latest baobab with latest babel. The error I'm seing is babel complaining .babelrc.optional is not valid option. Based on the documentation for babel there is no "optional" unless its undocumented option.

```
resolve: {
	extensions: [ '', '.js', '.jsx' ]
},

module: {
	loaders: [
		{
			test: /\.(js|jsx)$/,
			loader: 'babel',
			query: {
				presets: [ 'es2015', 'react' ],
				plugins: [ 'transform-runtime' ]
			}
		},
		{
			test: /\.json$/,
			loader: 'json-loader'
		}
	]
},
```

Relevant lines from `npm ls --depth=0`

```
├── babel@6.3.13
├── babel-core@6.3.15
├── babel-loader@6.2.0
├── babel-plugin-transform-runtime@6.3.13
├── babel-preset-es2015@6.3.13
├── babel-preset-react@6.3.13
├── babel-preset-stage-0@6.3.13
├── babel-preset-stage-1@6.3.13
├── babel-preset-stage-2@6.3.13
├── babel-preset-stage-3@6.3.13
├── baobab@2.1.2
├── baobab-react@1.0.0
```

Tried to isolate it but problem doesn't appear consistently (probably due to code getting optimized out or not hitting certain code paths in the simplified examples). 

A simple workaround (that works) is to just remove the file, `rm node_modules/baobab/.babelrc`

**Comment by Yomguithereal** [comment]
Hello @srcspider. I thought I had dropped the `.babelrc` file with `.npmignore` but it seems it's not the case. Would this fix your issue if the `.babelrc` file was not included in the npm release?

**Comment by Yomguithereal** [comment]
On a side note, you should exclude the `node_modules` folder from being parsed by babel in your loader configuration. This would dramatically enhance the speed of your build.

**Comment by srcspider** [comment]
Yes removing the file solves it, and I'm aware of the ignore option but its
not an option for my setup.

**Comment by Yomguithereal** [comment]
Ok. I'll drop the file from the npm build then. I am quite surprised however that babel search for .babelrc files within deps sub folders.

**Comment by srcspider** [comment]
@Yomguithereal its probably a good thing. I have considered in the past including the specific functions from certain libraries such as D3 but been stopped by their "unique" file inclusion system. Recently more and more libraries are moving to webpack/babel/es2015 friendly structures (for better or worse). So, with a bit of headache on having to deal with libraries babel issues (and their changing code), its relatively easy to include bits of them when there are great advantages to be had in doing so (such as is the case with D3 where you might want to access a subsystem directly to be sure to avoid the rest of the bloat).

**Comment by Yomguithereal** [comment]
Aren't recent [modularization](https://github.com/d3) not of any help in your case?

**Comment by Yomguithereal** [comment]
Just dropped the file from the build. Will release `2.1.0` now.

**Comment by Yomguithereal** [comment]
Now released.
