### ISSUE TITLE
Tree-level event emitted when data has not changed

### ISSUE THREAD

**Issue by jrust** [Yomguithereal/baobab#409]
I'm seeing inconsistent behavior in which events are emitted when a set doesn't actually change the value of the data.  Example:

```javascript
var tree = new Baobab({
    items: [{id: 1}],
});

var cursor = tree.select(['palette', 'items']);
cursor.on('update', function() { console.log('cursor update'); });
tree.on('update', function() { console.log('tree update'); });

tree.select(['palette', 'items', 0, 'id']).set(1);  // Only tree update is emitted, but with empty 'paths' array
```

I would expect that no events are emitted if the paths array is empty.

**Comment by Yomguithereal** [comment]
That's weird indeed @jrust. Let me check that and fix it.

**Comment by Yomguithereal** [comment]
So I wrote this test:

```js
it('moot updates should not trigger an update of the tree.', function() {
  const tree = new Baobab({items: [{id: 1}]}, {asynchronous: false});

  let triggered = false;

  tree.on('update', function({data}) {
    triggered = true;
  });

  tree.set(['items', 0, 'id'], 1);

  assert(!triggered);
});
```

and it passed.

Can you check several things:

1. are you using Baobab v2?
2. did you disable the `pure` option?
3. your example mentions a non-existent `palette` key. Is that a problem or just that your example was truncated from a more complex one?

**Comment by jrust** [comment]
Sorry palette should not have been there.  But, very interesting: when I did `asynchronous: false` then it worked as expected.  But when I use tree.commit() instead then it does emit an event.

**Comment by Yomguithereal** [comment]
Ok, I think this is a `tree.commit` issue actually. I think the method doesn't check whether there are updates in the stack before firing.

**Comment by Yomguithereal** [comment]
Does this fix the issue @jrust?

**Comment by jrust** [comment]
It does, thanks!
