### ISSUE TITLE
Error thrown when setting prop on a not found item

### ISSUE THREAD

**Issue by jrust** [Yomguithereal/baobab#410]
Minor thing, but two different types of errors are raised if a path is not found when trying to do an update:
```javascript
var tree = new Baobab({ items: [{ id: 1 }] });
tree.set(['items', { id: 2 }, 'id'], 3); // Throws Baobab.select: invalid path.
tree.select(['items', { id: 2 }]).set('id', 3); // Throws Cannot read property 'concat' of null
```

I'd expect the first error in both cases.

**Comment by Yomguithereal** [comment]
That's a problem indeed @jrust. I'll check that tomorrow.

**Comment by jrust** [comment]
Also, worth noting is that I came across this as I was trying to find a good way to do conditional updates.  I was trying to figure out a more concise way to do something like:
```
var tree = new Baobab({ items: [{ id: 1 }] });
if (tree.get('items', { id: 1 })) {
  tree.set('items', { id: 1 }, 2);
}
```

Is there a better way that I'm missing?  I kind of hoped that it'd just silently no-op if I did a `set` on an invalid path, but I can see how that could be problematic as well.  OTOH it felt heavy to have to do a full `get()` on it to test for existence.

**Comment by jrust** [comment]
I found cursor.exists() -- that seems reasonably lightweight.

**Comment by Yomguithereal** [comment]
The second case should now throw properly.

**Comment by jrust** [comment]
Yup, that works, :+1:
