### ISSUE TITLE
Support for rich objects in monkeys?

### ISSUE THREAD

**Issue by jrust** [Yomguithereal/baobab#412]
I had been hoping to have things like `moment` objects as monkeys in a Baobab tree.  However, `Object.freeze` on the `moment` object messes up its internals and trying to get the object out of the tree with `tree/cursor.deepClone` also fails because of the methods on the moment object.

 If I turn immutability off for the whole tree then it works fine, but I'd rather not do that.  So, another possibility would be to add the ability to turn off immutability on a per-monkey basis. Have you come across this sort of thing?  Any solutions I'm missing?

**Comment by Yomguithereal** [comment]
Hello @jrust. This issue is also being discussed in #394. I will probably end up adding some options to the monkeys. Something along the following:

```js
monkey({
  cursors: {
    name: ['name']
  },
  get: function() {...},
  immutable: false
});
```

**Comment by jrust** [comment]
Sounds like a decent solution. Thanks for looking into it!

**Comment by Yomguithereal** [comment]
Can I ask you a question @jrust? Do you prefer the following:

```js
monkey({
  cursors: {
    name: ['name']
  },
  get: function() {...},
  immutable: false
});
```

Or the following:

```js
monkey({
  cursors: {
    name: ['name']
  },
  get: function() {...},
  options: {
    immutable: false
  }
});
```

**Comment by jrust** [comment]
I think the first looks cleaner, but how would it work in the shorthand mode for creating monkeys?

**Comment by Yomguithereal** [comment]
I guess it wouldn't work for the shorthand. In this case, you need complex things so the shorthand is not very appropriate. Else, a solution would be the following:

```js
monkey(['name'], fn, {immutable: false});
```

But I must check whether this arguments heuristic is possible so that the function can be that polymorphic.

**Comment by tnrich** [comment]
+1 for the nice looking shorthand :)

**Comment by Yomguithereal** [comment]
However, I guess the shorthand would go along with the second longhand, not the first one.

**Comment by jrust** [comment]
Yeah, I think that looks like a nice API that is extensible to other options in the future

**Comment by Yomguithereal** [comment]
I added the longhand version on master. Will add the shorthand later.

**Comment by Yomguithereal** [comment]
The shorthand has been added. Will release v2.3.0 very soon.

**Comment by jrust** [comment]
:clap:

**Comment by Yomguithereal** [comment]
Can one of you test the feature on its project so I can release safely?

**Comment by tnrich** [comment]
Are there any anti-patterns to be aware of when using the non-immutable monkeys?

**Comment by tnrich** [comment]
I'll try to test this out today @Yomguithereal , thanks for all the hard work :)

**Comment by jrust** [comment]
Yup, it worked great (shorthand notation) on my project.  What before had resulted in a number of failing tests now works as expected.  In terms of best practices @tnrich my thought would be to avoid mutating the object's raw values if at all possible since that could make it hard to reason about where a change is coming from.  In the case of a `moment` object that would mean not trying to mutate the timestamp that makes up the core of the object, while allowing the moment library to do its internal mutations of month names or localization formats.

**Comment by tnrich** [comment]
Thanks @jrust for the feedback. I think you put that very nicely :)

**Comment by Yomguithereal** [comment]
@tnrich, mutable monkeys already are a kind of anti-pattern anyway. But sometimes, immutability etc. is a drag and you have to circumvent it to get the job done. The examples from this issue and yours in #394 are good example of why you would like to have mutable monkeys sometimes.
