### ISSUE TITLE
Splice not working as expected when passing negative starting value 

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#413]
I would expect splice to work the same as this code when passing (-1,1) as arguments : 
![image](https://cloud.githubusercontent.com/assets/2730609/11988930/469f5584-a9aa-11e5-8833-c254edf68f6e.png)

However that doesn't seem to be the case (https://tonicdev.com/tnrich/567b65dfb573610c005a2b09):
![image](https://cloud.githubusercontent.com/assets/2730609/11988936/7177a428-a9aa-11e5-93ba-97f6018f3148.png)

Let me know if this is actually working as expected. Thanks!

**Comment by Yomguithereal** [comment]
Hello @tnrich. Let me look into this and see if something went wrong.

**Comment by Yomguithereal** [comment]
It seems I haven't thought to handle negative indexes. Let me take care of this.

**Comment by tnrich** [comment]
Thanks!
