### ISSUE TITLE
Specify path via dot notation string instead of array

### ISSUE THREAD

**Issue by TomKaltz** [Yomguithereal/baobab#415]
Instead of 

```javascript
var newData = cursor.set(['one', 'two'], 'world');
```
Would be nice to be able to...
```javascript
var newData = cursor.set('one.two', 'world');
```
using a library such as https://github.com/sindresorhus/dot-prop or something similar.

**Comment by Yomguithereal** [comment]
Hello @TomKaltz. I am not very fond of the dot notation because you have to find some way to escape the dot in case a user wants to use a dot within one of its keys. Let me think about it some more.

**Comment by Yomguithereal** [comment]
I won't go this way for the time being. Too much users using `.` in some conventions for property names. Would be very harmful to them and breaking to deploy this in v2.

**Comment by PFight** [comment]
May be as an option, disabled by default? I have just read about baobab, these arrays are pretty confusing for a newbie.
