### ISSUE TITLE
tree.set and pathes

### ISSUE THREAD

**Issue by markuplab** [Yomguithereal/baobab#416]
Hello @Yomguithereal! I have question about `tree.set` / `cursor.set`.

```
state.set(['array', { id: 10 }, 'field'], value)
```

When we use path with "find" logic, it's convert it to string `'[object_Object]'` and use it as key.
It's planned? If planned, i think we must analyze paths with find logic, and work like it `tree.get`

**Comment by Yomguithereal** [comment]
Hello @markuplab. You shouldn't do the following:

```js
state.set(['array', { id: 10 }, 'field', value]);
```

But this:

```js
state.set(['array', { id: 10 }, 'field'], value);
```

Because your first example is saying: set the whole state to be the array I give you.

But the fact that it is cast to string is weird. Can you build a full use case so I can try to debug it, please?

**Comment by markuplab** [comment]
Sorry, it's error in message.

```

var tree = new Baobab({
	x: [
		{ id: 10, hello: 'world' }
  ]
});

tree.set(['x', { id: 10 }, 'field', 'some'], 'value');
console.log(tree.get());
```
![2015-12-29 23 20 01](https://cloud.githubusercontent.com/assets/4974184/12038481/58933e02-ae7a-11e5-85fd-9f89fc3ddfc5.png)


But this code work correct:

```
tree.set(['x', { id: 10 }, 'field'], 'value');
```
![2015-12-29 23 21 20](https://cloud.githubusercontent.com/assets/4974184/12038503/8214410e-ae7a-11e5-9072-a5757f13002d.png)

**Comment by Yomguithereal** [comment]
Ok, I see now. Thanks @markuplab. Will fix that asap.

**Comment by Yomguithereal** [comment]
This is more profound than I initially thought. Will need some time to fix this.

**Comment by Yomguithereal** [comment]
This should be fixed now. Thanks @markuplab and sorry for the delay.
