### ISSUE TITLE
Nested monkeys not triggering other nested monkeys..

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#417]
Hey there @Yomguithereal , I'm having an issue where my monkeys aren't updating quite correctly. I've got the lazy monkeys disabled. Here's a simplified version of the state:
```js
var state = {
    products: {
        genes: {
            howManyGenes: null,
            customVectorRequired: true,
            completed: monkey([
                ['.', 'customVectorRequired'],
                ['.', 'howManyGenes'],
                function(customVectorRequired, howManyGenes) {
                    return (customVectorRequired != null && howManyGenes != null)
                }
            ]),
        },
       
    },
    pages: {
        UserInfoPage: {
            number: 0,
            completed: false,
        },
        SelectProductPage: {
            number: 1,
            completed: monkey([
                ['products'],
                function(products) {
                    if (products.genes.selected && products.genes.completed) {
                        return true
                    } else if (products.oligoPools.selected) {
                        return true
                    } else if (products.onboardCustomVector.selected) {
                        return true
                    } else {
                        return false
                    }
                }
            ]),
        },
    },
    //derived state
    currentPage: monkey([
        ['activePageNumber'],
        ['pages'],
        function(activePageNumber, pages) {
            var currentPage
            some(pages, function(page) {
                if (page.number === activePageNumber) {
                    currentPage = page;
                }
            });
            return currentPage
        }
    ])
}
```

Basically the flow should be: 
update howManyGenes: 10  >>>  triggers products.genes.completed >>> triggers pages.SelectProductPage.completed >>> triggers currentPage

Unfortunately, it seems to be only making it part of the way. The current page update is never triggered. I'm wondering what the culprit might be. I'll try to whip up a little example real quick.

**Comment by tnrich** [comment]
Here's a link demonstrating the problem: 
https://tonicdev.com/tnrich/5683368d6baf940c00094e46

**Comment by Yomguithereal** [comment]
Hello @tnrich. I don't have much time right now but if your monkeys are recursive, try setting them in the tree in the dependency order and this should fix it. I haven't implemented a full dependency solving algorithm in the lib yet and it won't go farther than solving the first recursion level.

**Comment by tnrich** [comment]
what do you mean exactly by dependency order?

**Comment by Yomguithereal** [comment]
Like if A relies on B that relies on C, the insertion order in the tree should be A, then B then C.

**Comment by tnrich** [comment]
Hmm okay I think I tried that but got errors even when it was like that.
I'll check it out and post another example. How hard would it be to make it
order independent?

**Comment by Yomguithereal** [comment]
It would require to build a propre dependency solving algorithm into the library and apply it wherever needed and this would require some time for a rather small benefit.

**Comment by tnrich** [comment]
Okay, I'm fine with that. Here's an example where I declared the monkeys in descending order, but they still don't work quite right: https://tonicdev.com/tnrich/monkeytest2

Maybe it's because they're nested a bit?

**Comment by Yomguithereal** [comment]
It seems your example displays a strange example of the `some` function. Shouldn't you be using `find`?

**Comment by Yomguithereal** [comment]
Ok, turns out that this level of nesting throw off my solving algorithm.

**Comment by tnrich** [comment]
How hard will this one be to fix you think? Is there anything I can do to help?

**Comment by Yomguithereal** [comment]
I have a solution but need to edit the code slightly but in a lot of different places.

**Comment by tnrich** [comment]
Sounds good. Good luck!

**Comment by tnrich** [comment]
Any update on this one @Yomguithereal , I'm running into it in several places now.

**Comment by tnrich** [comment]
```js
pages: {
        UserInfoPage: {
            name: 'Contact Info',
            number: 0,
            completed: false,
        },
        SelectProductPage: {
            name: 'Product Selection',
            number: 1,
            completed: monkey([
                ['cerebralForm', 'SelectProductPage', 'completed'],
                function(completed) {
                    console.log('completed: ' + JSON.stringify(completed, null, 4))
                    return completed;
                }
            ]),
            
        },
        CustomizeProductPage: {
            name: 'Customization',
            number: 2,
            completed: false,
        },
        SubmissionPage: {
            name: 'Upload',
            number: 3,
            completed: false,
        },
        EmailVerificationPage: {
            name: 'Confirmation',
            number: 4,
            completed: false,
        }
    },
```

I'm also getting a new type of error as well: 

![image](https://cloud.githubusercontent.com/assets/2730609/12310875/d4fec1d0-ba07-11e5-9816-c06781c9c7f5.png)

**Comment by Yomguithereal** [comment]
I'm on it.

**Comment by Yomguithereal** [comment]
My latest commit should have fixed your issue @tnrich. Can you test it and tell me if the second issue you raised is still here, and, if so, open a dedicated issue please?

**Comment by tnrich** [comment]
Awesome thanks so much @yomguithereal !! I'll test it out asap

**Comment by tnrich** [comment]
Okay @Yomguithereal, looks like my first issue has indeed been remedied. Thanks for that! I am unfortunately still seeing the second problem I posted, so I'll make a dedicated issue for that. 

Thanks again for all the hard work :)
