### ISSUE TITLE
nested monkey errors when listening to undefined path

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#422]
Hey @Yomguithereal , this one is a little bit tricky and might be hard to debug. I haven't yet been able to produce a simplified test-case for it, but at least it is reproducible within the repo I'm in. 

Here's the code that produces the bug: 

```
import Model from 'cerebral-model-baobab';
const state = Model({
    // completed: monkey([
    //             ['cerebralForm','SelectProductPage','completed'],
    //             function(completed) {
    //                 return completed ? true : false
    //             }
    //         ]),
    pages: {
        // completed: monkey([
        //         ['cerebralForm','SelectProductPage','completed'],
        //         function(completed) {
        //             return completed ? true : false
        //         }
        //     ]),
    },
}, {
    lazyMonkeys: false
})
```

When the first comment block is commented in, no error occurs, everything just runs as it should. However, if the second comment block is commented in, I'm getting this error: 

![image](https://cloud.githubusercontent.com/assets/2730609/12339358/988efeaa-bac9-11e5-8d11-83e8ba611106.png)

As you can see, the error is getting triggered by the cerebral devtools. 

![image](https://cloud.githubusercontent.com/assets/2730609/12339415/ced3d364-bac9-11e5-8650-ec2ba4adc624.png)

Let me know what other info/setup I can provide you with to help you out.

Thanks!

**Comment by abalmos** [comment]
@Yomguithereal I have the same issue as @tnrich. Any Monkey that is not at the root the of the state tree results in the above error.

**Comment by Yomguithereal** [comment]
Hello @tnrich and @abalmos. Can you tell me if you are able to reproduce the bug with raw Baobab outside of the cerebral Model please?

**Comment by Zache** [comment]
I get the bug and we are only using React and Baobab, so it's not a Cerebral issue.

**Comment by Yomguithereal** [comment]
Ok. Can you show me the use case @Zache? Or does the one shown at the beginning at this issue, without cerebral decorum work?

**Comment by Zache** [comment]
@Yomguithereal I'm working on making an isolated repro, but it's not cooperating with me right now :cry:

**Comment by Zache** [comment]
```javascript
var Baobab = require('baobab');
var Monkey = Baobab.monkey;

var baobab = new Baobab({
    blubb: {
        data: {
            name: 'zacharias',
            primes: [2, 3, 5, 7, 11],
            doubler: Monkey(['.', 'primes'], primes => primes.map(n => n * 2))
        },
        other: {
            trippler: Monkey(['..', 'data', 'primes'], n => n * 3)
        }
    }
});

baobab.merge(['blubb'], { data: { stuff: 13, primes: [2, 3, 5, 7] } });
```

**Comment by Yomguithereal** [comment]
Thanks @Zache. I will look into it.

**Comment by Yomguithereal** [comment]
Version `2.3.2` is now released.

**Comment by abalmos** [comment]
@Yomguithereal Thanks for quick response! However, it seems that with `2.3.2` the "trippler" monkey function is called twice. Once with the new array of primes and once with `undefined` (which of courses breaks the monkey).

Here is the updated example case:
```js
var Baobab = require('baobab');
var Monkey = Baobab.monkey;

var baobab = new Baobab({
    blubb: {
        data: {
            name: 'zacharias',
            primes: [2, 3, 5, 7, 11],
            doubler: Monkey(['.', 'primes'], primes => primes.map(n => n * 2))
        },
        other: {
            trippler: Monkey(['..', 'data', 'primes'], n => n.map(n * 3))
        }
    }
});

baobab.merge(['blubb'], { data: { stuff: 13, primes: [2, 3, 5, 7] } });
baobab.get(['blubb', 'other', 'trippler']);
```

**Comment by abalmos** [comment]
@Yomguithereal On second take it seems ['blubb', 'data', 'primes'] is just lost from the tree altogether. That's why the Monkey is called with undefined.
