### ISSUE TITLE
How would I select all sub documents?

### ISSUE THREAD

**Issue by srossross** [Yomguithereal/baobab#442]
```
var tree = new Baobab({
  users: {
    john: {
      firstname: 'John',
      lastname: 'Gold'
    },
    jack: {
      firstname: 'Jack',
      lastname: 'Gold'
    }
  }
});
```

In this example how would I select all users with the last name `"Gold"`?
eg:

```
tree.select('users', '*', {lastname: 'Gold'})
```

**Comment by Yomguithereal** [comment]
Hello @srossross. Baobab cursors cannot look over multiple nodes in the tree (as opposed to jQuery for instance) for sanity and performance reasons.

What do you need to do here? Retrieve all the users with the last name Gold or do you also need to observe their changes (in that case I can show you how you could solve your issue by using monkeys).

**Comment by srossross** [comment]
> What do you need to do here? Retrieve all the users with the last name Gold

Yes, That was what I was wondering. Thank you for the response.
