### ISSUE TITLE
.parent() feature

### ISSUE THREAD

**Issue by azimot** [Yomguithereal/baobab#447]
after selecting a path sometimes need to access to parent for example : 
tree.select('palette', 'flower','herbal').set('newkey','newvalue').parent()  
or .parent('flower') [one of fathers that is exist on path] to doing another things

**Comment by Yomguithereal** [comment]
Hello @azimot. The `.up` method actually does that (at least your first example, not the latter with further selection).

**Comment by azimot** [comment]
Thanks
