### ISSUE TITLE
Get/Select on Various Array Entries

### ISSUE THREAD

**Issue by jemos** [Yomguithereal/baobab#449]
Hi,

Is it possible to use .get({param: value}) and it return all the entries that have the property param = value?

As far as I know it will only return the first element found.

Thank you.

**Comment by davincho** [comment]
Hi,
I think it is not possible.
But there is an easy solution for your problem:

```javascript
{
  items: [{
    id: 1,
    name: 'Item1'
  }, {
    id: 2,
    name: 'Item1'
  }]
}

var result = tree.get('items').filter(function(item) {
  return item.name === 'Item1';
});
```

**Comment by jemos** [comment]
Thanks for that hint.
