### ISSUE TITLE
Allow to use "xpath" selectors like '/palette/colors/2'

### ISSUE THREAD

**Issue by ebuster** [Yomguithereal/baobab#452]
Instead of proposed selectors format with multiple arguments or array:

``` js
var thirdColorCursor = tree.select('palette', 'colors', 2);
var thirdColorCursor = tree.select(['palette', 'colors', 2]);
```

I would like to use string path selectors:
`var thirdColorCursor = tree.select('/palette/colors/2);`

Implementation promises to be a simple (I didn't read sources yet, sorry):

``` js
select() {
  // get first passed argument
  // ...
  if (_.isString(argument) && _.includes(argument, '/')) {
    path = _.split('/', argument)
  }
  // use path var like it was 1st argument
}
```

Additionally it could be allows to use relative selectors, from already taken cursor:

``` js
var paletteCursor = tree.select('/palette'); // absolute
var thirdColorCursor = paletteCursor.select('./colors/2'); // relative from pallete
// or the same but without leading dotslash
var thirdColorCursor = paletteCursor.select('colors/2');
```

**Comment by Yomguithereal** [comment]
Hello @ebuster. This would be a nice idea indeed to enable XPath like selection or else but I won't add it to the library's core. However, a distinct library to enhance a tree so it can use this kind of utility by adding, say, a `selectXpath` or `xpath` to the tree & cursors coule be a nice addition.
