### ISSUE TITLE
Monkeys Defined in Arrays don't Resolve

### ISSUE THREAD

**Issue by glennt** [Yomguithereal/baobab#453]
Hello,

I am currently evaluating baobab, one use case in our application is for a common object to be referenced by multiple nodes in a tree. Monkeys solve this problem but I can't get it to work when the monkey is defined in an object that's in an array.

Below is the state tree I'm using:

```
var stateTree = new BaoBab({
    nested: {
        nestedMore: {
            nestedMonkey: monkey({
                cursors: {
                    users: ['users']
                },
                get: function(data) {
                    return data.users['1'];
                }
            })
        }
    },
    todos: [
        {id: 1, name: 'todo1', user:
            monkey({
                cursors: {
                    users: ['users']
                },
                get: function(data) {
                    return data.users['1'];
                }
            })
        },
        {id: 2, name: 'todo2', user:
            monkey({
                cursors: {
                    users: ['users']
                },
                get: function(data) {
                    return data.users['2'];
                }
            })
        }
    ],
    users: {
        '1': {name: 'user1'},
        '2': {name: 'user2'}
    }
});

//returns a user object as expected
console.log(stateTree.select('nested','nestedMore','nestedMonkey').get());

//returns a MonkeyDefinition object instead of a user object
console.log(stateTree.select('todos',0,'user').get()); 
```

Also, the data param in the get functions in the todos array always comes in undefined so I had to make the functions return hard-coded objects.

Should we be able to define monkeys in objects that are in arrays? 

Thanks!

**Comment by glennt** [comment]
I approached this a different way, instead I attach the monkeys after creating the initial tree by iterating through each of the todos then doing cursor.set('user', monkey({ ... })) and it works fine.

**Comment by Yomguithereal** [comment]
Hello @glennt. Sorry for the very late answer but yes, monkeys are not automatically created beneath array for performance reasons. Your solution should work fine but I advise you not to have too large an array containing monkeys.
