### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by sithara** [Yomguithereal/baobab#454]
Hi 

This is my code .Is there a provision to internationalise the data(`**Past 30 days**`) in the tree structure  ? 

```
Router.run(routes, Router.HistoryLocation, (Handler, state) => {
  var tree = new Baobab({
    app: {
      timeLines: [
        {
          name: 'Past 30 Days',
          value: 30,
        },
        {
          name: 'Past 60 Days',
          value: 60,
        },
        {
          name: 'Past 90 Days',
          value: 90,
        }
      ]
    }
  });
```

**Comment by Yomguithereal** [comment]
Internationalisation should not be a concern of the tree but rather of your components' rendering logic. Typically, what people tend to do is to pass the internationalisation function through context and use in in components to translate the string or string codes.
