### ISSUE TITLE
Hot to find the data from collection?

### ISSUE THREAD

**Issue by janryWang** [Yomguithereal/baobab#456]
like this

```

const tree = new Baobab({collection : [{id:1223},{id:455}] })

tree.select('collection').select(
     Baobab.query(
       {
          id:{$gt:1000}
       }
     )
)


```

**Comment by Yomguithereal** [comment]
Hello @janryWang. What do you need to achieve in the end. Get the desired data, or select it to listen to its updates?

**Comment by janryWang** [comment]
I just want search data，and I need a powerful search feature like mongo query language😄

**Comment by Yomguithereal** [comment]
I you just want to search data, you can just use JavaScript builtin `filter` method like this:

```js
const collection = tree.get('collection');

const foundItems = collection.filter(function(item) {
  return item.id > 1000;
});
```

I what you need is a configuration model supplied as data like in Mongo, then Baobab won't help you but you could use its data along with different library doing just this kind of work.

**Comment by Yomguithereal** [comment]
Something like [Sift](https://github.com/crcn/sift.js) for instance.

**Comment by janryWang** [comment]
Perfect ! Thank you very much! I like it !
