### ISSUE TITLE
Events are not firing up in IE11

### ISSUE THREAD

**Issue by vcardins** [Yomguithereal/baobab#486]
Hello, for some reason events are not firing up in IE11. Is that known? What can be done to workaround this?

```
myCursor.on('update', function() {
  console.log('Event was fired up');
});
```

**Comment by Yomguithereal** [comment]
Unfortunately I don't have a mean to test anything on IE11. Can you give me some more information about the issue? Do you see errors displayed in the JS console?

**Comment by samsch** [comment]
I'm just passing through, but maybe the MS testing VM's would be useful to you?
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by fabien** [comment]
@vcardins did you ever find out more about this? Although I haven't tried in IE11, I am depending on Baobab in my apps, so it would be good to know the current status. Thanks!

**Comment by Yomguithereal** [comment]
Can't someone give me the error displayed in the console so I can debug? I don't have time right now to spawn a VM to test IE11 compatibility.

**Comment by anthony-redFox** [comment]
I took example from readme and checked on IE11.
Windows 10 - IE11 - it works 

![image](https://user-images.githubusercontent.com/4757846/30744314-8901bb8a-9f6f-11e7-8af8-bab91c70bba6.png)

**Comment by Yomguithereal** [comment]
Should I close this issue then?

**Comment by anthony-redFox** [comment]
I think yes, if someone doesn't agree, the issue can be reopened with more details.
