### ISSUE TITLE
Infinite loop when adding DOM element

### ISSUE THREAD

**Issue by krom-xr** [Yomguithereal/baobab#507]
let example = new Baobab({test: {}})
    let divEl = document.createElement('div');
    example.select('test').set({div: divEl});

After `.set(...)` - infinite loop. Browser tab not responding

**Comment by krom-xr** [comment]
Ok. Thanks. 
But may be best solution - throw error in that case. If it possible?

In may case - 
I put stream (webrtc stream) to Baobab store.
In one option i put canvas.captureStream() (empty stream).
There was ok in chrome - but infinite loop in firefox. 
Because stream instance - have link to canvas in firefox.

**Comment by Yomguithereal** [comment]
> But may be best solution - throw error in that case. If it possible?

Probably so. But checking for circular reference does have a performance cost.

You should really avoid storing classes from the DOM in a Baobab tree if you can, though.
