### ISSUE TITLE
Force monkey recalculation

### ISSUE THREAD

**Issue by savolkov** [Yomguithereal/baobab#515]
Hey!

It so happened that I need to make monkey to recalculate value on data change outside the tree.

Example:
```ts
fromJohn: monkey(
  ['data', 'messages'],
  function(messages) {
    const externalValue = ExternalService.getValue()
     return messages.filter(function(m) {
      return m.from === 'John' || externalValue;
});
```

In my case it is possible to fire events in case of outer data change, however I can't find the proper way to trigger monkey recalculation.

What is the proper way to do it?

**Comment by Yomguithereal** [comment]
There is a hidden method `_refreshMonkeys` defined [here](https://github.com/Yomguithereal/baobab/blob/master/src/baobab.js#L167) that you can try. It's possible to call it without arguments to force all of the tree to refresh if I remember correctly. Or you can read the code and see how to refresh one particular monkey.

**Comment by savolkov** [comment]
@Yomguithereal Thanks a lot! Didn't manage to find it on my own.

I'll write back with solution if I'll find it

**Comment by savolkov** [comment]
Didn't work for me, but I've managed to get to monkey's `update()` method and it worked.
Thanks!
