### ISSUE TITLE
shouldComponentUpdate still relevant

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#55]
First, awesome job in this lib! I have been looking for something to handle application state with a lot more flexibility and this just nails it :-)

*"This basically makes the shouldComponentUpdate method useless in most of cases and ensures that your components will only re-render if they need to because of data changes."*

This quote is a bit naive. The reason is that any time setState is run on a React component the nested components will also run their render method. So even if you reduce the number of rerenders by listening to specific state changes, you will still have the propagation issue. Wrote an article on it here: [An alternative render strategy with Flux and React JS](http://christianalfoni.github.io/javascript/2014/12/04/flux-and-eventemitter2.html)

What could actually be more performant with this lib is to use the "tree listener" on the top application component, listen for updates and then run "setState" there. That would run the render method on every component in the app exactly once per tree update. More predictable, a lot less code and you never have to worry about f.ex. one component update causing 5 nested components to rerender and one of those nested components also update and rerenders itself again and its children again :-)

Great job!

**Comment by Yomguithereal** [comment]
Thanks for the information @christianalfoni. I'll make sure to read your article asap to see how I can improve things for the library.
