### ISSUE TITLE
Support different validation methods. e.g. json-schema

### ISSUE THREAD

**Issue by Prestaul** [Yomguithereal/baobab#56]
How hard would it be to support use a replaceable `validate` method or some other mechanism for developers to specify a different validation scheme? For example, we already use json-schemas on the server and it would be ideal if we could use a json schema to validate a tree.

It is simple enough to compose multiple schemas to allow us to validate the entire tree, but it would be even better if we could mount schemas to validate specific cursors as an alternative.

For example maybe we could write something like the following: 
```js
function validateSchema(schema) {
    return function(data) { 
        return schemaValidator.validate(data, schema); 
    };
}

tree.select('users').validate(validateSchema(usersSchema));
tree.select('schedule').validate(validateSchema(scheduleSchema));
```

**Comment by Yomguithereal** [comment]
Hello @Prestaul,
This should not be too hard and I shall look what I can do about it soon. I feel however that the validation function should rather go into the tree's configuration so that events can be fired accordingly.

Besides, do you need a `validate` method at cursor level? If so, I can also see whether to implement it.

**Comment by Prestaul** [comment]
@Yomguithereal setting up validation on the tree would be sufficient. Adding validation to a cursor would just be a nice to have. Thanks for the response!

**Comment by Yomguithereal** [comment]
I what you need is validation of the tree on the fly, here is what you could currently do:

```js
function myCustomValidator() {...}

// Fired whenever an update is commited by the tree
tree.on('update', function(e) {

  // e.data.log holds an array of modified paths
  e.data.log.forEach(function(path) {
    var valid = myCustomValidator(tree.get(path), path);

    if (!valid) {
      // Do whatever feels right
      tree.emit('invalid', {errors: customErrors});
      console.log('The tree is invalid at path: ' + path.join('/'));
    }
  });
});
```

**Comment by Prestaul** [comment]
That looks very promising, but am I seeing correctly that it would not prevent the tree from entering that invalid state? Is there an even that fires prior to updating the state or (I'm guessing) is that what you would need to add to support this feature fully?

**Comment by Yomguithereal** [comment]
You are right indeed. There is no way currently to prevent the tree from entering an invalid state. But I am strongly considering to implement a way to do so. Any opinion on how this should be done? Cancel the whole update, Only apply the valid parts of the update?

**Comment by Prestaul** [comment]
I may not be the best person to ask because it depends largely on your implementation and I'm not familiar enough. Because you are buffering multiple changes and applying them on the next tick, it may make sense to apply individual changes that are valid. However, my gut instinct is that treating each update as a transaction makes the most sense and you should reject it entirely.

Maybe a better alternative is to allow the validation method to determine the final state of the tree? This may not be practical, but if the validation method were passed the currentState and proposedState of the tree (along with access the the change log) then it could determine what strategy to use. This seems the most flexible, but may not be practical. Because you've already implemented a state history, I'm guessing that this might not be too much of a stretch...

**Comment by Yomguithereal** [comment]
Hello @Prestaul. I am currently developing v1 and reworking the validation process.

Do you think a transaction-wide validation with option to rollback would be enough or should the validation be done at path level where updates are actually occurring?

```js
var tree = new Baobab(

  // Data
  {...},

  // Options
  {
    validate: function(oldState, newState, paths) {
      // Perform validation and return false if something breaked
    },
    validationBehaviour: 'rollback'
  }
);
```

**Comment by Prestaul** [comment]
I think transaction-wide is probably sufficient (and easiest to understand) in most cases. In my case, trying to validate each change individually would be extremely difficult because I'd like to use json-schemas we're already using in other places and schemas are not easy to apply at specific paths.

**Comment by Yomguithereal** [comment]
Ok. Done for `v1` following the example above.
