### ISSUE TITLE
"Touch" history

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#57]
Hi,

I just got this idea, thought I could run it by you.

Lets say you are making an ajax request, posting a new item to the server. Before optimistically updating the new item in the tree you could "touch" the tree. Like:

```javascript
addItem: function (item) {
  var beforeAdd = tree.touch();
  tree.select('items').push(item);
  ajax(item).success().error(function () {
    tree.reset(beforeAdd);
    tree.set('error', 'Could not add item');
  });
}
```

So if an error occurs you can easily reset the tree to whatever state it was when you touched it. A great way to easily reset state when something wrong occurs.

**Comment by Yomguithereal** [comment]
Hello @christianalfoni,
I am also currently trying to expand and improve the `history` option of baobab. I'd like, for instance, to enable the recording on cursors themselves for perf reasons mostly so that bigger part of your application would not clog the history.

The "touch" idea is seducing, however I wonder if this could work currently with the way I store transactions applied to the tree. What if, for instance, the tree has updated further when the ajax call fails? Does the tree rolls back further than necessary?

**Comment by christianalfoni** [comment]
That is a good point @Yomguithereal. I have been thinking a bit more about this, also the lib in general. If you think of this lib in a FLUX application I would suggest this is how it is used, a simplified example:

```javascript
var tree = new Baobab({foo: 'bar');

var state = {
  updateFoo: function (value) {
    tree.edit('foo', value);
  }
};

var actions = {
  changeFoo: function (value) {
    state.updateFoo(value);
  }
};

var Component = React.createClass({
  submit: function () {
    actions.changeFoo(this.refs.input.getDOMNode().value);
  },
  render: function () {
    return (
      <div>
        <div>{tree.get('foo')}</div>
        <input type="text" ref="input"/>
        <button onClick={this.submit}>Change foo</button>
      </div>
    );
  }
});
```
**state** is your tree mutation methods

**actions** is what the components call to update the state. They will do any async operations and use *state* methods to actually update the tree. This will keep a "one way flow" of state and make it easier to reason about the code and test it. (http://www.toptal.com/front-end/simple-data-flow-in-react-applications-using-flux-and-backbone)

So with some async stuff:

```javascript
var tree = new Baobab({items: [], isAddingItem: false);

var state = {
  addItem: function (item) {
    return tree.select('items').push(item);
  },
  isAddingItem: function (isAdding) {
    return tree.edit('isAddingItem', isAdding);
  }
};

var actions = {
  addItem: function (item) {
    var revertAdd = state.addItem(item);
    var revertAddingItem = state.isAddingItem(true);
    ajax.post('/items', item)
    .success(function () {
      revertAddingItem();
    })
    .error(function () {
      revertAdd();
      revertAddingItem();
    });
  }
};

/* SOME COMPONENT ADDING ITEMS */
```

Here you see the suggestion to "touch" coming back. After more though I think it would be better for each setter to return a "revert transaction" function. That way you would be able to easily revert any changes done to the tree.

What we have to think of here though is a scenario where you have added two items to the list before any ajax has returned. The first fails, the latter is a success:
- push transactions holds a reference to item added to list, so any revert is done on that specific item
- edit transactions holds a reference to the previous value. If a new transaction is done any previous transactions being reverted are ignored

An example of push revert would be that if even though two items are being added, each revert would have to point to the item being added and remove it.

An example of edit revert would be that "isLoading" state is being set and after 50 ms it is being set again. When the first edit is done and tries to revert it is ignored, because there is a newer transaction "in progress". 

Okay, this was just some ideas :-)

**Comment by Yomguithereal** [comment]
I will add, in a near future, a way to store history at cursor level. This should address this issue normally.

**Comment by Yomguithereal** [comment]
I guess this has become a little outdated :).

**Comment by gersongoulart** [comment]
Leaving it here for documentation purposes:
https://github.com/Yomguithereal/baobab#history

**Comment by christianalfoni** [comment]
Haha... ah, back in the days ;-)
