### ISSUE TITLE
toLocalStorage?

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#58]
Okay, sorry to just hammer out ideas without much suggested solutions, but it would also be great to say:

```javascript
tree.toLocalStorage();
tree.fromLocalStorage();
```

If the browser refreshes etc. you would easily be able to keep the state.

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, I indeed use the `localStorage` some times to store a tree so the application can keep its state across the browser "accidents".

However, I don't know if methods dealing with the `localStorage` should be part of the library for the following reasons:

* It is really simple to store the tree in the localStorage and does not take more than one or two lines usually.
* I always find myself wanting to keep only certain parts of the state in the `localStorage` and end up selecting part of the data I need.
* This is not isomorphic.

**Comment by christianalfoni** [comment]
You know what, that is very true, I think you are right about this :-) I just got a bit excited, hehe
