### ISSUE TITLE
PureRenderMixin

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#59]

**Comment by christianalfoni** [comment]
Hi, 

I just thought of that you should include PureRenderMixin with your other mixins, for tree and cursor. That way components does what you state in the documentation, only renders themselves :-)

This would be a great addition!

**Comment by Yomguithereal** [comment]
Yes I might do that but I do not want this library to include `react` as a dependency to do so. I don't see any other option right now than to let the user pass the mixin as an instantiation option.

**Comment by Yomguithereal** [comment]
The mixin itself is really easy to recode however (two lines of mixins and a shallow comparison function).

**Comment by christianalfoni** [comment]
Good point! But what if you allowed it as an option?

```javascript
var baobab = new Baobab(

  // Initial data
  {
    palette: {
      name: 'fancy',
      colors: ['blue', 'green']
    }
  },

  // Options
  {
    maxHistory: 5,
    clone: true,
    mixins: [React.PureRenderMixin]
  }
)
```
This would allow for users to attach other default mixins too.

**Comment by Yomguithereal** [comment]
Nice. I'll consider this asap.
