### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#62]
Hi,

Would you consider putting this on bower? Since React is there also it would be great to have Baobab :-)

One strategy here is to create a separate repo that only contains the build files of Baobab, "baobab-bower".

Since it is based on "tags" the workflow can be a bit confusing when sharing repo. At least I tend to forget using tags ;-)

**Comment by Yomguithereal** [comment]
The library should be available through bower now.

**Comment by christianalfoni** [comment]
Sweet stuff! Thanks :-)

I am writing up an article on using this with React in a flux architecture. Just have to do a bit more research, explore testing etc.
