### ISSUE TITLE
Tracking objects in array

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#65]
Hi,

I have been playing around with this a bit and I find it difficult to track my objects in arrays. For example:

```javascript
var tree = new Baobab({
  notifications: []
});

var notification = {type: 'foo', content: 'bar'};
tree.select('notifications').push(notification);
```

If I now want to edit the notification I would have to do something like this?:

```javascript
var tree = new Baobab({
  notifications: []
});

var notification = {type: 'foo', content: 'bar'};
tree.select('notifications').push(notification);

// LATER

var index = tree.select('notifications').get().indexOf(notification);
tree.select('notifications', index).set('type', 'whatever');
```

Is there a better way to track objects in an array?

Also, how would I got about removing an item from an array or a property from an object? Would I have to extract the whole thing, do my manipulation and then insert it again?

Would it break something if push returned a cursor for the object being inserted? Same with "set", it would return a cursor to the value inserted, instead of returning the current cursor?

This would be much like jQuery I believe. `$('div').first().append('<span/>')`... but I am not sure how that fits in with this :-)

**update**
Working a bit more with this I see there really is not a biggy extracting the array/object and modify, then edit it back into the cursor. You think that is "best practice"?

**Comment by Yomguithereal** [comment]
You certainly have a point here. However, for the time being, you can only access items in an array with their index. I could indeed return a cursor but I prefer returning `this` for the time being to enable chaining (Plus it would be awkward that some methods can chain and some cannot).

Problem here is that it might prove very difficult to track an item in a moving array (when unshifting and/or splicing etc.).

Could be possible to work with references but this is not very immutabley and would not work when cloning option is on.

Do you have other solutions in mind?

**Comment by christianalfoni** [comment]
Yeah, I agree with you on chaining, I was desperate ;-)

But what about this?:

```javascript

var tree = new Baobab({
  notifications: [],
  items: {
    '123': {}
  }
});

var notification = {foo: 'bar'};

tree.select('notifications').push(notification);
tree.select('notifications').select(0); // works now of course
tree.select('notifications').selectByReference(notification)

tree.select('notifications').remove(0);
tree.select('notifications').removeByReference(notification);

tree.select('items').select('123'); // works now of course
tree.select('items').remove('123');
```

 Hm, what do you think? :-)

**Comment by Yomguithereal** [comment]
1. The library indeed lacks of `remove`/`splice` methods (let me check clojure zippers before making any naming choice).
2. I am a bit cautious about doing anything concerning the references yet.

**Comment by christianalfoni** [comment]
In my experience I rarely use an index to find something in an array, I always use `indexOf` passing a reference to figure out the index only to get that thing out of the array. I think a very typical pattern with Baobab will be:

```javascript
var addItem = function (item) {
  baobab.select('items').push(item);
  ajax.post('/items', item)
    .success(function () {
      baobab.select('items').selectByReference(item).set('saved', true);
    })
    .error(function () {
      baobab.select('items').removeByReference(item);
    });
};
```

Maybe it is not Baobabs job to do this at all. Maybe it should just hold values. If you need to manipulate them you select -> mutate -> reinsert. Like:

``javascript
var addItem = function (item) {
  baobab.select('items').push(item);
  ajax.post('/items', item)
    .success(function () {
     var items =  baobab.select('items').get();
     item.saved = true;
     baobab.select('items').edit(items);
    })
    .error(function () {
      var items = baobab.select('items').get();
      items.splice(items.indexOf(item), 1);
      baobab.select('items').edit(items);
    });
};
```
But this does feel quite verbose and a bit unnatural because you do no really have to "edit". The only reason you do it is to trigger the "update" even. Hm hm...
