### ISSUE TITLE
Remove methods

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#70]
Related to #65.

**Comment by Yomguithereal** [comment]
Call them `$unset`.

**Comment by sskyy** [comment]
Need this method really bad, please implement it ASAP. Thx.

**Comment by christianalfoni** [comment]
You create a shortcut too? tree.unset('key'), cursor.unset('key')? :-)

**Comment by Yomguithereal** [comment]
This is the plan: a `$unset` keyword and `tree.unset`, `cursor.unset` and `cursor.remove`.

**Comment by christianalfoni** [comment]
:+1:

**Comment by christianalfoni** [comment]
btw, will it be possible to do this?:

```javascript
cursor.up().remove(cursor); ?
```
Or is that what `cursor.remove` does?

**Comment by Yomguithereal** [comment]
`cursor.remove` will be the same to `cursor.unset` as `cursor.edit` is to `cursor.set`. It will remove the node at cursor.

**Comment by christianalfoni** [comment]
Oki, cool, that will be nice indeed :-)

**Comment by mkuklis** [comment]
I'm looking forward to this as well!

**Comment by Yomguithereal** [comment]
`remove` and `unset` methods has been added. Is there someone brave enough to test them and tell me whether they work as expected before I release `0.4.0`?

**Comment by christianalfoni** [comment]
Is it built? Test it on JSBIN :-)

**Comment by Yomguithereal** [comment]
Yes it is.

**Comment by christianalfoni** [comment]
Cool, I will check it :)

**Comment by christianalfoni** [comment]
Hmm, do not think it quite works: http://jsbin.com/worigebiru/1/

**Comment by Yomguithereal** [comment]
Just checked it and it seems to work. The `bar` key was removed.

**Comment by christianalfoni** [comment]
Uhm? It is not removed when I run it?

**Comment by christianalfoni** [comment]
Ah, it must be JSBIN, works okay in console

**Comment by christianalfoni** [comment]
Check again, arrays does not seem to work? http://jsbin.com/worigebiru/1/

**Comment by Yomguithereal** [comment]
Your test works. But the chrome console always show you the *current*  state of the object your are displaying rather than the state of the object at the moment of the log. The console says there are 2 items in the array but there is really only one.

**Comment by christianalfoni** [comment]
Ah, of course, forgetting about the async. Updated with manual committing, it works :-)

**Comment by christianalfoni** [comment]
Hm, did you check the length of the array when you remove? Might be jsbin again, but there seems to be something weird happening with the indexing and length of array?

**Comment by Yomguithereal** [comment]
The length of the array does not change because, for the time being, I use the `delete` keyword. There is a decision to be made here: should I splice the array and maybe compromise other index-based cursors or should I keep it the way it is?

**Comment by christianalfoni** [comment]
Ah, I see your point, but I really think you should change that behavior because the array becomes broken. In my opinion the index selector is "watch that position in the array", not the actual content. If I want to track the content I use `tree.select('items', {id: 123})`.

I think there are more situations too where you would get into trouble thinking of the index cursor as a "pointing to value of index", like applying and splicing manually etc.

Does that make sense? :-)

**Comment by Yomguithereal** [comment]
This makes sense. I will fix this behaviour asap and add some more safeguards about this.

**Comment by christianalfoni** [comment]
:+1:

**Comment by Yomguithereal** [comment]
Attempt to fix behaviour as per 9008d763d409a7f76632f132d7c1208851fb2762 (wrongly refered to another issue).

Can you run your tests again @christianalfoni and tell me whether this fix actually fits (unit tested already but I am superstitious sometimes).

**Comment by christianalfoni** [comment]
It looks good :-) Ran it again on this bin http://jsbin.com/worigebiru/1/edit?html,js,console,output. Indexes are correct and length is correct.

**Comment by Yomguithereal** [comment]
Good, I will release a `0.4.1` soon then along with some bug fixes. Next step should be `1.0.0` I hope.

**Comment by christianalfoni** [comment]
awesome :+1:
