### ISSUE TITLE
New version, updating component state cursor

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#85]
Hi there,

Sorry to not have looked into this first, but I am on the train and will first be able to check it out tomorrow :-)

```javascript
var React = require('react');
var Baobab = require('baobab');
var tree = new Baobab({
  admin: {
    items: []
  }
}, {
  mixins: [React.addons.PureRenderMixin],
  shiftReferences: true
});

// Pointing to the cursor like this does _not_ update the component
var Parent = React.createClass({
  mixins: [tree.mixin],
  cursor: ['admin'],
  render: function () {
    return (
        <ul>
          {this.state.cursor.items.map(function (item) {
            return <li>{item}</li>
          })}
        </ul>
    );
  }
});

// But this works :-)
var Parent = React.createClass({
  mixins: [tree.mixin],
  cursor: ['admin', 'items'],
  render: function () {
    return (
        <ul>
          {this.state.cursor.map(function (item) {
            return <li>{item}</li>
          })}
        </ul>
    );
  }
});

// But this does _not_ work either
var Parent = React.createClass({
  mixins: [tree.select('admin').mixin],
  cursor: ['items'],
  render: function () {
    return (
        <ul>
          {this.state.cursor.map(function (item) {
            return <li>{item}</li>
          })}
        </ul>
    );
  }
});
```

There seems to be a requirement to point directly to a value for it to understand the updates. Again, I am sorry not to have looked more into this. I will check it out tomorrow, just thought I would mention it.

Otherwise, this is looking spectacular :-D

**Comment by Yomguithereal** [comment]
Yes, you are right indeed. This is because the `admin` reference was not shifted, only the `items` one. Would the react update addon shift its reference in this kind of case?

Concerning the third case, in cannot work because you are using a cursor mixin and the cursor mixin does not make any use of the `cursor` property.

**Comment by Yomguithereal** [comment]
Need to check here but I think react updates only alter top-level references. Furthermore, I think there is a problem when using the `PureRenderMixin` here with tree-level `cursors` mixins since the check performed is shallow.

**Comment by christianalfoni** [comment]
Hi again,

Yeah, this is the issue. Check out [this bin](http://jsbin.com/buvetafoci/1/edit?html,js,console). It does change the reference of parent objects/arrays up the tree.

Sorry this got lost in the discussions, but yeah, it is kind of important :-)

**Comment by christianalfoni** [comment]
I saw in the source code you have some parent references? So I guess it is doable? :-)

**Comment by christianalfoni** [comment]
This also gives a nice correlation with the update events. It both updates the reference and triggers and update even.

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, I just committed a fix (well, I hope it is). Can you tell me if this works for you so I can release a patch if this works?

**Comment by christianalfoni** [comment]
Hi @Yomguithereal,

I have done some simple tests and it looks great! I will be able to integrate this in a larger project on monday, to really test it. But I would say this is working :-)

What I really like about this is that the API has become even smoother. You just use a cursor mixin and you got the values on your state. It is really great!

I am finishing up my article on this and will publish it next week after testing it in the larger project. I also have an article ready for codementors.com that mentions Baoabab. I think this is a great contribution to the evolving flux community. Fantastic job! :-)
