### ISSUE TITLE
Event emitting effectiveness

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#90]
Hi there!

We have started working on a layer that uses Baobab with React JS. The layer is basically an API that puts a specific structure to the tree and allows for Backbone like updates. It is kinda awesome, will tell you more later :-)

Anyways, I am thinking about the `asynchronous` option. As I understand it, by having this set to true Baobab will run its tree update operation after possibly multiple updates has been done? Do you see this update as expensive? We have some issues with configuring the tree, where multiple operations to a non existing cursor gives some issues. I am wondering if you have any thoughts on the consequence of setting this to false?

One other thing. Is the events triggered synchronously? What I would see as an optimization is that all events that will trigger would do so in a "requestAnimationFrame". That would make sure that tree tells components about updates with optimal timing . What do you think?

I think by using `asynchronous = false`, but collecting events until the next  `requestAnimationFrame` runs would be a super solution for us. Maybe it could be an option?

About the `asynchronous`, it would be great to change that option "on the fly"... would that be possible? :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni,

1. The updates are asynchronous so multiple updates can stack and so that mutations are optimized and merged before they are done. (If you perform a set twice on the same node, I will only execute the latter). Plus executing updates in a nested tree is inherently recursive and costly so I only walk the tree once per update.

2. You are mentioning issues concerning multiple updates: can you tell me more about it because it could be bug in the library I did not catch earlier.

3. There is an `autoCommit` option that you can set to `false` if you need to control finely when the tree updates through the `commit` method.

4. Events are triggered synchronously. The tree updates on the next animation frame by [default](https://github.com/Yomguithereal/baobab/blob/master/src/helpers.js#L232-L236) (given the browser is able to do so of course).

5. I am not entirely sure it would work but I think you can change the `asynchronous` option on the fly by doing:

```js
tree.options.asynchronous = false;
```

**Comment by christianalfoni** [comment]
Hi again and thanks for the quick response :-)

1. Aha, I see. But with a flat tree that would not be much of an issue I suppose? But does the events still trigger asynchronously? So even though three updates are done synchronously it still waits for next animation frame to fire off only needed events? Not three times the events actually needed?

2. Well, the tree is initially empty and you use an API to configure it. If you run one method to set a cursor and then on the same tick do an update to that cursor, it seems to fail. As if the cursor is not there yet. Does that make sense or maybe you need an example?

3. Yeah, I was wondering about that commit method. Where do I run it? I can not run it on cursors it seems. Do I run it on the tree itself? That could actually be a solution to the configuring part

4. That is awesome :-)

5. Okay, fallback, I will check the autoCommit first!

Thanks for your answers! BTW, check out this awesome comment on the Baobab article!: http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html#comment-1843788866

**Comment by christianalfoni** [comment]
Awesome, autoCommit solved the issue. Thanks again for the quick response! And it is really good to know that the tree updates on requestAnimationFrame.

**Comment by Yomguithereal** [comment]
1. Let's say you disable the `asynchronous` flag: the tree will actually commit its updates every time you stack an update, so yes, one event per update. But `autoCommit` to false is really the thing here for I do not really see any use cases where you would like to update the tree synchronously but fire the event only at the next frame.

```js
tree.select('items').push(1).push(2);
tree.commit();
```

2. I should probably investigate this. It smells like bug. Any example you have is of course valuable.

3. The commit method belongs to the tree. Do you find the documentation lacking about that? I should probably improve it.

**Comment by christianalfoni** [comment]
1. Yup, autoCommit works like a charm :-)

2. An example would be to start with an empty tree. Then do an edit on none existing cursor and insert an object that has a nested object, then on next line try to point to the nested object with a cursor and edit that. I think the second one will fail.

3. Figured it out, yeah. Hm, I think it would be good to point out that commit() has to be done on the tree. Maybe comment it next to the example?

**Comment by Yomguithereal** [comment]
Closing this issue in favor of #101.
