### ISSUE TITLE
Indicate that merge is shallow

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#92]

**Comment by nickdima** [comment]
Can you explain shallow merging for those not familiar with the concept?

**Comment by christianalfoni** [comment]
Hi @nickdima ,

Updated the wiki with this: https://github.com/Yomguithereal/baobab/wiki/Merge

**Comment by nickdima** [comment]
@christianalfoni great, thanks!
I think you're missing `age` here in the result?

```javascript
tree.select('user').merge({ age: 30, likes: 'apples'});

// On update event
tree.select('user').get();
>>> { name: 'Bob', likes: 'apples', settings: { foo: 'bar' } }
```

**Comment by christianalfoni** [comment]
Ah, thanks for pointing that out! Fixed :-)

**Comment by nickdima** [comment]
Great, I think you can close the issue if you want.
