### ISSUE TITLE
Latency issue

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#95]
Hi there!

We are using Baobab with great success, though have started to come across a latency issue. We are using it with `shiftReferences: true`.

When I run a profiler in Chrome Baboab spends a lot of time in typology.js. Here is a screenshot:

![screen shot 2015-02-23 at 14 51 43](https://cloud.githubusercontent.com/assets/3956929/6328820/8eb81b72-bb6b-11e4-8b97-1e4029c09fa6.png)

The tree is not really that big. You have any initial theories on why it gets slow? What does typology actually do?

Thanks :-)

**Comment by christianalfoni** [comment]
I checked this out some more. By just commenting out all the calls to typology.check , using custom `typeof` etc. checks, I got this profile instead... crazy faster... from 600ms to 27ms.

![screen shot 2015-02-23 at 15 02 32](https://cloud.githubusercontent.com/assets/3956929/6329005/082b712e-bb6d-11e4-9b1f-6d5d297aa7cf.png)

Do you see any problems replacing typology with custom type checks instead? Or am I missing something? :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, you make a fine point.

1. I will file an issue on the `typology` repository and work on it with @jacomyal so the perf can be boosted.
2. Maybe it's time to drop this dependencies from Baobab and let the user decide of its own validation scheme when he needs the tree to be validated. This could mean, as you said, better perfs and smaller library size.

**Comment by christianalfoni** [comment]
Yeah, I was actually a bit surprised that there was validation here. Maybe its a zipper thing? As I see it I just want to but plain objects, arrays and primitives in my tree and I have actions doing that. So in a relatively big application I would maybe have like 20-30 methods doing all the updates of the tree, and those methods are tested. So yeah... to me it feels like the tree updates should be tested, not validated, as an invalid update is a bug in your application?

But again, that is just my opinion and I probably do not see all use cases :-) But yes, it would be great if this was optional all together.

**Comment by Yomguithereal** [comment]
Fixed as per f8aac1fd80ed6a81097d94c736f5d5a975090602.
